import Link from "next/link"
import { ArrowRight, CheckCircle2, CircleDollarSign, Radar, ShieldCheck, Sparkles } from "lucide-react"
import { AppShell } from "@/components/app-shell"
import { AcquisitionAttribution } from "@/components/acquisition/acquisition-attribution"
import type { AcquisitionPage } from "@/lib/acquisition-pages"

const base="https://hegevaai.co.uk"
export function AcquisitionPageView({page}:{page:AcquisitionPage}){
 const jsonLd=[{"@context":"https://schema.org","@type":"WebApplication",name:"HEGEVA AI",url:`${base}/${page.slug}`,applicationCategory:"BusinessApplication",operatingSystem:"Web",description:page.description,offers:[{"@type":"Offer",name:"Premium",price:"14.99",priceCurrency:"GBP"},{"@type":"Offer",name:"Pro",price:"29.99",priceCurrency:"GBP"}]},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"HEGEVA AI",item:base},{"@type":"ListItem",position:2,name:page.h1,item:`${base}/${page.slug}`}]},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:page.faq.map(({q,a})=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]
 const cta=`/login?callbackURL=%2Fcommand-center&source=${page.slug}`
 return <AppShell><main><AcquisitionAttribution path={`/${page.slug}`}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}}/>
  <section className="relative overflow-hidden border-b border-border"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_72%_18%,oklch(.76_.14_168/.13),transparent_32%),radial-gradient(circle_at_20%_70%,oklch(.78_.13_85/.08),transparent_34%)]"/><div className="relative mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-[1.12fr_.88fr] lg:items-center"><div><p className="ve-eyebrow">{page.eyebrow}</p><h1 className="mt-4 max-w-4xl font-display text-4xl font-semibold leading-[1.04] tracking-tight sm:text-6xl">{page.h1}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">{page.lead}</p><div className="mt-8 flex flex-wrap gap-3"><Link data-acquisition-event="registration_start" href={cta} className="hegeva-primary inline-flex min-h-12 items-center gap-2 px-6">Start your workspace<ArrowRight className="size-4"/></Link><Link data-acquisition-event="pricing_view" href="/pricing" className="hegeva-secondary inline-flex min-h-12 items-center gap-2 px-6">View pricing</Link></div><p className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 text-primary"/>Real workspace data when signed in · owner-controlled actions</p></div><aside className="rounded-[2rem] border border-primary/25 bg-black/25 p-6 shadow-2xl shadow-black/30 backdrop-blur sm:p-8" aria-label="HEGEVA product proof"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl border border-primary/30 bg-primary/10"><Radar className="size-5 text-primary"/></span><div><small className="text-primary">HEGEVA CORE · PRODUCT PROOF</small><h2 className="font-semibold">{page.proofTitle}</h2></div></div><p className="mt-5 text-sm leading-6 text-muted-foreground">{page.proofBody}</p><ol className="mt-6 space-y-3"><li className="rounded-2xl border border-border bg-background/50 p-4"><small className="text-gold">SIGNAL</small><p className="mt-1 text-sm font-semibold">{page.signal}</p></li><li className="rounded-2xl border border-border bg-background/50 p-4"><small className="text-cyan-300">WHY IT MATTERS</small><p className="mt-1 text-sm">{page.why}</p></li><li className="rounded-2xl border border-primary/25 bg-primary/[.06] p-4"><small className="text-primary">RECOMMENDED ACTION</small><p className="mt-1 text-sm font-semibold">{page.action}</p></li></ol><p className="mt-4 flex gap-2 text-xs text-muted-foreground"><CheckCircle2 className="size-4 shrink-0 text-primary"/>{page.outcome}</p></aside></div></section>
  <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="max-w-3xl"><h2 className="font-display text-3xl font-semibold">One intelligent system for the work behind your business</h2><p className="mt-4 text-base leading-7 text-muted-foreground">{page.problem}</p><p className="mt-3 text-base leading-7 text-muted-foreground">{page.audience}</p></div><div className="mt-10 grid gap-8 lg:grid-cols-3">{page.sections.map((section,index)=><article key={section.title} className="border-t border-primary/30 pt-5"><span className="font-mono text-xs text-gold">0{index+1}</span><h2 className="mt-3 font-display text-2xl font-semibold">{section.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{section.body}</p><ul className="mt-5 space-y-3">{section.points.map(point=><li key={point} className="flex gap-2 text-sm"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-primary"/>{point}</li>)}</ul></article>)}</div></section>
  <section className="border-y border-border bg-primary/[.035]"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 sm:px-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="ve-eyebrow">HOW HEGEVA WORKS</p><h2 className="mt-3 font-display text-3xl font-semibold">Understand. Prioritise. Prepare. Improve.</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">HEGEVA connects operational evidence to the next supported action. It does not promise unrestricted automation.</p></div><ol className="grid gap-3 sm:grid-cols-2">{["UNDERSTAND the real business signal","PRIORITISE by evidence and impact","PREPARE the supported next step","APPROVE before controlled execution","MEASURE the workspace outcome","IMPROVE using verified progress"].map((item,index)=><li key={item} className="flex items-center gap-3 rounded-2xl border border-border bg-background/45 p-4"><span className="font-mono text-xs text-primary">{String(index+1).padStart(2,"0")}</span><strong className="text-sm">{item}</strong></li>)}</ol></div></section>
  <section className="mx-auto max-w-5xl px-5 py-16 sm:px-8"><div className="flex items-center gap-3"><Sparkles className="size-5 text-gold"/><h2 className="font-display text-3xl font-semibold">Questions business owners ask</h2></div><div className="mt-8 divide-y divide-border border-y border-border">{page.faq.map(item=><article key={item.q} className="py-6"><h3 className="font-semibold">{item.q}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.a}</p></article>)}</div><nav className="mt-10" aria-label="Related HEGEVA guides"><h2 className="text-sm font-semibold">Explore related HEGEVA workflows</h2><div className="mt-4 flex flex-wrap gap-3">{page.related.map(item=><Link key={item.href} href={item.href} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border px-4 text-sm hover:border-primary/40">{item.label}<ArrowRight className="size-4"/></Link>)}</div></nav></section>
  <section className="mx-auto max-w-5xl px-5 pb-20 sm:px-8"><div className="rounded-[2rem] border border-gold/25 bg-gradient-to-r from-gold/[.08] via-background to-primary/[.08] p-8 text-center sm:p-12"><CircleDollarSign className="mx-auto size-7 text-gold"/><h2 className="mt-4 font-display text-3xl font-semibold">Your business. One intelligent system.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-muted-foreground">Start with a real customer and unlock your live Operating Picture. Premium is £14.99/month and Pro is £29.99/month. Applicable taxes are shown before payment.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link data-acquisition-event="registration_start" href={cta} className="hegeva-primary inline-flex min-h-12 items-center gap-2 px-6">Create your workspace<ArrowRight className="size-4"/></Link><Link data-acquisition-event="pricing_view" href="/pricing" className="hegeva-secondary inline-flex min-h-12 items-center px-6">Compare plans</Link></div></div></section>
 </main></AppShell>
}
