export function applyHardcoreVisualPolish(html: string) {
  if (!html || html.includes('data-hegeva-hardcore="v6"')) return html

  const style = `<style data-hegeva-hardcore="v6">
:root{--hw-bg:#030805;--hw-surface:#08150f;--hw-surface2:#0c2016;--hw-surface3:#112a1d;--hw-line:rgba(111,238,190,.14);--hw-line-strong:rgba(111,238,190,.34);--hw-text:#f8fcfa;--hw-muted:#9db4aa;--hw-green:#2be3a1;--hw-green2:#7bf3c5;--hw-gold:#e8c96f;--hw-blue:#7bc7ff;--hw-danger:#ff9292;--hw-shadow:0 34px 100px rgba(0,0,0,.40);--hw-soft:0 16px 44px rgba(0,0,0,.22)}
html{background:var(--hw-bg)!important;scroll-behavior:smooth!important}body{background:radial-gradient(circle at 86% -9%,rgba(43,227,161,.19),transparent 30%),radial-gradient(circle at 6% 24%,rgba(232,201,111,.07),transparent 25%),linear-gradient(180deg,#06100c 0%,#020604 100%)!important;color:var(--hw-text)!important;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important;letter-spacing:-.01em!important;-webkit-font-smoothing:antialiased!important}
body::before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.22;background-image:linear-gradient(rgba(255,255,255,.015) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.015) 1px,transparent 1px);background-size:40px 40px;mask-image:linear-gradient(to bottom,black,transparent 75%)}
.shell,.layout,.dashboard-layout{position:relative;z-index:1}.main,main,.content,.page{position:relative;z-index:1}
aside,.side,.sidebar{background:linear-gradient(180deg,rgba(3,13,9,.992),rgba(4,17,12,.97))!important;border-color:var(--hw-line)!important;box-shadow:16px 0 54px rgba(0,0,0,.22)!important}.brand{letter-spacing:-.04em!important}.brand small{letter-spacing:.19em!important}
nav button,nav a,.nav button,.nav a{border:1px solid transparent!important;transition:transform .18s ease,background .18s ease,border-color .18s ease,color .18s ease,box-shadow .18s ease!important}nav button:hover,nav a:hover,.nav button:hover,.nav a:hover{transform:translateX(3px)!important;border-color:rgba(111,238,190,.13)!important}nav .active,.nav .active,[aria-current="page"]{background:linear-gradient(90deg,rgba(43,227,161,.15),rgba(43,227,161,.04))!important;border-color:rgba(111,238,190,.19)!important;box-shadow:inset 3px 0 0 var(--hw-green),0 10px 26px rgba(0,0,0,.12)!important}
header,.header,.hero,.top,.page-header{position:relative;overflow:hidden;background:linear-gradient(135deg,rgba(19,53,39,.985),rgba(6,22,16,.98))!important;border:1px solid var(--hw-line-strong)!important;box-shadow:var(--hw-shadow)!important}header::before,.header::before,.hero::before,.top::before,.page-header::before{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(115deg,rgba(255,255,255,.04),transparent 32%,rgba(43,227,161,.04) 70%,transparent)!important}header::after,.header::after,.hero::after,.top::after,.page-header::after{content:"";position:absolute;width:330px;height:330px;right:-145px;top:-190px;border-radius:999px;background:radial-gradient(circle,rgba(43,227,161,.21),transparent 66%);pointer-events:none}
h1{letter-spacing:-.062em!important;line-height:1!important;text-wrap:balance!important}h2,h3{letter-spacing:-.03em!important;text-wrap:balance!important}p{max-width:72ch}
.card,.panel,.widget,article,section{border-color:var(--hw-line)!important;box-shadow:var(--hw-soft)!important}.card,.panel,.widget{background:linear-gradient(180deg,rgba(18,44,33,.96),rgba(7,22,16,.99))!important}.panel,.card,.widget{position:relative;overflow:hidden}.panel::after,.card::after,.widget::after{content:"";position:absolute;inset:0 0 auto;height:1px;background:linear-gradient(90deg,transparent,rgba(123,243,197,.27),transparent);pointer-events:none}
.stats{align-items:stretch!important;grid-auto-rows:1fr!important}.stats .card,.kpi,.metric-card{min-height:126px!important;display:flex!important;flex-direction:column!important;justify-content:space-between!important;transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease!important}.stats .card:hover,.kpi:hover,.metric-card:hover{transform:translateY(-4px)!important;border-color:var(--hw-line-strong)!important;box-shadow:0 28px 72px rgba(0,0,0,.31)!important}.stats .card:nth-child(2n),.kpi:nth-child(2n){background:linear-gradient(180deg,rgba(19,42,34,.97),rgba(7,21,17,.99))!important}.stats .card strong,.kpi strong,.metric-card strong{font-variant-numeric:tabular-nums!important;letter-spacing:-.05em!important}.stats .card small,.kpi small,.metric-card small{text-transform:uppercase!important;letter-spacing:.075em!important;font-size:.72em!important;color:var(--hw-muted)!important}
.grid{align-items:stretch!important}.grid>.panel,.grid>.card,.grid>.widget{height:100%!important}.grid.three{gap:16px!important}.toolbar{row-gap:10px!important}.quick{gap:9px!important}
button,.action,[role="button"]{transition:transform .16s ease,box-shadow .16s ease,filter .16s ease,border-color .16s ease!important}button:hover,.action:hover,[role="button"]:hover{transform:translateY(-1px)!important;filter:brightness(1.04)!important}button:active,.action:active,[role="button"]:active{transform:translateY(0)!important}button:disabled{transform:none!important;filter:none!important;opacity:.5!important}button.action,.primary,.btn-primary{background:linear-gradient(135deg,var(--hw-green),var(--hw-green2))!important;color:#021109!important;box-shadow:0 15px 38px rgba(43,227,161,.21)!important}button.action:hover,.primary:hover,.btn-primary:hover{box-shadow:0 20px 48px rgba(43,227,161,.29)!important}.mini,.secondary,.btn-secondary{border-color:rgba(255,255,255,.10)!important;background:rgba(255,255,255,.025)!important}.mini:hover,.secondary:hover,.btn-secondary:hover{border-color:rgba(111,238,190,.23)!important;background:rgba(43,227,161,.06)!important}
input,select,textarea{background:rgba(3,14,10,.95)!important;border-color:rgba(255,255,255,.11)!important;color:var(--hw-text)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.022)!important;transition:border-color .16s ease,box-shadow .16s ease,background .16s ease!important}input:hover,select:hover,textarea:hover{border-color:rgba(255,255,255,.18)!important}input:focus,select:focus,textarea:focus{background:rgba(5,20,14,.98)!important;border-color:rgba(43,227,161,.68)!important;box-shadow:0 0 0 3px rgba(43,227,161,.11),inset 0 1px 0 rgba(255,255,255,.02)!important}
.tablewrap{background:rgba(2,10,7,.36)!important;border-color:rgba(255,255,255,.065)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.015)!important}.table thead,.table th,thead th{background:rgba(255,255,255,.03)!important;letter-spacing:.075em!important}.table tbody tr,tbody tr{transition:background .14s ease!important}.table tbody tr:hover,tbody tr:hover{background:rgba(43,227,161,.05)!important}.table td,.table th{border-color:rgba(255,255,255,.055)!important}
.badge,[class*="badge"]{backdrop-filter:blur(10px)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.04)!important}.empty{min-height:104px!important;display:flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;border:1px dashed rgba(111,238,190,.19)!important;border-radius:16px!important;background:linear-gradient(135deg,rgba(43,227,161,.032),rgba(232,201,111,.024))!important;color:var(--hw-muted)!important}.empty::before{content:"✦";margin-right:9px;color:var(--hw-green)!important;opacity:.88}
.chart,.bars{border-radius:18px!important;background:linear-gradient(180deg,rgba(255,255,255,.02),transparent)!important;padding-inline:14px!important}.bar{box-shadow:0 14px 36px rgba(43,227,161,.13)!important;transition:filter .16s ease,transform .16s ease!important}.bar:hover{filter:brightness(1.13)!important;transform:translateY(-3px)!important}.activity>div,.dueItem{transition:transform .16s ease,border-color .16s ease,background .16s ease!important}.activity>div:hover,.dueItem:hover{transform:translateX(3px)!important;border-color:var(--hw-line-strong)!important;background:rgba(43,227,161,.035)!important}.quick button{background:linear-gradient(180deg,rgba(43,227,161,.09),rgba(43,227,161,.035))!important;border-color:var(--hw-line)!important}.quick button:hover{border-color:var(--hw-line-strong)!important;box-shadow:0 14px 34px rgba(0,0,0,.20)!important}.toast,[role="status"]{backdrop-filter:blur(16px)!important}.sideFoot{background:linear-gradient(180deg,rgba(43,227,161,.065),rgba(43,227,161,.025))!important;border-color:rgba(111,238,190,.17)!important}
::selection{background:rgba(43,227,161,.29)!important;color:#fff!important}:focus-visible{outline:3px solid rgba(123,243,197,.87)!important;outline-offset:3px!important}
@media(min-width:1180px){.main,main,.content,.page{max-width:1500px!important}.stats{gap:14px!important}.grid.three{gap:16px!important}}
@media(max-width:980px){.shell,.layout,.dashboard-layout{grid-template-columns:1fr!important}.side,.sidebar,aside{position:relative!important;top:auto!important;height:auto!important;border-right:0!important;border-bottom:1px solid var(--hw-line)!important}.nav,nav{display:flex!important;overflow-x:auto!important;gap:7px!important;padding-bottom:5px!important;scroll-snap-type:x proximity!important;-webkit-overflow-scrolling:touch!important}.nav>*,nav>*{flex:0 0 auto!important;scroll-snap-align:start!important}.sideFoot{position:static!important;margin-top:10px!important}.main,main,.content,.page{padding-top:18px!important}}
@media(max-width:800px){body::before{display:none}.main,main,.content,.page{padding-left:12px!important;padding-right:12px!important}header,.header,.hero,.top,.page-header{border-radius:18px!important}.top,.header,.page-header{flex-direction:column!important;gap:12px!important}.stats{gap:9px!important;grid-template-columns:repeat(2,minmax(0,1fr))!important}.stats .card,.kpi,.metric-card{min-height:104px!important}.grid,.grid.three{grid-template-columns:1fr!important}.formgrid,.formgrid.two{grid-template-columns:1fr!important}.tablewrap{border-radius:12px!important}.panel,.card,.widget{border-radius:16px!important}button,input,select,textarea{min-height:46px!important}.toolbar{align-items:stretch!important}.toolbar>*{max-width:100%!important}}
@media(max-width:520px){.stats .card strong,.kpi strong,.metric-card strong{font-size:1.62rem!important}.quick{display:grid!important;grid-template-columns:1fr 1fr!important}.quick button{width:100%!important}.tablewrap{margin-inline:-2px!important}.main,main,.content,.page{padding-left:9px!important;padding-right:9px!important}.verified{white-space:normal!important;align-self:flex-start!important}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto!important}*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
</style>`

  const script = `<script data-hegeva-hardcore="v6">(()=>{document.documentElement.classList.add('hegeva-hardcore-v6');const enhance=()=>{document.querySelectorAll('button').forEach(b=>{if(!b.hasAttribute('type')&&!b.closest('form'))b.setAttribute('type','button')});document.querySelectorAll('table').forEach(t=>{const p=t.parentElement;if(p&&!p.classList.contains('tablewrap')){const w=document.createElement('div');w.className='tablewrap';p.insertBefore(w,t);w.appendChild(t)}});document.querySelectorAll('input,select,textarea').forEach((el,i)=>{if(!el.getAttribute('aria-label')&&!el.getAttribute('aria-labelledby'))el.setAttribute('aria-label',el.getAttribute('placeholder')||el.getAttribute('name')||('Field '+(i+1)))});document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{const id=a.getAttribute('href')?.slice(1);const target=id&&document.getElementById(id);if(target)target.scrollIntoView({behavior:'smooth',block:'start'})}));document.querySelectorAll('nav button,.nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('nav button,.nav button').forEach(x=>x.removeAttribute('aria-current'));b.setAttribute('aria-current','page')}))};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance,{once:true});else enhance()})();</script>`

  let next = html
  next = next.replace(/<style data-hegeva-hardcore="v[45]">[\s\S]*?<\/style>/gi, "")
  next = next.replace(/<script data-hegeva-hardcore="v[45]">[\s\S]*?<\/script>/gi, "")
  next = /<\/head>/i.test(next) ? next.replace(/<\/head>/i, `${style}\n</head>`) : `${style}\n${next}`
  next = /<\/body>/i.test(next) ? next.replace(/<\/body>/i, `${script}\n</body>`) : `${next}\n${script}`
  return next
}
