export function applyHardcoreVisualPolish(html: string) {
  if (!html || html.includes('data-hegeva-hardcore="v5"')) return html

  const style = `<style data-hegeva-hardcore="v5">
:root{--hw-bg:#040906;--hw-surface:#091710;--hw-surface2:#0d2117;--hw-surface3:#132c20;--hw-line:rgba(111,238,190,.15);--hw-line-strong:rgba(111,238,190,.32);--hw-text:#f8fcfa;--hw-muted:#9fb6ac;--hw-green:#2be3a1;--hw-green2:#7bf3c5;--hw-gold:#e8c96f;--hw-blue:#7bc7ff;--hw-danger:#ff9292;--hw-shadow:0 34px 100px rgba(0,0,0,.38);--hw-soft:0 16px 42px rgba(0,0,0,.20)}
html{background:var(--hw-bg)!important;scroll-behavior:smooth!important}body{background:radial-gradient(circle at 84% -8%,rgba(43,227,161,.18),transparent 31%),radial-gradient(circle at 7% 28%,rgba(232,201,111,.065),transparent 25%),linear-gradient(180deg,#06100c 0%,#030705 100%)!important;color:var(--hw-text)!important;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important;letter-spacing:-.01em!important;-webkit-font-smoothing:antialiased!important}
body::before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.24;background-image:linear-gradient(rgba(255,255,255,.016) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.016) 1px,transparent 1px);background-size:38px 38px;mask-image:linear-gradient(to bottom,black,transparent 72%)}
.shell,.layout,.dashboard-layout{position:relative;z-index:1}.main,main,.content,.page{position:relative;z-index:1}
aside,.side,.sidebar{background:linear-gradient(180deg,rgba(3,13,9,.985),rgba(5,18,13,.96))!important;border-color:var(--hw-line)!important;box-shadow:14px 0 48px rgba(0,0,0,.20)!important}
.brand{letter-spacing:-.035em!important}.brand small{letter-spacing:.18em!important}
nav button,nav a,.nav button,.nav a{border:1px solid transparent!important;transition:transform .18s ease,background .18s ease,border-color .18s ease,color .18s ease,box-shadow .18s ease!important}nav button:hover,nav a:hover,.nav button:hover,.nav a:hover{transform:translateX(2px)!important;border-color:rgba(111,238,190,.12)!important}nav .active,.nav .active,[aria-current="page"]{background:linear-gradient(90deg,rgba(43,227,161,.13),rgba(43,227,161,.045))!important;border-color:rgba(111,238,190,.18)!important;box-shadow:inset 3px 0 0 var(--hw-green)!important}
header,.header,.hero,.top,.page-header{position:relative;overflow:hidden;background:linear-gradient(135deg,rgba(18,50,37,.98),rgba(7,24,18,.975))!important;border:1px solid var(--hw-line-strong)!important;box-shadow:var(--hw-shadow)!important}
header::before,.header::before,.hero::before,.top::before,.page-header::before{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(115deg,rgba(255,255,255,.035),transparent 34%,rgba(43,227,161,.035) 72%,transparent)!important}
header::after,.header::after,.hero::after,.top::after,.page-header::after{content:"";position:absolute;width:300px;height:300px;right:-130px;top:-178px;border-radius:999px;background:radial-gradient(circle,rgba(43,227,161,.19),transparent 66%);pointer-events:none}
h1{letter-spacing:-.06em!important;line-height:1.01!important;text-wrap:balance!important}h2,h3{letter-spacing:-.028em!important;text-wrap:balance!important}p{max-width:72ch}
.card,.panel,.widget,article,section{border-color:var(--hw-line)!important;box-shadow:var(--hw-soft)!important}.card,.panel,.widget{background:linear-gradient(180deg,rgba(18,44,33,.95),rgba(8,24,18,.985))!important}
.panel,.card,.widget{position:relative;overflow:hidden}.panel::after,.card::after,.widget::after{content:"";position:absolute;inset:0 0 auto;height:1px;background:linear-gradient(90deg,transparent,rgba(123,243,197,.26),transparent);pointer-events:none}
.stats{align-items:stretch!important}.stats .card,.kpi,.metric-card{min-height:122px!important;display:flex!important;flex-direction:column!important;justify-content:space-between!important;transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease!important}.stats .card:hover,.kpi:hover,.metric-card:hover{transform:translateY(-3px)!important;border-color:var(--hw-line-strong)!important;box-shadow:0 26px 68px rgba(0,0,0,.29)!important}.stats .card:nth-child(2n),.kpi:nth-child(2n){background:linear-gradient(180deg,rgba(19,42,34,.96),rgba(8,22,18,.985))!important}
.stats .card strong,.kpi strong,.metric-card strong{font-variant-numeric:tabular-nums!important;letter-spacing:-.045em!important}.stats .card small,.kpi small,.metric-card small{text-transform:uppercase!important;letter-spacing:.07em!important;font-size:.72em!important;color:var(--hw-muted)!important}
button,.action,[role="button"]{transition:transform .16s ease,box-shadow .16s ease,filter .16s ease,border-color .16s ease!important}button:hover,.action:hover,[role="button"]:hover{transform:translateY(-1px)!important;filter:brightness(1.035)!important}button:active,.action:active,[role="button"]:active{transform:translateY(0)!important}button:disabled{transform:none!important;filter:none!important;opacity:.5!important}
button.action,.primary,.btn-primary{background:linear-gradient(135deg,var(--hw-green),var(--hw-green2))!important;color:#021109!important;box-shadow:0 14px 36px rgba(43,227,161,.20)!important}button.action:hover,.primary:hover,.btn-primary:hover{box-shadow:0 18px 42px rgba(43,227,161,.27)!important}
.mini,.secondary,.btn-secondary{border-color:rgba(255,255,255,.10)!important;background:rgba(255,255,255,.025)!important}.mini:hover,.secondary:hover,.btn-secondary:hover{border-color:rgba(111,238,190,.22)!important;background:rgba(43,227,161,.055)!important}
input,select,textarea{background:rgba(4,16,11,.94)!important;border-color:rgba(255,255,255,.11)!important;color:var(--hw-text)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.022)!important;transition:border-color .16s ease,box-shadow .16s ease,background .16s ease!important}input:hover,select:hover,textarea:hover{border-color:rgba(255,255,255,.17)!important}input:focus,select:focus,textarea:focus{background:rgba(5,20,14,.97)!important;border-color:rgba(43,227,161,.66)!important;box-shadow:0 0 0 3px rgba(43,227,161,.10),inset 0 1px 0 rgba(255,255,255,.02)!important}
.tablewrap{background:rgba(2,11,7,.32)!important;border-color:rgba(255,255,255,.065)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.015)!important}.table thead,.table th,thead th{background:rgba(255,255,255,.028)!important;letter-spacing:.075em!important}.table tbody tr,tbody tr{transition:background .14s ease!important}.table tbody tr:hover,tbody tr:hover{background:rgba(43,227,161,.045)!important}.table td,.table th{border-color:rgba(255,255,255,.055)!important}
.badge,[class*="badge"]{backdrop-filter:blur(10px)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.035)!important}.empty{min-height:96px!important;display:flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;border:1px dashed rgba(111,238,190,.18)!important;border-radius:16px!important;background:linear-gradient(135deg,rgba(43,227,161,.03),rgba(232,201,111,.022))!important;color:var(--hw-muted)!important}.empty::before{content:"✦";margin-right:9px;color:var(--hw-green)!important;opacity:.85}
.chart,.bars{border-radius:18px!important;background:linear-gradient(180deg,rgba(255,255,255,.018),transparent)!important;padding-inline:14px!important}.bar{box-shadow:0 14px 36px rgba(43,227,161,.12)!important;transition:filter .16s ease,transform .16s ease!important}.bar:hover{filter:brightness(1.12)!important;transform:translateY(-2px)!important}
.activity>div,.dueItem{transition:transform .16s ease,border-color .16s ease,background .16s ease!important}.activity>div:hover,.dueItem:hover{transform:translateX(3px)!important;border-color:var(--hw-line-strong)!important;background:rgba(43,227,161,.03)!important}
.quick{gap:9px!important}.quick button{background:linear-gradient(180deg,rgba(43,227,161,.085),rgba(43,227,161,.035))!important;border-color:var(--hw-line)!important}.quick button:hover{border-color:var(--hw-line-strong)!important;box-shadow:0 14px 32px rgba(0,0,0,.19)!important}
.toast,[role="status"]{backdrop-filter:blur(16px)!important}.sideFoot{background:linear-gradient(180deg,rgba(43,227,161,.06),rgba(43,227,161,.025))!important;border-color:rgba(111,238,190,.16)!important}
::selection{background:rgba(43,227,161,.28)!important;color:#fff!important}:focus-visible{outline:3px solid rgba(123,243,197,.86)!important;outline-offset:3px!important}
@media(min-width:1180px){.main,main,.content,.page{max-width:1480px!important}.grid.three{gap:16px!important}.stats{gap:14px!important}}
@media(max-width:800px){body::before{display:none}.main,main,.content,.page{padding-left:12px!important;padding-right:12px!important}header,.header,.hero,.top,.page-header{border-radius:18px!important}.stats{gap:9px!important}.stats .card,.kpi,.metric-card{min-height:102px!important}.tablewrap{border-radius:12px!important}nav,.nav{scroll-snap-type:x proximity!important;-webkit-overflow-scrolling:touch!important}nav>* ,.nav>*{scroll-snap-align:start!important}.panel,.card,.widget{border-radius:16px!important}button,input,select,textarea{min-height:46px!important}}
@media(max-width:520px){.stats{grid-template-columns:1fr 1fr!important}.stats .card strong,.kpi strong,.metric-card strong{font-size:1.7rem!important}.quick{display:grid!important;grid-template-columns:1fr 1fr!important}.quick button{width:100%!important}.tablewrap{margin-inline:-2px!important}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto!important}*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
</style>`

  const script = `<script data-hegeva-hardcore="v5">(()=>{document.documentElement.classList.add('hegeva-hardcore-v5');const enhance=()=>{document.querySelectorAll('button').forEach(b=>{if(!b.hasAttribute('type')&&!b.closest('form'))b.setAttribute('type','button')});document.querySelectorAll('table').forEach(t=>{const p=t.parentElement;if(p&&!p.classList.contains('tablewrap')){const w=document.createElement('div');w.className='tablewrap';p.insertBefore(w,t);w.appendChild(t)}});document.querySelectorAll('input,select,textarea').forEach((el,i)=>{if(!el.getAttribute('aria-label')&&!el.getAttribute('aria-labelledby'))el.setAttribute('aria-label',el.getAttribute('placeholder')||el.getAttribute('name')||('Field '+(i+1)))});document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{const id=a.getAttribute('href')?.slice(1);const target=id&&document.getElementById(id);if(target)target.scrollIntoView({behavior:'smooth',block:'start'})}))};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance,{once:true});else enhance()})();</script>`

  let next = html
  next = next.replace(/<style data-hegeva-hardcore="v4">[\s\S]*?<\/style>/i, "")
  next = next.replace(/<script data-hegeva-hardcore="v4">[\s\S]*?<\/script>/i, "")
  next = /<\/head>/i.test(next) ? next.replace(/<\/head>/i, `${style}\n</head>`) : `${style}\n${next}`
  next = /<\/body>/i.test(next) ? next.replace(/<\/body>/i, `${script}\n</body>`) : `${next}\n${script}`
  return next
}
