"use client"

import Link from "next/link"
import { ArrowLeft, ArrowRight, Braces, CheckCircle2, FlaskConical, Layers3, Palette, ShieldCheck } from "lucide-react"
import { AppShell } from "@/components/app-shell"
import { SafeX30Renderer } from "@/components/x30/safe-renderer"
import type { X30RendererLabels } from "@/components/x30/safe-renderer"
import { pawflowX30Fixture } from "@/lib/x30/fixtures"
import { deriveWorkspaceVisualDirection } from "@/lib/x30/domain-visual-intelligence"
import { useWorkspaceData } from "@/lib/use-workspace-data"
import { useSession } from "@/lib/auth-client"
import { useI18n } from "@/lib/i18n/provider"
import { useState } from "react"

type Row = { id?: string; name?: string; title?: string; due?: string; done?: boolean }

const copy = {
 en:{cloud:"Authenticated workspace",local:"Local workspace · not cloud-synced",empty:"No workspace data available",demo:"Show PawFlow demo preview",hideDemo:"Hide demo preview",demoLabel:"User-selected demo preview",demoDirection:"Pet grooming · warm booking-led direction",genericAvatar:"Demo profile",back:"App Studio",runtime:"HEGEVA / NEXT GENERATION RUNTIME",alpha:"Alpha",eyebrow:"STRUCTURED. SAFE. DOMAIN-AWARE.",intro:"A deterministic proof that HEGEVA turns bounded workspace summaries into a distinctive interface without executing generated code.",pipeline:"X30 rendering architecture",steps:[["Structured spec","Version 0.1"],["Domain direction","Layout + visual rhythm"],["Component registry","Allowlisted components"],["Safe renderer","No generated code"],["Visual result","Quality checks"]],preview:"Workspace-aware structured preview",previewDescription:"A read-only summary from aggregate records saved in this workspace.",customers:"Customers",documents:"Documents",expenses:"Expenses",invoices:"Invoices & quotes",records:"Saved workspace records",schedule:"Schedule",openPlanner:"Open planner work",plannerItem:"Open planner item",noValue:"—",readOnly:"Read-only preview",structured:"X30 structured preview",rejected:"Preview rejected."},
 hu:{cloud:"Hitelesített munkaterület",local:"Helyi munkaterület · nincs felhőszinkron",empty:"Nincs elérhető munkaterületi adat",demo:"PawFlow bemutató megjelenítése",hideDemo:"Bemutató elrejtése",demoLabel:"Felhasználó által kiválasztott bemutató",demoDirection:"Kisállatkozmetika · meleg, foglalásközpontú irány",genericAvatar:"Bemutatóprofil",back:"App Stúdió",runtime:"HEGEVA / KÖVETKEZŐ GENERÁCIÓS RENDSZER",alpha:"Alfa",eyebrow:"STRUKTURÁLT. BIZTONSÁGOS. DOMÉN-TUDATOS.",intro:"Determinista bizonyíték arra, hogy a HEGEVA összesített munkaterületi adatokból megkülönböztethető felületet készít generált kód futtatása nélkül.",pipeline:"X30 renderelési architektúra",steps:[["Strukturált séma","0.1-es verzió"],["Doménirány","Elrendezés és vizuális ritmus"],["Komponens-regiszter","Engedélyezett komponensek"],["Biztonságos renderelő","Nincs generált kód"],["Vizuális eredmény","Minőség-ellenőrzések"]],preview:"Munkaterület-tudatos strukturált előnézet",previewDescription:"Csak olvasható összegzés a munkaterület összesített adataiból.",customers:"Ügyfelek",documents:"Dokumentumok",expenses:"Kiadások",invoices:"Számlák és árajánlatok",records:"Mentett munkaterületi rekordok",schedule:"Ütemezés",openPlanner:"Nyitott tervezési feladatok",plannerItem:"Nyitott tervezési elem",noValue:"—",readOnly:"Csak olvasható előnézet",structured:"X30 strukturált előnézet",rejected:"Az előnézet elutasítva."},
 de:{cloud:"Authentifizierter Workspace",local:"Lokaler Workspace · nicht cloud-synchronisiert",empty:"Keine Workspace-Daten verfügbar",demo:"PawFlow-Demo anzeigen",hideDemo:"Demo ausblenden",demoLabel:"Vom Benutzer ausgewählte Demo",demoDirection:"Tierpflege · warme, buchungsorientierte Richtung",back:"App Studio",runtime:"HEGEVA / NÄCHSTE GENERATION",alpha:"Alpha",eyebrow:"STRUKTURIERT. SICHER. DOMÄNENBEWUSST.",intro:"Ein deterministischer Nachweis, dass HEGEVA aus begrenzten Workspace-Zusammenfassungen eine eigene Oberfläche ohne ausgeführten Code erstellt.",pipeline:"X30-Rendering-Architektur",steps:[["Strukturierte Spezifikation","Version 0.1"],["Domänenrichtung","Layout und visueller Rhythmus"],["Komponentenregister","Erlaubte Komponenten"],["Sicherer Renderer","Kein generierter Code"],["Visuelles Ergebnis","Qualitätsprüfungen"]],preview:"Workspace-bewusste strukturierte Vorschau",previewDescription:"Eine schreibgeschützte Zusammenfassung aggregierter Workspace-Daten.",customers:"Kunden",documents:"Dokumente",expenses:"Ausgaben",invoices:"Rechnungen und Angebote",records:"Gespeicherte Workspace-Datensätze",schedule:"Planung",openPlanner:"Offene Planungsaufgaben",plannerItem:"Offenes Planungselement",noValue:"—",readOnly:"Schreibgeschützte Vorschau",structured:"Strukturierte X30-Vorschau",rejected:"Vorschau abgelehnt."},
 fr:{cloud:"Espace authentifié",local:"Espace local · non synchronisé dans le cloud",empty:"Aucune donnée d’espace disponible",demo:"Afficher la démo PawFlow",hideDemo:"Masquer la démo",demoLabel:"Démo sélectionnée par l’utilisateur",demoDirection:"Toilettage animalier · direction chaleureuse axée sur la réservation",back:"App Studio",runtime:"HEGEVA / RUNTIME NOUVELLE GÉNÉRATION",alpha:"Alpha",eyebrow:"STRUCTURÉ. SÛR. ORIENTÉ DOMAINE.",intro:"Une preuve déterministe que HEGEVA transforme des résumés agrégés en interface distinctive sans exécuter de code généré.",pipeline:"Architecture de rendu X30",steps:[["Spécification structurée","Version 0.1"],["Direction de domaine","Mise en page et rythme visuel"],["Registre de composants","Composants autorisés"],["Rendu sécurisé","Aucun code généré"],["Résultat visuel","Contrôles qualité"]],preview:"Aperçu structuré lié à l’espace",previewDescription:"Un résumé en lecture seule des données agrégées de cet espace.",customers:"Clients",documents:"Documents",expenses:"Dépenses",invoices:"Factures et devis",records:"Enregistrements de l’espace",schedule:"Planning",openPlanner:"Tâches de planning ouvertes",plannerItem:"Élément de planning ouvert",noValue:"—",readOnly:"Aperçu en lecture seule",structured:"Aperçu structuré X30",rejected:"Aperçu rejeté."},
 es:{cloud:"Espacio autenticado",local:"Espacio local · no sincronizado en la nube",empty:"No hay datos del espacio disponibles",demo:"Mostrar demo de PawFlow",hideDemo:"Ocultar demo",demoLabel:"Demo seleccionada por el usuario",demoDirection:"Peluquería canina · dirección cálida centrada en reservas",back:"App Studio",runtime:"HEGEVA / RUNTIME DE NUEVA GENERACIÓN",alpha:"Alfa",eyebrow:"ESTRUCTURADO. SEGURO. CONSCIENTE DEL DOMINIO.",intro:"Una prueba determinista de que HEGEVA convierte resúmenes agregados en una interfaz propia sin ejecutar código generado.",pipeline:"Arquitectura de renderizado X30",steps:[["Especificación estructurada","Versión 0.1"],["Dirección de dominio","Diseño y ritmo visual"],["Registro de componentes","Componentes permitidos"],["Renderizador seguro","Sin código generado"],["Resultado visual","Controles de calidad"]],preview:"Vista previa estructurada del espacio",previewDescription:"Un resumen de solo lectura de los datos agregados de este espacio.",customers:"Clientes",documents:"Documentos",expenses:"Gastos",invoices:"Facturas y presupuestos",records:"Registros guardados del espacio",schedule:"Planificación",openPlanner:"Tareas de planificación abiertas",plannerItem:"Elemento de planificación abierto",noValue:"—",readOnly:"Vista previa de solo lectura",structured:"Vista previa estructurada X30",rejected:"Vista previa rechazada."},
} as const

type X30Copy = (typeof copy)[keyof typeof copy]

function workspaceSpec(customers: Row[], documents: Row[], expenses: Row[], invoices: Row[], planner: Row[], labels: X30Copy) {
 const open = planner.filter((item) => !item.done)
 const direction = deriveWorkspaceVisualDirection({ customerCount:customers.length, documentCount:documents.length, expenseCount:expenses.length, invoiceCount:invoices.length, plannerCount:planner.length })
 return { version:"0.1" as const, id:"workspace-overview", name:"HEGEVA Workspace", direction, nodes:[
  {id:"welcome",type:"hero" as const,props:{eyebrow:labels.cloud,title:labels.preview,description:labels.previewDescription}},
  {id:"customers",type:"metric" as const,props:{label:labels.customers,value:String(customers.length),detail:labels.records}},
  {id:"documents",type:"metric" as const,props:{label:labels.documents,value:String(documents.length),detail:labels.records}},
  {id:"expenses",type:"metric" as const,props:{label:labels.expenses,value:String(expenses.length),detail:labels.records}},
  {id:"invoices",type:"metric" as const,props:{label:labels.invoices,value:String(invoices.length),detail:labels.records}},
  {id:"planner",type:"schedule" as const,props:{title:labels.openPlanner,items:open.slice(0,8).map((item,index)=>({id:`planner-item-${index}`,time:labels.noValue,title:labels.plannerItem,detail:"",value:""}))}},
 ]}
}

export default function X30AlphaPage(){
 const {locale}=useI18n(); const c=copy[locale]; const {data:session,isPending}=useSession(); const [showDemo,setShowDemo]=useState(false)
 const {items:customers,cloudEnabled:customerCloud}=useWorkspaceData<Row>("customers")
 const {items:documents}=useWorkspaceData<Row>("documents")
 const {items:expenses}=useWorkspaceData<Row>("expenses")
 const {items:invoices}=useWorkspaceData<Row>("invoice_documents")
 const {items:planner}=useWorkspaceData<Row>("planner")
 const cloud=Boolean(session?.user) && customerCloud
 const hasData=customers.length+documents.length+expenses.length+invoices.length+planner.length>0
 const spec=workspaceSpec(customers,documents,expenses,invoices,planner,c)
 const genericAvatar = ({en:"Demo profile",hu:"Bemutatóprofil",de:"Demo-Profil",fr:"Profil de démo",es:"Perfil de demo"} as const)[locale]
 const rendererLabels: X30RendererLabels = { schedule:c.schedule, readOnlyPreview:c.readOnly, structuredPreview:c.structured, previewRejected:c.rejected, genericPlannerItem:c.plannerItem, noValue:c.noValue, genericAvatar }
 return <AppShell><main className="mx-auto max-w-[1500px] px-4 py-8 sm:px-6 lg:px-8">
  <section className="x30-crown"><div><Link href="/app-studio" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/><span>{c.back}</span></Link><p>{c.runtime}</p><h1>X30 <span>{c.alpha}</span></h1><b>{c.eyebrow}</b><small>{c.intro}</small></div><div className="x30-core-object" aria-hidden><i/><i/><i/><Layers3/></div></section>
  <section className="x30-pipeline" aria-label={c.pipeline}>{c.steps.map(([title,detail],index)=>{const Icon=[Braces,Palette,Layers3,ShieldCheck,CheckCircle2][index]; return <div key={title}><span>{String(index+1).padStart(2,"0")}</span><Icon aria-hidden/><b>{title}</b><small>{detail}</small>{index<4&&<ArrowRight aria-hidden/>}</div>})}</section>
  <section className="mt-8"><div className="mb-3 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">{showDemo ? c.demoLabel : cloud ? c.cloud : c.local}</p><h2 className="mt-1 text-lg font-semibold">{showDemo ? c.demoDirection : c.preview}</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">{showDemo ? c.demoLabel : c.previewDescription}</p></div><div className="flex items-center gap-2"><span className="hidden items-center gap-2 rounded-full border border-violet/25 bg-violet/10 px-3 py-1.5 text-xs text-violet sm:inline-flex"><FlaskConical className="size-3.5"/>{showDemo ? c.demoLabel : c.readOnly}</span><button type="button" onClick={()=>setShowDemo((value)=>!value)} className="rounded-lg border border-border px-3 py-2 text-xs font-semibold">{showDemo ? c.hideDemo : c.demo}</button></div></div>{!isPending && !showDemo && !hasData ? <div role="status" className="rounded-2xl border border-border bg-background/40 p-6 text-sm text-muted-foreground">{c.empty}</div> : <SafeX30Renderer spec={showDemo ? pawflowX30Fixture : spec} labels={rendererLabels}/>}</section>
 </main></AppShell>
}
