"use client"

import Link from "next/link"
import { ArrowLeft, Braces, FlaskConical, Layers3, Palette, ShieldCheck } from "lucide-react"
import { AppShell } from "@/components/app-shell"
import { SafeX30Renderer } from "@/components/x30/safe-renderer"
import { useI18n } from "@/lib/i18n/provider"
import { pawflowX30Fixture } from "@/lib/x30/fixtures"

const copy = {
  en:{back:"App Studio",eyebrow:"HEGEVA / INTERNAL PREVIEW",title:"X30 structured preview",sub:"A deterministic demonstration of a versioned specification rendered through allowlisted components. It does not execute generated code.",schema:"Structured specification",direction:"Domain direction",registry:"Allowlisted components",renderer:"Validated renderer",fixture:"Deterministic fixture",fixtureTitle:"Pet grooming · booking-led direction",internal:"Internal preview",preview:"X30 structured preview",rejected:"Preview rejected.",schedule:"Schedule",previewAction:"Preview action; not interactive"},
  hu:{back:"App Stúdió",eyebrow:"HEGEVA / BELSŐ ELŐNÉZET",title:"X30 strukturált előnézet",sub:"Verziózott specifikáció determinisztikus bemutatója engedélyezett komponensekkel. Nem futtat generált kódot.",schema:"Strukturált specifikáció",direction:"Területi irány",registry:"Engedélyezett komponensek",renderer:"Ellenőrzött renderelő",fixture:"Determinisztikus minta",fixtureTitle:"Kisállatkozmetika · foglalásközpontú irány",internal:"Belső előnézet",preview:"X30 strukturált előnézet",rejected:"Az előnézet elutasítva.",schedule:"Időbeosztás",previewAction:"Előnézeti művelet; nem interaktív"},
  de:{back:"App Studio",eyebrow:"HEGEVA / INTERNE VORSCHAU",title:"Strukturierte X30-Vorschau",sub:"Eine deterministische Demonstration einer versionierten Spezifikation mit zugelassenen Komponenten. Es wird kein generierter Code ausgeführt.",schema:"Strukturierte Spezifikation",direction:"Domänenrichtung",registry:"Zugelassene Komponenten",renderer:"Validierter Renderer",fixture:"Deterministische Testdaten",fixtureTitle:"Tierpflege · buchungsorientierte Ausrichtung",internal:"Interne Vorschau",preview:"Strukturierte X30-Vorschau",rejected:"Vorschau abgelehnt.",schedule:"Zeitplan",previewAction:"Vorschauaktion; nicht interaktiv"},
  fr:{back:"App Studio",eyebrow:"HEGEVA / APERÇU INTERNE",title:"Aperçu structuré X30",sub:"Une démonstration déterministe d’une spécification versionnée rendue avec des composants autorisés. Aucun code généré n’est exécuté.",schema:"Spécification structurée",direction:"Direction métier",registry:"Composants autorisés",renderer:"Rendu validé",fixture:"Jeu de données déterministe",fixtureTitle:"Toilettage · approche centrée sur les réservations",internal:"Aperçu interne",preview:"Aperçu structuré X30",rejected:"Aperçu refusé.",schedule:"Planning",previewAction:"Action d’aperçu non interactive"},
  es:{back:"App Studio",eyebrow:"HEGEVA / VISTA INTERNA",title:"Vista estructurada X30",sub:"Una demostración determinista de una especificación versionada mediante componentes permitidos. No ejecuta código generado.",schema:"Especificación estructurada",direction:"Dirección de dominio",registry:"Componentes permitidos",renderer:"Renderizador validado",fixture:"Datos deterministas",fixtureTitle:"Peluquería de mascotas · enfoque de reservas",internal:"Vista interna",preview:"Vista estructurada X30",rejected:"Vista rechazada.",schedule:"Agenda",previewAction:"Acción de vista previa; no interactiva"},
} as const

export default function X30AlphaPage() {
  const { locale } = useI18n()
  const text = copy[locale]
  const steps = [[Braces,text.schema,"0.1"],[Palette,text.direction,pawflowX30Fixture.direction.industry],[Layers3,text.registry,String(pawflowX30Fixture.nodes.length)],[ShieldCheck,text.renderer,text.internal]] as const
  return <AppShell><main id="main-content" className="mx-auto w-full max-w-[1500px] px-4 py-8 sm:px-6 lg:px-8"><header className="rounded-[2rem] border border-cyan/20 bg-gradient-to-br from-cyan/8 via-background/70 to-violet/10 p-6 sm:p-8"><Link href="/app-studio" className="inline-flex min-h-11 items-center gap-2 text-sm text-muted-foreground transition hover:text-foreground"><ArrowLeft className="size-4" aria-hidden />{text.back}</Link><p className="ve-eyebrow mt-8">{text.eyebrow}</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-[-.045em] sm:text-5xl">{text.title}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground sm:text-base">{text.sub}</p></header><section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label={text.title}>{steps.map(([Icon,title,detail],index)=><article key={title} className="rounded-2xl border border-white/10 bg-background/45 p-4"><span className="text-xs text-muted-foreground">{String(index+1).padStart(2,"0")}</span><Icon className="mt-5 size-5 text-cyan" aria-hidden /><h2 className="mt-3 text-sm font-semibold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{detail}</p></article>)}</section><section className="mt-8"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="ve-eyebrow">{text.fixture}</p><h2 className="mt-1 text-lg font-semibold">{text.fixtureTitle}</h2></div><span className="inline-flex items-center gap-2 rounded-full border border-violet/25 bg-violet/10 px-3 py-2 text-xs text-violet"><FlaskConical className="size-3.5" aria-hidden />{text.internal}</span></div><SafeX30Renderer spec={pawflowX30Fixture} copy={{preview:text.preview,rejected:text.rejected,schedule:text.schedule,previewAction:text.previewAction}} /></section></main></AppShell>
}
