"use client"

import Link from "next/link"
import { ArrowLeft, ArrowRight, Braces, CheckCircle2, FlaskConical, Layers3, Palette, ShieldCheck } from "lucide-react"
import { AppShell } from "@/components/app-shell"
import { SafeX30Renderer } from "@/components/x30/safe-renderer"
import type { X30RendererLabels } from "@/components/x30/safe-renderer"
import { pawflowX30Fixture } from "@/lib/x30/fixtures"
import { deriveWorkspaceVisualDirection } from "@/lib/x30/domain-visual-intelligence"
import { useWorkspaceData } from "@/lib/use-workspace-data"
import { useSession } from "@/lib/auth-client"
import { useI18n } from "@/lib/i18n/provider"
import { useState } from "react"
import { DEFAULT_X30_BRIEF, X30_BRIEF_CAPABILITIES, X30_BRIEF_DOMAINS, X30_BRIEF_SENSITIVITIES, X30_BRIEF_VISUAL_DIRECTIONS, mapX30BriefToSpec, validateX30Brief, type X30Brief } from "@/lib/x30/structured-brief"
import { buildX30GenerationRequest } from "@/lib/x30/x30-ai"
import { validateX30GenerationResult } from "@/lib/x30/generation-contract"
import type { X30AppSpec } from "@/lib/x30/schema"

type Row = { id?: string; name?: string; title?: string; due?: string; done?: boolean }

const copy = {
 en:{cloud:"Authenticated workspace",local:"Local workspace · not cloud-synced",empty:"No workspace data available",demo:"Show PawFlow demo preview",hideDemo:"Hide demo preview",demoLabel:"User-selected demo preview",demoDirection:"Pet grooming · warm booking-led direction",genericAvatar:"Demo profile",back:"App Studio",runtime:"HEGEVA / NEXT GENERATION RUNTIME",alpha:"Alpha",eyebrow:"STRUCTURED. SAFE. DOMAIN-AWARE.",intro:"A deterministic proof that HEGEVA turns bounded workspace summaries into a distinctive interface without executing generated code.",pipeline:"X30 rendering architecture",steps:[["Structured spec","Version 0.1"],["Domain direction","Layout + visual rhythm"],["Component registry","Allowlisted components"],["Safe renderer","No generated code"],["Visual result","Quality checks"]],preview:"Workspace-aware structured preview",previewDescription:"A read-only summary from aggregate records saved in this workspace.",customers:"Customers",documents:"Documents",expenses:"Expenses",invoices:"Invoices & quotes",records:"Saved workspace records",schedule:"Schedule",openPlanner:"Open planner work",plannerItem:"Open planner item",noValue:"—",readOnly:"Read-only preview",structured:"X30 structured preview",rejected:"Preview rejected.",generate:"Generate preview",generating:"Generating preview…",ready:"Planning context prepared · awaiting owner approval",approved:"Preview approval recorded locally.",authRequired:"Sign in to request a preview.",ownerOnly:"Preview generation is limited to the owner canary.",disabled:"X30 generation is currently unavailable.",quota:"X30 generation allowance reached.",conflict:"This preview request is already being processed.",timeout:"The preview request timed out.",unavailable:"The preview could not be generated."},
 hu:{cloud:"Hitelesített munkaterület",local:"Helyi munkaterület · nincs felhőszinkron",empty:"Nincs elérhető munkaterületi adat",demo:"PawFlow bemutató megjelenítése",hideDemo:"Bemutató elrejtése",demoLabel:"Felhasználó által kiválasztott bemutató",demoDirection:"Kisállatkozmetika · meleg, foglalásközpontú irány",genericAvatar:"Bemutatóprofil",back:"App Stúdió",runtime:"HEGEVA / KÖVETKEZŐ GENERÁCIÓS RENDSZER",alpha:"Alfa",eyebrow:"STRUKTURÁLT. BIZTONSÁGOS. DOMÉN-TUDATOS.",intro:"Determinista bizonyíték arra, hogy a HEGEVA összesített munkaterületi adatokból megkülönböztethető felületet készít generált kód futtatása nélkül.",pipeline:"X30 renderelési architektúra",steps:[["Strukturált séma","0.1-es verzió"],["Doménirány","Elrendezés és vizuális ritmus"],["Komponens-regiszter","Engedélyezett komponensek"],["Biztonságos renderelő","Nincs generált kód"],["Vizuális eredmény","Minőség-ellenőrzések"]],preview:"Munkaterület-tudatos strukturált előnézet",previewDescription:"Csak olvasható összegzés a munkaterület összesített adataiból.",customers:"Ügyfelek",documents:"Dokumentumok",expenses:"Kiadások",invoices:"Számlák és árajánlatok",records:"Mentett munkaterületi rekordok",schedule:"Ütemezés",openPlanner:"Nyitott tervezési feladatok",plannerItem:"Nyitott tervezési elem",noValue:"—",readOnly:"Csak olvasható előnézet",structured:"X30 strukturált előnézet",rejected:"Az előnézet elutasítva.",generate:"Előnézet generálása",generating:"Előnézet generálása…",ready:"A tervezési kontextus elkészült · tulajdonosi jóváhagyásra vár",approved:"Az előnézeti jóváhagyás helyben rögzítve.",authRequired:"Jelentkezz be előnézet kéréséhez.",ownerOnly:"Az előnézet-generálás csak a tulajdonosi canary számára érhető el.",disabled:"Az X30-generálás jelenleg nem érhető el.",quota:"Az X30-generálási keret elfogyott.",conflict:"Ez az előnézeti kérés már feldolgozás alatt áll.",timeout:"Az előnézeti kérés időtúllépést ért el.",unavailable:"Az előnézet nem generálható."},
 de:{cloud:"Authentifizierter Workspace",local:"Lokaler Workspace · nicht cloud-synchronisiert",empty:"Keine Workspace-Daten verfügbar",demo:"PawFlow-Demo anzeigen",hideDemo:"Demo ausblenden",demoLabel:"Vom Benutzer ausgewählte Demo",demoDirection:"Tierpflege · warme, buchungsorientierte Richtung",back:"App Studio",runtime:"HEGEVA / NÄCHSTE GENERATION",alpha:"Alpha",eyebrow:"STRUKTURIERT. SICHER. DOMÄNENBEWUSST.",intro:"Ein deterministischer Nachweis, dass HEGEVA aus begrenzten Workspace-Zusammenfassungen eine eigene Oberfläche ohne ausgeführten Code erstellt.",pipeline:"X30-Rendering-Architektur",steps:[["Strukturierte Spezifikation","Version 0.1"],["Domänenrichtung","Layout und visueller Rhythmus"],["Komponentenregister","Erlaubte Komponenten"],["Sicherer Renderer","Kein generierter Code"],["Visuelles Ergebnis","Qualitätsprüfungen"]],preview:"Workspace-bewusste strukturierte Vorschau",previewDescription:"Eine schreibgeschützte Zusammenfassung aggregierter Workspace-Daten.",customers:"Kunden",documents:"Dokumente",expenses:"Ausgaben",invoices:"Rechnungen und Angebote",records:"Gespeicherte Workspace-Datensätze",schedule:"Planung",openPlanner:"Offene Planungsaufgaben",plannerItem:"Offenes Planungselement",noValue:"—",readOnly:"Schreibgeschützte Vorschau",structured:"Strukturierte X30-Vorschau",rejected:"Vorschau abgelehnt.",generate:"Vorschau generieren",generating:"Vorschau wird generiert…",ready:"Vorschau zur Prüfung bereit.",authRequired:"Melde dich an, um eine Vorschau anzufordern.",ownerOnly:"Die Vorschau-Generierung ist auf den Owner-Canary begrenzt.",disabled:"X30-Generierung ist derzeit nicht verfügbar.",quota:"Das X30-Generierungslimit ist erreicht.",conflict:"Diese Vorschauanfrage wird bereits verarbeitet.",timeout:"Die Vorschauanfrage ist abgelaufen.",unavailable:"Die Vorschau konnte nicht generiert werden."},
 fr:{cloud:"Espace authentifié",local:"Espace local · non synchronisé dans le cloud",empty:"Aucune donnée d’espace disponible",demo:"Afficher la démo PawFlow",hideDemo:"Masquer la démo",demoLabel:"Démo sélectionnée par l’utilisateur",demoDirection:"Toilettage animalier · direction chaleureuse axée sur la réservation",back:"App Studio",runtime:"HEGEVA / RUNTIME NOUVELLE GÉNÉRATION",alpha:"Alpha",eyebrow:"STRUCTURÉ. SÛR. ORIENTÉ DOMAINE.",intro:"Une preuve déterministe que HEGEVA transforme des résumés agrégés en interface distinctive sans exécuter de code généré.",pipeline:"Architecture de rendu X30",steps:[["Spécification structurée","Version 0.1"],["Direction de domaine","Mise en page et rythme visuel"],["Registre de composants","Composants autorisés"],["Rendu sécurisé","Aucun code généré"],["Résultat visuel","Contrôles qualité"]],preview:"Aperçu structuré lié à l’espace",previewDescription:"Un résumé en lecture seule des données agrégées de cet espace.",customers:"Clients",documents:"Documents",expenses:"Dépenses",invoices:"Factures et devis",records:"Enregistrements de l’espace",schedule:"Planning",openPlanner:"Tâches de planning ouvertes",plannerItem:"Élément de planning ouvert",noValue:"—",readOnly:"Aperçu en lecture seule",structured:"Aperçu structuré X30",rejected:"Aperçu rejeté.",generate:"Générer un aperçu",generating:"Génération de l’aperçu…",ready:"Aperçu prêt à être relu.",authRequired:"Connectez-vous pour demander un aperçu.",ownerOnly:"La génération d’aperçu est limitée au canary propriétaire.",disabled:"La génération X30 n’est pas disponible actuellement.",quota:"La limite de génération X30 est atteinte.",conflict:"Cette demande d’aperçu est déjà en cours.",timeout:"La demande d’aperçu a expiré.",unavailable:"L’aperçu n’a pas pu être généré."},
 es:{cloud:"Espacio autenticado",local:"Espacio local · no sincronizado en la nube",empty:"No hay datos del espacio disponibles",demo:"Mostrar demo de PawFlow",hideDemo:"Ocultar demo",demoLabel:"Demo seleccionada por el usuario",demoDirection:"Peluquería canina · dirección cálida centrada en reservas",back:"App Studio",runtime:"HEGEVA / RUNTIME DE NUEVA GENERACIÓN",alpha:"Alfa",eyebrow:"ESTRUCTURADO. SEGURO. CONSCIENTE DEL DOMINIO.",intro:"Una prueba determinista de que HEGEVA convierte resúmenes agregados en una interfaz propia sin ejecutar código generado.",pipeline:"Arquitectura de renderizado X30",steps:[["Especificación estructurada","Versión 0.1"],["Dirección de dominio","Diseño y ritmo visual"],["Registro de componentes","Componentes permitidos"],["Renderizador seguro","Sin código generado"],["Resultado visual","Controles de calidad"]],preview:"Vista previa estructurada del espacio",previewDescription:"Un resumen de solo lectura de los datos agregados de este espacio.",customers:"Clientes",documents:"Documentos",expenses:"Gastos",invoices:"Facturas y presupuestos",records:"Registros guardados del espacio",schedule:"Planificación",openPlanner:"Tareas de planificación abiertas",plannerItem:"Elemento de planificación abierto",noValue:"—",readOnly:"Vista previa de solo lectura",structured:"Vista previa estructurada X30",rejected:"Vista previa rechazada.",generate:"Generar vista previa",generating:"Generando vista previa…",ready:"Vista previa lista para revisión.",authRequired:"Inicia sesión para solicitar una vista previa.",ownerOnly:"La generación de vista previa está limitada al canary propietario.",disabled:"La generación X30 no está disponible actualmente.",quota:"Se alcanzó el límite de generación X30.",conflict:"Esta solicitud de vista previa ya está en proceso.",timeout:"La solicitud de vista previa agotó el tiempo.",unavailable:"No se pudo generar la vista previa."},
} as const

type X30Copy = (typeof copy)[keyof typeof copy]

const briefUi = {
 en:{title:"Structured brief",description:"Shape a bounded preview brief before anything is generated.",project:"Project name",users:"Target users",goal:"Primary goal",domain:"Domain",pages:"Required pages",addPage:"Add page",capabilities:"Capabilities",visual:"Visual direction",sensitivity:"Data sensitivity",deployment:"Deployment intent",review:"Review brief",edit:"Edit brief",approve:"Approve preview",draft:"Return to draft",previewOnly:"Preview only",notStarted:"Execution not started",ready:"Planning context prepared · awaiting owner approval",invalid:"Complete the required fields to review this brief.",localOnly:"This brief stays in browser memory and is not cloud-synced."},
 hu:{title:"Strukturált brief",description:"Készíts korlátozott előnézeti briefet, mielőtt bármi generálódna.",project:"Projekt neve",users:"Célfelhasználók",goal:"Elsődleges cél",domain:"Domén",pages:"Szükséges oldalak",addPage:"Oldal hozzáadása",capabilities:"Képességek",visual:"Vizuális irány",sensitivity:"Adatérzékenység",deployment:"Telepítési szándék",review:"Brief áttekintése",edit:"Brief szerkesztése",approve:"Előnézet jóváhagyása",draft:"Vissza piszkozatba",previewOnly:"Csak előnézet",notStarted:"A végrehajtás nem indult el",ready:"A tervezési kontextus elkészült · tulajdonosi jóváhagyásra vár",invalid:"Az áttekintéshez töltsd ki a kötelező mezőket.",localOnly:"Ez a brief csak a böngésző memóriájában marad, nincs felhőszinkron."},
 de:{title:"Strukturiertes Briefing",description:"Erstelle ein begrenztes Vorschau-Briefing, bevor etwas generiert wird.",project:"Projektname",users:"Zielgruppen",goal:"Hauptziel",domain:"Domäne",pages:"Erforderliche Seiten",addPage:"Seite hinzufügen",capabilities:"Funktionen",visual:"Visuelle Richtung",sensitivity:"Datensensibilität",deployment:"Bereitstellungsabsicht",review:"Briefing prüfen",edit:"Briefing bearbeiten",approve:"Vorschau genehmigen",draft:"Als Entwurf zurück",previewOnly:"Nur Vorschau",notStarted:"Ausführung nicht gestartet",ready:"Planungskontext vorbereitet · wartet auf Eigentümerfreigabe",invalid:"Fülle die Pflichtfelder aus, um dieses Briefing zu prüfen.",localOnly:"Dieses Briefing bleibt im Browserspeicher und wird nicht synchronisiert."},
 fr:{title:"Brief structuré",description:"Préparez un brief de prévisualisation borné avant toute génération.",project:"Nom du projet",users:"Utilisateurs cibles",goal:"Objectif principal",domain:"Domaine",pages:"Pages requises",addPage:"Ajouter une page",capabilities:"Capacités",visual:"Direction visuelle",sensitivity:"Sensibilité des données",deployment:"Intention de déploiement",review:"Relire le brief",edit:"Modifier le brief",approve:"Approuver l’aperçu",draft:"Revenir au brouillon",previewOnly:"Aperçu uniquement",notStarted:"Exécution non démarrée",ready:"Contexte de planification préparé · en attente de l’approbation du propriétaire",invalid:"Complétez les champs requis pour relire ce brief.",localOnly:"Ce brief reste dans la mémoire du navigateur et n’est pas synchronisé."},
 es:{title:"Brief estructurado",description:"Define un brief acotado de vista previa antes de generar nada.",project:"Nombre del proyecto",users:"Usuarios objetivo",goal:"Objetivo principal",domain:"Dominio",pages:"Páginas necesarias",addPage:"Añadir página",capabilities:"Capacidades",visual:"Dirección visual",sensitivity:"Sensibilidad de datos",deployment:"Intención de despliegue",review:"Revisar brief",edit:"Editar brief",approve:"Aprobar vista previa",draft:"Volver al borrador",previewOnly:"Solo vista previa",notStarted:"Ejecución no iniciada",ready:"Contexto de planificación preparado · esperando aprobación del propietario",invalid:"Completa los campos obligatorios para revisar este brief.",localOnly:"Este brief permanece en la memoria del navegador y no se sincroniza."},
} as const

const tokenLabels = {
 en:{domains:{"professional-services":"Professional services",finance:"Finance",retail:"Retail",hospitality:"Hospitality",health:"Health",education:"Education",technology:"Technology",other:"Other"},visual:{professional:"Professional",ledger:"Ledger",hospitality:"Hospitality",studio:"Studio",editorial:"Editorial",technical:"Technical"},sensitivity:{public:"Public",internal:"Internal",confidential:"Confidential"},deployment:{"preview-only":"Preview only","future-review":"Future review"},capabilities:{records:"Records",search:"Search",filter:"Filter",create:"Create",edit:"Edit",delete:"Delete",dashboard:"Dashboard",schedule:"Schedule",responsive:"Responsive", "local-persistence":"Local persistence",reports:"Reports",messages:"Messages"}},
 hu:{domains:{"professional-services":"Szakmai szolgáltatások",finance:"Pénzügy",retail:"Kiskereskedelem",hospitality:"Vendéglátás",health:"Egészségügy",education:"Oktatás",technology:"Technológia",other:"Egyéb"},visual:{professional:"Szakmai",ledger:"Főkönyvi",hospitality:"Vendéglátó",studio:"Stúdió",editorial:"Szerkesztői",technical:"Technikai"},sensitivity:{public:"Nyilvános",internal:"Belső",confidential:"Bizalmas"},deployment:{"preview-only":"Csak előnézet","future-review":"Későbbi felülvizsgálat"},capabilities:{records:"Rekordok",search:"Keresés",filter:"Szűrés",create:"Létrehozás",edit:"Szerkesztés",delete:"Törlés",dashboard:"Irányítópult",schedule:"Ütemezés",responsive:"Reszponzív", "local-persistence":"Helyi mentés",reports:"Jelentések",messages:"Üzenetek"}},
 de:{domains:{"professional-services":"Professionelle Dienste",finance:"Finanzen",retail:"Einzelhandel",hospitality:"Gastgewerbe",health:"Gesundheit",education:"Bildung",technology:"Technologie",other:"Andere"},visual:{professional:"Professionell",ledger:"Ledger",hospitality:"Gastgewerbe",studio:"Studio",editorial:"Editorial",technical:"Technisch"},sensitivity:{public:"Öffentlich",internal:"Intern",confidential:"Vertraulich"},deployment:{"preview-only":"Nur Vorschau","future-review":"Spätere Prüfung"},capabilities:{records:"Datensätze",search:"Suche",filter:"Filter",create:"Erstellen",edit:"Bearbeiten",delete:"Löschen",dashboard:"Dashboard",schedule:"Planung",responsive:"Responsiv", "local-persistence":"Lokale Speicherung",reports:"Berichte",messages:"Nachrichten"}},
 fr:{domains:{"professional-services":"Services professionnels",finance:"Finance",retail:"Commerce",hospitality:"Hôtellerie",health:"Santé",education:"Éducation",technology:"Technologie",other:"Autre"},visual:{professional:"Professionnel",ledger:"Registre",hospitality:"Hôtellerie",studio:"Studio",editorial:"Éditorial",technical:"Technique"},sensitivity:{public:"Public",internal:"Interne",confidential:"Confidentiel"},deployment:{"preview-only":"Aperçu uniquement","future-review":"Révision ultérieure"},capabilities:{records:"Enregistrements",search:"Recherche",filter:"Filtre",create:"Créer",edit:"Modifier",delete:"Supprimer",dashboard:"Tableau de bord",schedule:"Planning",responsive:"Responsive", "local-persistence":"Stockage local",reports:"Rapports",messages:"Messages"}},
 es:{domains:{"professional-services":"Servicios profesionales",finance:"Finanzas",retail:"Comercio",hospitality:"Hostelería",health:"Salud",education:"Educación",technology:"Tecnología",other:"Otro"},visual:{professional:"Profesional",ledger:"Libro mayor",hospitality:"Hostelería",studio:"Estudio",editorial:"Editorial",technical:"Técnico"},sensitivity:{public:"Público",internal:"Interno",confidential:"Confidencial"},deployment:{"preview-only":"Solo vista previa","future-review":"Revisión futura"},capabilities:{records:"Registros",search:"Buscar",filter:"Filtrar",create:"Crear",edit:"Editar",delete:"Eliminar",dashboard:"Panel",schedule:"Planificación",responsive:"Adaptable", "local-persistence":"Almacenamiento local",reports:"Informes",messages:"Mensajes"}},
} as const

type BriefUiCopy = (typeof briefUi)[keyof typeof briefUi]
type BriefTokenLabels = (typeof tokenLabels)[keyof typeof tokenLabels]
type BriefEditorProps = { brief: X30Brief; briefState: X30Brief["reviewState"]; errors: string[]; copy: BriefUiCopy; labels: BriefTokenLabels; update: (key: keyof X30Brief, value: unknown) => void; review: () => void; approve: () => void; draft: () => void }

function BriefEditor({ brief, briefState, errors, copy: b, labels: t, update, review, approve, draft }: BriefEditorProps) {
  return <section className="mt-8 rounded-2xl border border-violet/20 bg-violet/5 p-5" aria-labelledby="x30-brief-title">
    <div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 id="x30-brief-title" className="text-lg font-semibold">{b.title}</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">{b.description}</p></div><span className="rounded-full border border-gold/30 px-3 py-1 text-xs text-gold">{b.previewOnly} · {b.notStarted}</span></div>
    {briefState !== "preview-only" ? <div className="grid min-w-0 gap-4 md:grid-cols-2">
      <label className="min-w-0 text-sm">{b.project}<input maxLength={80} value={brief.projectName} onChange={(e)=>update("projectName",e.target.value)} className="mt-1 w-full min-w-0 rounded-lg border border-border bg-background/50 px-3 py-2" /></label>
      <label className="min-w-0 text-sm">{b.users}<input maxLength={160} value={brief.targetUsers} onChange={(e)=>update("targetUsers",e.target.value)} className="mt-1 w-full min-w-0 rounded-lg border border-border bg-background/50 px-3 py-2" /></label>
      <label className="min-w-0 text-sm md:col-span-2">{b.goal}<input maxLength={180} value={brief.primaryGoal} onChange={(e)=>update("primaryGoal",e.target.value)} className="mt-1 w-full min-w-0 rounded-lg border border-border bg-background/50 px-3 py-2" /></label>
      <label className="min-w-0 text-sm">{b.domain}<select value={brief.domain} onChange={(e)=>update("domain",e.target.value)} className="mt-1 w-full min-w-0 rounded-lg border border-border bg-background/50 px-3 py-2">{X30_BRIEF_DOMAINS.map((item)=><option key={item} value={item}>{t.domains[item]}</option>)}</select></label>
      <label className="min-w-0 text-sm">{b.visual}<select value={brief.visualDirection} onChange={(e)=>update("visualDirection",e.target.value)} className="mt-1 w-full min-w-0 rounded-lg border border-border bg-background/50 px-3 py-2">{X30_BRIEF_VISUAL_DIRECTIONS.map((item)=><option key={item} value={item}>{t.visual[item]}</option>)}</select></label>
      <fieldset className="min-w-0 md:col-span-2"><legend className="text-sm font-semibold">{b.capabilities}</legend><div className="mt-2 grid min-w-0 grid-cols-2 gap-2 sm:grid-cols-3">{X30_BRIEF_CAPABILITIES.map((capability)=><label key={capability} className="flex min-w-0 items-center gap-2 text-xs"><input type="checkbox" checked={brief.requiredCapabilities.includes(capability)} onChange={(e)=>update("requiredCapabilities",e.target.checked?[...brief.requiredCapabilities,capability]:brief.requiredCapabilities.filter((item)=>item!==capability))}/><span className="break-words">{t.capabilities[capability]}</span></label>)}</div></fieldset>
      <div className="min-w-0 md:col-span-2"><div className="flex min-w-0 flex-wrap items-center justify-between gap-2"><label className="min-w-0 text-sm">{b.pages}</label>{(brief.requiredPages||[]).length<8&&<button type="button" onClick={()=>update("requiredPages",[...(brief.requiredPages||[]),""])} className="shrink-0 text-xs text-violet">{b.addPage}</button>}</div>{(brief.requiredPages||[]).map((page,index)=><input key={index} maxLength={48} value={page} onChange={(e)=>update("requiredPages",(brief.requiredPages||[]).map((item,i)=>i===index?e.target.value:item))} className="mt-2 block w-full min-w-0 rounded-lg border border-border bg-background/50 px-3 py-2" aria-label={`${b.pages} ${index+1}`}/>)}</div>
      <label className="min-w-0 text-sm">{b.sensitivity}<select value={brief.dataSensitivity} onChange={(e)=>update("dataSensitivity",e.target.value)} className="mt-1 w-full min-w-0 rounded-lg border border-border bg-background/50 px-3 py-2">{X30_BRIEF_SENSITIVITIES.map((item)=><option key={item} value={item}>{t.sensitivity[item]}</option>)}</select></label>
      <div className="flex flex-wrap items-end gap-2 md:col-span-2">{briefState==="ready-for-review"&&<p className="w-full text-sm text-emerald" role="status">{b.ready}</p>}<button type="button" onClick={review} className="rounded-lg border border-border px-3 py-2 text-xs font-semibold">{b.review}</button><button type="button" disabled={briefState!=="ready-for-review"} aria-disabled={briefState!=="ready-for-review"} onClick={approve} className="rounded-lg border border-emerald/40 px-3 py-2 text-xs font-semibold text-emerald disabled:cursor-not-allowed disabled:opacity-40">{b.approve}</button><button type="button" onClick={draft} className="rounded-lg border border-border px-3 py-2 text-xs font-semibold">{b.draft}</button></div>
    </div> : <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-emerald">{b.previewOnly}</p><button type="button" onClick={draft} className="rounded-lg border border-border px-3 py-2 text-xs font-semibold">{b.edit}</button></div>}
    {errors.length>0&&<p role="alert" className="mt-3 text-xs text-rose-300">{b.invalid}</p>}<p className="mt-3 text-xs text-muted-foreground">{b.localOnly}</p>
  </section>
}

function workspaceSpec(customers: Row[], documents: Row[], expenses: Row[], invoices: Row[], planner: Row[], labels: X30Copy) {
 const open = planner.filter((item) => !item.done)
 const direction = deriveWorkspaceVisualDirection({ customerCount:customers.length, documentCount:documents.length, expenseCount:expenses.length, invoiceCount:invoices.length, plannerCount:planner.length })
 return { version:"0.1" as const, id:"workspace-overview", name:"HEGEVA Workspace", direction, nodes:[
  {id:"welcome",type:"hero" as const,props:{eyebrow:labels.cloud,title:labels.preview,description:labels.previewDescription}},
  {id:"customers",type:"metric" as const,props:{label:labels.customers,value:String(customers.length),detail:labels.records}},
  {id:"documents",type:"metric" as const,props:{label:labels.documents,value:String(documents.length),detail:labels.records}},
  {id:"expenses",type:"metric" as const,props:{label:labels.expenses,value:String(expenses.length),detail:labels.records}},
  {id:"invoices",type:"metric" as const,props:{label:labels.invoices,value:String(invoices.length),detail:labels.records}},
  {id:"planner",type:"schedule" as const,props:{title:labels.openPlanner,items:open.slice(0,8).map((item,index)=>({id:`planner-item-${index}`,time:labels.noValue,title:labels.plannerItem,detail:"",value:""}))}},
 ]}
}

export default function X30AlphaPage(){
 const {locale}=useI18n(); const c=copy[locale]; const b=briefUi[locale]; const t=tokenLabels[locale]; const {data:session,isPending}=useSession(); const [showDemo,setShowDemo]=useState(false); const [brief,setBrief]=useState<X30Brief>({...DEFAULT_X30_BRIEF,language:locale}); const [briefState,setBriefState]=useState<X30Brief["reviewState"]>("draft"); const [briefErrors,setBriefErrors]=useState<string[]>([])
 const [isGenerating,setIsGenerating]=useState(false); const [generationState,setGenerationState]=useState<"idle"|"loading"|"ready"|"rejected"|"auth"|"owner"|"disabled"|"quota"|"conflict"|"timeout"|"unavailable">("idle"); const [generatedSpec,setGeneratedSpec]=useState<X30AppSpec|null>(null)
 const {items:customers,cloudEnabled:customerCloud}=useWorkspaceData<Row>("customers")
 const {items:documents}=useWorkspaceData<Row>("documents")
 const {items:expenses}=useWorkspaceData<Row>("expenses")
 const {items:invoices}=useWorkspaceData<Row>("invoice_documents")
 const {items:planner}=useWorkspaceData<Row>("planner")
 const cloud=Boolean(session?.user) && customerCloud
 const hasData=customers.length+documents.length+expenses.length+invoices.length+planner.length>0
 const spec=workspaceSpec(customers,documents,expenses,invoices,planner,c)
 const genericAvatar = ({en:"Demo profile",hu:"Bemutatóprofil",de:"Demo-Profil",fr:"Profil de démo",es:"Perfil de demo"} as const)[locale]
 const rendererLabels: X30RendererLabels = { schedule:c.schedule, readOnlyPreview:c.readOnly, structuredPreview:c.structured, previewRejected:c.rejected, genericPlannerItem:c.plannerItem, noValue:c.noValue, genericAvatar }
 const currentBrief: X30Brief={...brief,language:locale,reviewState:briefState,approvalState:briefState==="preview-only"?"owner-approved-preview":"not-requested"}
 const briefValidation=validateX30Brief(currentBrief)
 const briefSpec=briefValidation.ok&&briefState==="preview-only"?mapX30BriefToSpec(briefValidation.brief,{eyebrow:c.cloud,title:c.preview,description:c.previewDescription,customers:c.customers,documents:c.documents,expenses:c.expenses,invoices:c.invoices,records:c.records,schedule:c.openPlanner,noValue:c.noValue,plannerItem:c.plannerItem},{customers:customers.length,documents:documents.length,expenses:expenses.length,invoices:invoices.length,planner:planner.length}):null
 const update=(key:keyof X30Brief,value:unknown)=>{setBriefState("draft");setBriefErrors([]);setGeneratedSpec(null);setGenerationState("idle");setBrief((old)=>({...old,[key]:value}))}
 const review=()=>{const result=validateX30Brief({...currentBrief,reviewState:"ready-for-review",approvalState:"not-requested"}); if(result.ok){setBrief(result.brief);setBriefState("ready-for-review");setBriefErrors([])}else setBriefErrors(result.errors)}
 const approve=()=>{const result=validateX30Brief({...currentBrief,reviewState:"preview-only",approvalState:"owner-approved-preview"}); if(result.ok){setBrief(result.brief);setBriefState("preview-only");setBriefErrors([])}else setBriefErrors(result.errors)}
 const draft=()=>{setBriefState("draft");setBriefErrors([]);setGeneratedSpec(null);setGenerationState("idle")}
 const generatePreview=async()=>{if(isGenerating||briefState!=="preview-only") return; setIsGenerating(true);setGenerationState("loading");setGeneratedSpec(null); try {const request=buildX30GenerationRequest(currentBrief,crypto.randomUUID(),"authenticated"); const response=await fetch("/api/x30/generate",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({operationId:request.operation.operationId,brief:request.brief})}); if(!response.ok){setGenerationState(response.status===401?"auth":response.status===403?"owner":response.status===429?"quota":response.status===409?"conflict":response.status===504?"timeout":response.status===503?"disabled":"unavailable");return} const payload:unknown=await response.json(); const checked=validateX30GenerationResult(payload); if(!checked.ok||!checked.result||checked.result.status!=="ready-for-review"||checked.result.provenance.source!=="x30-ai"){setGenerationState("rejected");return} setGeneratedSpec(checked.result.spec||null);setGenerationState(checked.result.spec?"ready":"rejected")}catch{setGenerationState("unavailable")}finally{setIsGenerating(false)}}
 const generationMessage={idle:"",loading:c.generating,ready:c.ready,rejected:c.rejected,auth:c.authRequired,owner:c.ownerOnly,disabled:c.disabled,quota:c.quota,conflict:c.conflict,timeout:c.timeout,unavailable:c.unavailable}[generationState]
 return <AppShell><main className="mx-auto max-w-[1500px] px-4 py-8 sm:px-6 lg:px-8">
  <section className="x30-crown"><div><Link href="/app-studio" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/><span>{c.back}</span></Link><p>{c.runtime}</p><h1>X30 <span>{c.alpha}</span></h1><b>{c.eyebrow}</b><small>{c.intro}</small></div><div className="x30-core-object" aria-hidden><i/><i/><i/><Layers3/></div></section>
  <section className="x30-pipeline" aria-label={c.pipeline}>{c.steps.map(([title,detail],index)=>{const Icon=[Braces,Palette,Layers3,ShieldCheck,CheckCircle2][index]; return <div key={title}><span>{String(index+1).padStart(2,"0")}</span><Icon aria-hidden/><b>{title}</b><small>{detail}</small>{index<4&&<ArrowRight aria-hidden/>}</div>})}</section>
  <BriefEditor brief={brief} briefState={briefState} errors={briefErrors} copy={b} labels={t} update={update} review={review} approve={approve} draft={draft} />
  <section className="mt-8"><div className="mb-3 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">{showDemo ? c.demoLabel : cloud ? c.cloud : c.local}</p><h2 className="mt-1 text-lg font-semibold">{showDemo ? c.demoDirection : c.preview}</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">{showDemo ? c.demoLabel : c.previewDescription}</p></div><div className="flex flex-wrap items-center gap-2"><span className="hidden items-center gap-2 rounded-full border border-violet/25 bg-violet/10 px-3 py-1.5 text-xs text-violet sm:inline-flex"><FlaskConical className="size-3.5"/>{showDemo ? c.demoLabel : c.readOnly}</span><button type="button" disabled={isGenerating||briefState!=="preview-only"} aria-disabled={isGenerating||briefState!=="preview-only"} onClick={generatePreview} className="rounded-lg border border-violet/40 px-3 py-2 text-xs font-semibold text-violet disabled:cursor-not-allowed disabled:opacity-40">{isGenerating ? c.generating : c.generate}</button><button type="button" onClick={()=>setShowDemo((value)=>!value)} className="rounded-lg border border-border px-3 py-2 text-xs font-semibold">{showDemo ? c.hideDemo : c.demo}</button></div></div>{generationMessage&&<p role="status" className="mb-4 rounded-lg border border-border bg-background/40 px-3 py-2 text-sm text-muted-foreground">{generationMessage}</p>}{!isPending && !showDemo && !hasData ? <div role="status" className="rounded-2xl border border-border bg-background/40 p-6 text-sm text-muted-foreground">{c.empty}</div> : <SafeX30Renderer spec={showDemo ? pawflowX30Fixture : generatedSpec || briefSpec || spec} labels={rendererLabels}/>}</section>
 </main></AppShell>
}
