"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { useI18n } from "@/lib/i18n/provider"

const COPY = {
  en: { title:"Customer referrals",create:"Create referral link",copy:"Copy referral link",copied:"Referral link copied",revoke:"Revoke",empty:"No referred registrations yet.",pending:"Reward pending review",approved:"Reward approved",rejected:"Reward rejected",reversed:"Reward reversed",entitlementNotVerified:"Entitlement not verified",invalidReferral:"Invalid referral",selfReferral:"Self-referral rejected",ownerOnly:"Only the HEGEVA owner can approve or reject reward eligibility.",noAutomaticReward:"Approval records eligibility only. No payout, credit or discount is created automatically.",approve:"Approve eligibility",reject:"Reject eligibility",touches:"Aggregate referral touches",reviewUnavailable:"Reward review is temporarily unavailable." },
  hu: { title:"Ügyfélajánlások",create:"Ajánlói link létrehozása",copy:"Ajánlói link másolása",copied:"Az ajánlói link kimásolva",revoke:"Visszavonás",empty:"Még nincs ajánlott regisztráció.",pending:"Jutalom ellenőrzésre vár",approved:"Jutalom jóváhagyva",rejected:"Jutalom elutasítva",reversed:"Jutalom visszavonva",entitlementNotVerified:"A jogosultság nincs hitelesítve",invalidReferral:"Érvénytelen ajánlás",selfReferral:"Saját ajánlás elutasítva",ownerOnly:"A jutalom jogosultságát csak a HEGEVA tulajdonosa hagyhatja jóvá vagy utasíthatja el.",noAutomaticReward:"A jóváhagyás csak a jogosultságot rögzíti. Kifizetés, jóváírás vagy kedvezmény nem jön létre automatikusan.",approve:"Jogosultság jóváhagyása",reject:"Jogosultság elutasítása",touches:"Összesített ajánlási érintések",reviewUnavailable:"A jutalom ellenőrzése átmenetileg nem érhető el." },
  de: { title:"Kundenempfehlungen",create:"Empfehlungslink erstellen",copy:"Empfehlungslink kopieren",copied:"Empfehlungslink kopiert",revoke:"Widerrufen",empty:"Noch keine empfohlenen Registrierungen.",pending:"Prämie wartet auf Prüfung",approved:"Prämie genehmigt",rejected:"Prämie abgelehnt",reversed:"Prämie zurückgenommen",entitlementNotVerified:"Berechtigung nicht verifiziert",invalidReferral:"Ungültige Empfehlung",selfReferral:"Selbstempfehlung abgelehnt",ownerOnly:"Nur der HEGEVA-Inhaber kann die Prämienberechtigung genehmigen oder ablehnen.",noAutomaticReward:"Die Genehmigung dokumentiert nur die Berechtigung. Es wird nicht automatisch ausgezahlt, gutgeschrieben oder rabattiert.",approve:"Berechtigung genehmigen",reject:"Berechtigung ablehnen",touches:"Aggregierte Empfehlungskontakte",reviewUnavailable:"Die Prämienprüfung ist vorübergehend nicht verfügbar." },
  fr: { title:"Parrainages clients",create:"Créer un lien de parrainage",copy:"Copier le lien de parrainage",copied:"Lien de parrainage copié",revoke:"Révoquer",empty:"Aucune inscription recommandée.",pending:"Récompense en attente d’examen",approved:"Récompense approuvée",rejected:"Récompense rejetée",reversed:"Récompense annulée",entitlementNotVerified:"Droit non vérifié",invalidReferral:"Parrainage invalide",selfReferral:"Auto-parrainage rejeté",ownerOnly:"Seul le propriétaire HEGEVA peut approuver ou rejeter l’éligibilité.",noAutomaticReward:"L’approbation enregistre uniquement l’éligibilité. Aucun paiement, crédit ou rabais n’est créé automatiquement.",approve:"Approuver l’éligibilité",reject:"Rejeter l’éligibilité",touches:"Interactions de parrainage agrégées",reviewUnavailable:"L’examen de la récompense est temporairement indisponible." },
  es: { title:"Referencias de clientes",create:"Crear enlace de referencia",copy:"Copiar enlace de referencia",copied:"Enlace de referencia copiado",revoke:"Revocar",empty:"Aún no hay registros referidos.",pending:"Recompensa pendiente de revisión",approved:"Recompensa aprobada",rejected:"Recompensa rechazada",reversed:"Recompensa revertida",entitlementNotVerified:"Derecho no verificado",invalidReferral:"Referencia no válida",selfReferral:"Autorreferencia rechazada",ownerOnly:"Solo el propietario de HEGEVA puede aprobar o rechazar la elegibilidad.",noAutomaticReward:"La aprobación solo registra la elegibilidad. No se crea automáticamente ningún pago, crédito o descuento.",approve:"Aprobar elegibilidad",reject:"Rechazar elegibilidad",touches:"Interacciones de referencia agregadas",reviewUnavailable:"La revisión de la recompensa no está disponible temporalmente." },
} as const

type ReferralCode = { id:string;code:string }
type Attribution = { id:string;firstTouchAt:string;attributionState:string }
type RewardStatus = "pending"|"approved"|"rejected"|"reversed"
type RewardReview = { status:RewardStatus;touchCount:number;id?:string;canReview?:boolean }

export function ReferralReview(){
  const{locale}=useI18n(),c=COPY[locale as keyof typeof COPY]??COPY.en
  const[code,setCode]=useState<ReferralCode|null>(null),[items,setItems]=useState<Attribution[]>([]),[reviews,setReviews]=useState<RewardReview[]>([]),[copied,setCopied]=useState(false),[reviewing,setReviewing]=useState(""),[notice,setNotice]=useState("")
  const loadReviews=useCallback(()=>fetch("/api/referrals/reward-reviews",{credentials:"include",cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>setReviews(Array.isArray(d?.items)?d.items:[])).catch(()=>setNotice(c.reviewUnavailable)),[c.reviewUnavailable])
  useEffect(()=>{fetch("/api/referrals/attributions",{credentials:"include"}).then(r=>r.ok?r.json():null).then(d=>setItems(d?.items||[]));void loadReviews()},[loadReviews])
  const referralUrl=useMemo(()=>code&&typeof window!=="undefined"?`${window.location.origin}/r/${code.code}`:"",[code])
  const copyReferral=async()=>{if(!referralUrl)return;await navigator.clipboard.writeText(referralUrl);setCopied(true);window.setTimeout(()=>setCopied(false),2000)}
  const decide=async(review:RewardReview,decision:"approved"|"rejected")=>{if(!review.canReview||!review.id||reviewing)return;setReviewing(review.id);setNotice("");try{const response=await fetch(`/api/referrals/reward-reviews/${review.id}`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({decision,reason:"owner-reviewed-v1"})});if(!response.ok){setNotice(c.reviewUnavailable);return}window.dispatchEvent(new CustomEvent("hegeva:analytics-event",{detail:{event:"referral_reward_reviewed",path:"/account",params:{outcome:decision,status:decision,methodologyVersion:"referral-reward-review-v1"}}}));await loadReviews()}finally{setReviewing("")}}
  const statusLabel=(status:RewardStatus)=>c[status]
  return <section className="mt-8 glass-panel rounded-3xl p-6"><h2 className="text-lg font-semibold">{c.title}</h2><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={async()=>{const r=await fetch("/api/referrals/code",{method:"POST",credentials:"include"}),d=await r.json();if(r.ok)setCode(d);else setNotice(c.invalidReferral)}} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold">{c.create}</button>{code&&<><code className="max-w-full break-all rounded-xl border border-border px-3 py-2 text-sm">{referralUrl}</code><button type="button" onClick={()=>void copyReferral()} className="rounded-xl border border-primary/30 px-3 py-2 text-sm">{copied?c.copied:c.copy}</button><button type="button" onClick={async()=>{await fetch(`/api/referrals/code/${code.id}`,{method:"DELETE",credentials:"include"});setCode(null);setCopied(false)}} className="rounded-xl border border-border px-3 py-2 text-sm">{c.revoke}</button></>}</div>{items.length===0&&reviews.length===0?<p className="mt-4 text-sm text-muted-foreground">{c.empty}</p>:items.length>0&&reviews.length===0?<ul className="mt-4 space-y-2">{items.map(x=><li key={x.id} className="rounded-xl border border-border p-3 text-sm">{c.entitlementNotVerified} · {new Date(x.firstTouchAt).toLocaleDateString(locale)}</li>)}</ul>:null}<div className="mt-4 space-y-3">{reviews.map((review,index)=><article key={review.id||`${review.status}-${index}`} className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm">{statusLabel(review.status)}</strong><span className="text-xs text-muted-foreground">{c.touches}: {review.touchCount}</span></div><p className="mt-2 text-xs text-muted-foreground">{c.noAutomaticReward}</p>{review.canReview&&review.status==="pending"&&<div className="mt-3 flex flex-wrap gap-2"><button disabled={Boolean(reviewing)} onClick={()=>void decide(review,"approved")} className="rounded-xl bg-primary px-3 py-2 text-sm font-semibold disabled:opacity-50">{c.approve}</button><button disabled={Boolean(reviewing)} onClick={()=>void decide(review,"rejected")} className="rounded-xl border border-border px-3 py-2 text-sm disabled:opacity-50">{c.reject}</button></div>}</article>)}</div><p className="mt-4 text-xs text-muted-foreground">{c.ownerOnly}</p>{notice&&<p role="alert" className="mt-3 text-sm text-muted-foreground">{notice}</p>}</section>
}
