import type { Locale } from "./dictionaries"

export const ACCOUNT_COPY: Record<Locale, {
  eyebrow:string; title:string; subtitle:string; checking:string; signInTitle:string; signInBody:string; signIn:string;
  details:string; name:string; email:string; plan:string; usage:string; period:string; unavailable:string;
  workspace:string; assistant:string; pricing:string; support:string; logout:string; billingSuccess:string; billingSignIn:string;
}> = {
  en:{eyebrow:"HEGEVA ACCOUNT",title:"Your account",subtitle:"Review your real account, plan and current AI usage.",checking:"Checking your HEGEVA account…",signInTitle:"Sign in required",signInBody:"Sign in to view your private account information.",signIn:"Go to login",details:"Account details",name:"Name",email:"Email",plan:"Current plan",usage:"AI messages used",period:"Usage period",unavailable:"Plan information is temporarily unavailable.",workspace:"Open workspace",assistant:"Open Assistant",pricing:"View plans",support:"Contact support",logout:"Logout",billingSuccess:"Sandbox payment completed. Your plan will appear here after the verified Stripe webhook is processed.",billingSignIn:"The Sandbox payment completed. Sign in again to securely view the updated plan."},
  hu:{eyebrow:"HEGEVA FIÓK",title:"A fiókod",subtitle:"Tekintsd meg valódi fiókadataidat, csomagodat és aktuális AI-használatodat.",checking:"HEGEVA-fiók ellenőrzése…",signInTitle:"Bejelentkezés szükséges",signInBody:"A személyes fiókadatok megtekintéséhez jelentkezz be.",signIn:"Belépés",details:"Fiókadatok",name:"Név",email:"E-mail",plan:"Jelenlegi csomag",usage:"Felhasznált AI-üzenetek",period:"Használati időszak",unavailable:"A csomaginformáció átmenetileg nem érhető el.",workspace:"Munkaterület megnyitása",assistant:"Asszisztens megnyitása",pricing:"Csomagok megtekintése",support:"Kapcsolatfelvétel",logout:"Kijelentkezés",billingSuccess:"A Sandbox fizetés sikerült. A csomagod a hitelesített Stripe webhook feldolgozása után jelenik meg itt.",billingSignIn:"A Sandbox fizetés sikerült. Jelentkezz be újra, hogy biztonságosan lásd a frissített csomagodat."},
  de:{eyebrow:"HEGEVA KONTO",title:"Ihr Konto",subtitle:"Prüfen Sie Ihre echten Kontodaten, Ihren Tarif und die aktuelle KI-Nutzung.",checking:"HEGEVA-Konto wird geprüft…",signInTitle:"Anmeldung erforderlich",signInBody:"Melden Sie sich an, um Ihre privaten Kontoinformationen zu sehen.",signIn:"Zur Anmeldung",details:"Kontodaten",name:"Name",email:"E-Mail",plan:"Aktueller Tarif",usage:"Verwendete KI-Nachrichten",period:"Nutzungszeitraum",unavailable:"Tarifinformationen sind vorübergehend nicht verfügbar.",workspace:"Arbeitsbereich öffnen",assistant:"Assistent öffnen",pricing:"Tarife ansehen",support:"Support kontaktieren",logout:"Abmelden",billingSuccess:"Die Sandbox-Zahlung war erfolgreich. Der Tarif erscheint nach Verarbeitung des verifizierten Stripe-Webhooks.",billingSignIn:"Die Sandbox-Zahlung war erfolgreich. Melden Sie sich erneut an, um den aktualisierten Tarif sicher zu sehen."},
  fr:{eyebrow:"COMPTE HEGEVA",title:"Votre compte",subtitle:"Consultez vos véritables informations de compte, votre offre et votre utilisation actuelle de l’IA.",checking:"Vérification de votre compte HEGEVA…",signInTitle:"Connexion requise",signInBody:"Connectez-vous pour afficher les informations privées de votre compte.",signIn:"Se connecter",details:"Informations du compte",name:"Nom",email:"E-mail",plan:"Offre actuelle",usage:"Messages IA utilisés",period:"Période d’utilisation",unavailable:"Les informations de l’offre sont temporairement indisponibles.",workspace:"Ouvrir l’espace de travail",assistant:"Ouvrir l’Assistant",pricing:"Voir les offres",support:"Contacter le support",logout:"Se déconnecter",billingSuccess:"Le paiement Sandbox a réussi. Votre offre apparaîtra après le traitement du webhook Stripe vérifié.",billingSignIn:"Le paiement Sandbox a réussi. Reconnectez-vous pour consulter votre offre mise à jour en toute sécurité."},
  es:{eyebrow:"CUENTA HEGEVA",title:"Tu cuenta",subtitle:"Consulta los datos reales de tu cuenta, tu plan y el uso actual de IA.",checking:"Comprobando tu cuenta HEGEVA…",signInTitle:"Debes iniciar sesión",signInBody:"Inicia sesión para ver la información privada de tu cuenta.",signIn:"Ir al inicio de sesión",details:"Datos de la cuenta",name:"Nombre",email:"Correo electrónico",plan:"Plan actual",usage:"Mensajes de IA utilizados",period:"Periodo de uso",unavailable:"La información del plan no está disponible temporalmente.",workspace:"Abrir espacio de trabajo",assistant:"Abrir Asistente",pricing:"Ver planes",support:"Contactar con soporte",logout:"Cerrar sesión",billingSuccess:"El pago Sandbox se completó. Tu plan aparecerá cuando se procese el webhook verificado de Stripe.",billingSignIn:"El pago Sandbox se completó. Inicia sesión de nuevo para ver el plan actualizado de forma segura."}
}
