import type { Locale } from "./dictionaries"

const en = { title:"Secure account access", subtitle:"Sign in to use your authenticated HEGEVA workspace, AI usage limits and cloud-saved business data.", login:"Login", register:"Register", name:"Name", yourName:"Your name", email:"Email", password:"Password", minPassword:"Minimum 8 characters", forgot:"Forgot your password?", wait:"Please wait…", create:"Create account", sendReset:"Send reset link", back:"Back to login", checking:"Checking your session…", signedIn:"You are signed in as", open:"Open Command Center", resetTitle:"Reset your password", resetSubtitle:"Choose a new secure password for your HEGEVA workspace.", newPassword:"New password", confirm:"Confirm new password", update:"Update password", updating:"Updating…", updated:"Password updated", returnLogin:"Return to login", mismatch:"The passwords do not match.", invalid:"This reset link is invalid or has expired." }
type Copy = typeof en
export const AUTH_COPY: Record<Locale, Copy> = {
 en,
 hu:{title:"Biztonságos fiókhozzáférés",subtitle:"Jelentkezz be a hitelesített HEGEVA munkaterület, az AI-limitek és a felhőben mentett üzleti adatok használatához.",login:"Belépés",register:"Regisztráció",name:"Név",yourName:"A neved",email:"Email",password:"Jelszó",minPassword:"Legalább 8 karakter",forgot:"Elfelejtetted a jelszavad?",wait:"Kérlek, várj…",create:"Fiók létrehozása",sendReset:"Visszaállító link küldése",back:"Vissza a belépéshez",checking:"Munkamenet ellenőrzése…",signedIn:"Bejelentkezve mint",open:"Vezérlőközpont megnyitása",resetTitle:"Jelszó visszaállítása",resetSubtitle:"Válassz új, biztonságos jelszót a HEGEVA munkaterületedhez.",newPassword:"Új jelszó",confirm:"Új jelszó megerősítése",update:"Jelszó frissítése",updating:"Frissítés…",updated:"Jelszó frissítve",returnLogin:"Vissza a belépéshez",mismatch:"A jelszavak nem egyeznek.",invalid:"A visszaállító link érvénytelen vagy lejárt."},
 de:{title:"Sicherer Kontozugang",subtitle:"Melden Sie sich für den authentifizierten HEGEVA-Arbeitsbereich, KI-Limits und Cloud-Daten an.",login:"Anmelden",register:"Registrieren",name:"Name",yourName:"Ihr Name",email:"E-Mail",password:"Passwort",minPassword:"Mindestens 8 Zeichen",forgot:"Passwort vergessen?",wait:"Bitte warten…",create:"Konto erstellen",sendReset:"Link senden",back:"Zurück zur Anmeldung",checking:"Sitzung wird geprüft…",signedIn:"Angemeldet als",open:"Kommandozentrale öffnen",resetTitle:"Passwort zurücksetzen",resetSubtitle:"Wählen Sie ein neues sicheres Passwort.",newPassword:"Neues Passwort",confirm:"Passwort bestätigen",update:"Passwort aktualisieren",updating:"Aktualisierung…",updated:"Passwort aktualisiert",returnLogin:"Zur Anmeldung",mismatch:"Die Passwörter stimmen nicht überein.",invalid:"Dieser Link ist ungültig oder abgelaufen."},
 fr:{title:"Accès sécurisé au compte",subtitle:"Connectez-vous pour utiliser l’espace HEGEVA authentifié, les limites IA et les données cloud.",login:"Connexion",register:"Inscription",name:"Nom",yourName:"Votre nom",email:"E-mail",password:"Mot de passe",minPassword:"8 caractères minimum",forgot:"Mot de passe oublié ?",wait:"Veuillez patienter…",create:"Créer un compte",sendReset:"Envoyer le lien",back:"Retour à la connexion",checking:"Vérification de la session…",signedIn:"Connecté en tant que",open:"Ouvrir le centre de commande",resetTitle:"Réinitialiser le mot de passe",resetSubtitle:"Choisissez un nouveau mot de passe sécurisé.",newPassword:"Nouveau mot de passe",confirm:"Confirmer le mot de passe",update:"Mettre à jour",updating:"Mise à jour…",updated:"Mot de passe mis à jour",returnLogin:"Retour à la connexion",mismatch:"Les mots de passe ne correspondent pas.",invalid:"Ce lien est invalide ou expiré."},
 es:{title:"Acceso seguro a la cuenta",subtitle:"Inicia sesión para usar el espacio HEGEVA autenticado, los límites de IA y los datos en la nube.",login:"Entrar",register:"Registrarse",name:"Nombre",yourName:"Tu nombre",email:"Correo",password:"Contraseña",minPassword:"Mínimo 8 caracteres",forgot:"¿Olvidaste tu contraseña?",wait:"Espera…",create:"Crear cuenta",sendReset:"Enviar enlace",back:"Volver al acceso",checking:"Comprobando sesión…",signedIn:"Sesión iniciada como",open:"Abrir centro de mando",resetTitle:"Restablecer contraseña",resetSubtitle:"Elige una nueva contraseña segura.",newPassword:"Nueva contraseña",confirm:"Confirmar contraseña",update:"Actualizar contraseña",updating:"Actualizando…",updated:"Contraseña actualizada",returnLogin:"Volver al acceso",mismatch:"Las contraseñas no coinciden.",invalid:"Este enlace no es válido o ha caducado."}
}
