import type { Locale } from "./dictionaries"

export const businessModulesCopy = {
  en: {
    eyebrow: "Business Workspace",
    planner: { title: "Planner / Time Saver", subtitle: "Capture priorities, due dates and quick tasks in one place. Signed-in accounts keep this real data synced to their cloud workspace.", saving: "Saving to cloud…", synced: "Cloud synced", checking: "Checking cloud…", browser: "Saved in this browser", cloudBody: "Planner tasks sync to your authenticated HEGEVA workspace.", guestBody: "Sign in to enable cloud sync.", errorBody: "Cloud sync is temporarily unavailable. Your browser copy remains available.", add: "Add task", addBody: "Create only the work you actually want to track.", taskTitle: "Task title", low: "Low priority", medium: "Medium priority", high: "High priority", yourTasks: "Your tasks", open: "open", total: "total", empty: "No tasks saved yet.", due: "Due", markOpen: "Mark open", markDone: "Mark done", delete: "Delete task" },
    reports: { title: "Reports", subtitle: "Summaries are calculated from your real cloud workspace data, with a browser-local fallback. No demo revenue, customers or activity are invented.", customers: "Customers", customerNote: "Saved customer records", documents: "Documents", documentNote: "Saved document records", expenses: "Expenses", expenseEntries: "saved expense entries", openTasks: "Open tasks", completedTasks: "completed tasks", integrity: "Report integrity", integrityCloud: "Every figure above is derived from records stored in your authenticated HEGEVA cloud workspace.", integrityBrowser: "Every figure above is derived from records stored in your HEGEVA browser workspace.", integrityNote: "Revenue, profit, conversion, savings and other performance numbers are intentionally not shown because HEGEVA does not have verified source data for them yet." },
    messages: { title: "Message Studio", subtitle: "Draft customer replies, follow-ups, reminders and business messages. Signed-in drafts sync to your workspace but are never presented as sent.", saving: "Saving to cloud…", synced: "Cloud synced", checking: "Checking cloud…", browser: "Saved in this browser", cloudBody: "Drafts sync to your authenticated HEGEVA workspace.", guestBody: "Sign in to enable cloud sync.", errorBody: "Cloud sync is temporarily unavailable. Your browser copy remains available.", newDraft: "New draft", types: ["Customer reply", "Follow-up", "Payment reminder", "Sales message", "Support response", "Business email"], tones: ["Professional", "Friendly", "Short", "Formal"], recipient: "Recipient (optional)", subject: "Subject (optional)", body: "Write or paste your draft message", save: "Save draft", honesty: "Saving a draft does not send it. No email or message integration is claimed as active in this version.", empty: "No saved drafts yet", emptyBody: "Create a real draft when you need one. HEGEVA will not fabricate sent messages or customer activity.", to: "To", copy: "Copy draft", delete: "Delete draft", saved: "Saved" },
  },
  hu: {
    eyebrow: "Üzleti munkaterület",
    planner: { title: "Tervező / Időmegtakarító", subtitle: "Prioritások, határidők és gyors feladatok egy helyen. A bejelentkezett fiókok valódi adatai szinkronizálódnak a felhőalapú munkaterülettel.", saving: "Mentés a felhőbe…", synced: "Felhővel szinkronizálva", checking: "Felhő ellenőrzése…", browser: "Mentve ebben a böngészőben", cloudBody: "A tervező feladatai a hitelesített HEGEVA munkaterülettel szinkronizálódnak.", guestBody: "Jelentkezz be a felhőszinkron bekapcsolásához.", errorBody: "A felhőszinkron átmenetileg nem érhető el. A böngészős másolat megmarad.", add: "Feladat hozzáadása", addBody: "Csak olyan valódi munkát rögzíts, amelyet követni szeretnél.", taskTitle: "Feladat neve", low: "Alacsony prioritás", medium: "Közepes prioritás", high: "Magas prioritás", yourTasks: "Feladataid", open: "nyitott", total: "összesen", empty: "Még nincs mentett feladat.", due: "Határidő", markOpen: "Megjelölés nyitottként", markDone: "Megjelölés elvégzettként", delete: "Feladat törlése" },
    reports: { title: "Jelentések", subtitle: "Az összesítések a valódi felhőalapú munkaterületi adatokból készülnek, böngészős biztonsági másolattal. Nincs kitalált bevétel, ügyfél vagy tevékenység.", customers: "Ügyfelek", customerNote: "Mentett ügyféladatok", documents: "Dokumentumok", documentNote: "Mentett dokumentumadatok", expenses: "Kiadások", expenseEntries: "mentett kiadási tétel", openTasks: "Nyitott feladatok", completedTasks: "elvégzett feladat", integrity: "A jelentés hitelessége", integrityCloud: "Minden fenti érték a hitelesített HEGEVA felhőalapú munkaterületeden tárolt adatokból származik.", integrityBrowser: "Minden fenti érték a HEGEVA böngészős munkaterületén tárolt adatokból származik.", integrityNote: "A bevétel, nyereség, konverzió, megtakarítás és más teljesítményadatok szándékosan nem jelennek meg, mert a HEGEVA még nem rendelkezik hozzájuk ellenőrzött forrásadatokkal." },
    messages: { title: "Üzenetstúdió", subtitle: "Ügyfélválaszok, utánkövetések, emlékeztetők és üzleti üzenetek készítése. A bejelentkezett fiókok vázlatai szinkronizálódnak, de soha nem jelennek meg elküldöttként.", saving: "Mentés a felhőbe…", synced: "Felhővel szinkronizálva", checking: "Felhő ellenőrzése…", browser: "Mentve ebben a böngészőben", cloudBody: "A vázlatok a hitelesített HEGEVA munkaterülettel szinkronizálódnak.", guestBody: "Jelentkezz be a felhőszinkron bekapcsolásához.", errorBody: "A felhőszinkron átmenetileg nem érhető el. A böngészős másolat megmarad.", newDraft: "Új vázlat", types: ["Ügyfélválasz", "Utánkövetés", "Fizetési emlékeztető", "Értékesítési üzenet", "Támogatási válasz", "Üzleti e-mail"], tones: ["Professzionális", "Barátságos", "Rövid", "Hivatalos"], recipient: "Címzett (nem kötelező)", subject: "Tárgy (nem kötelező)", body: "Írd vagy illeszd be az üzenetvázlatot", save: "Vázlat mentése", honesty: "A vázlat mentése nem küldi el az üzenetet. Ebben a verzióban nem állítjuk, hogy aktív e-mail- vagy üzenetküldő integráció működik.", empty: "Még nincs mentett vázlat", emptyBody: "Készíts valódi vázlatot, amikor szükséged van rá. A HEGEVA nem talál ki elküldött üzeneteket vagy ügyféltevékenységet.", to: "Címzett", copy: "Vázlat másolása", delete: "Vázlat törlése", saved: "Mentve" },
  },
  de: {
    eyebrow: "Business-Arbeitsbereich",
    planner: { title: "Planer / Zeitsparer", subtitle: "Prioritäten, Fristen und kurze Aufgaben an einem Ort. Angemeldete Konten synchronisieren echte Daten mit ihrem Cloud-Arbeitsbereich.", saving: "In der Cloud speichern…", synced: "Cloud synchronisiert", checking: "Cloud wird geprüft…", browser: "In diesem Browser gespeichert", cloudBody: "Planeraufgaben werden mit Ihrem authentifizierten HEGEVA-Arbeitsbereich synchronisiert.", guestBody: "Melden Sie sich an, um die Cloud-Synchronisierung zu aktivieren.", errorBody: "Cloud-Synchronisierung vorübergehend nicht verfügbar. Ihre Browserkopie bleibt erhalten.", add: "Aufgabe hinzufügen", addBody: "Erstellen Sie nur Arbeiten, die Sie wirklich verfolgen möchten.", taskTitle: "Aufgabentitel", low: "Niedrige Priorität", medium: "Mittlere Priorität", high: "Hohe Priorität", yourTasks: "Ihre Aufgaben", open: "offen", total: "gesamt", empty: "Noch keine Aufgaben gespeichert.", due: "Fällig", markOpen: "Als offen markieren", markDone: "Als erledigt markieren", delete: "Aufgabe löschen" },
    reports: { title: "Berichte", subtitle: "Zusammenfassungen werden aus echten Cloud-Daten berechnet, mit lokaler Browser-Sicherung. Keine erfundenen Umsätze, Kunden oder Aktivitäten.", customers: "Kunden", customerNote: "Gespeicherte Kundeneinträge", documents: "Dokumente", documentNote: "Gespeicherte Dokumenteinträge", expenses: "Ausgaben", expenseEntries: "gespeicherte Ausgabeneinträge", openTasks: "Offene Aufgaben", completedTasks: "erledigte Aufgaben", integrity: "Datenintegrität", integrityCloud: "Alle obigen Werte stammen aus Datensätzen in Ihrem authentifizierten HEGEVA-Cloud-Arbeitsbereich.", integrityBrowser: "Alle obigen Werte stammen aus Datensätzen in Ihrem HEGEVA-Browser-Arbeitsbereich.", integrityNote: "Umsatz, Gewinn, Konversion, Einsparungen und andere Leistungswerte werden bewusst nicht angezeigt, da HEGEVA dafür noch keine verifizierten Quelldaten besitzt." },
    messages: { title: "Nachrichtenstudio", subtitle: "Kundenantworten, Nachfassaktionen, Erinnerungen und Geschäftsnachrichten entwerfen. Angemeldete Entwürfe werden synchronisiert, aber nie als gesendet dargestellt.", saving: "In der Cloud speichern…", synced: "Cloud synchronisiert", checking: "Cloud wird geprüft…", browser: "In diesem Browser gespeichert", cloudBody: "Entwürfe werden mit Ihrem authentifizierten HEGEVA-Arbeitsbereich synchronisiert.", guestBody: "Melden Sie sich an, um die Cloud-Synchronisierung zu aktivieren.", errorBody: "Cloud-Synchronisierung vorübergehend nicht verfügbar. Ihre Browserkopie bleibt erhalten.", newDraft: "Neuer Entwurf", types: ["Kundenantwort", "Nachfassung", "Zahlungserinnerung", "Verkaufsnachricht", "Support-Antwort", "Geschäftliche E-Mail"], tones: ["Professionell", "Freundlich", "Kurz", "Formell"], recipient: "Empfänger (optional)", subject: "Betreff (optional)", body: "Entwurfsnachricht schreiben oder einfügen", save: "Entwurf speichern", honesty: "Das Speichern eines Entwurfs sendet ihn nicht. In dieser Version wird keine aktive E-Mail- oder Nachrichtenintegration behauptet.", empty: "Noch keine Entwürfe gespeichert", emptyBody: "Erstellen Sie bei Bedarf einen echten Entwurf. HEGEVA erfindet keine gesendeten Nachrichten oder Kundenaktivitäten.", to: "An", copy: "Entwurf kopieren", delete: "Entwurf löschen", saved: "Gespeichert" },
  },
  fr: {
    eyebrow: "Espace professionnel",
    planner: { title: "Planificateur / Gain de temps", subtitle: "Centralisez priorités, échéances et tâches rapides. Les comptes connectés synchronisent ces données réelles avec leur espace cloud.", saving: "Enregistrement dans le cloud…", synced: "Cloud synchronisé", checking: "Vérification du cloud…", browser: "Enregistré dans ce navigateur", cloudBody: "Les tâches sont synchronisées avec votre espace HEGEVA authentifié.", guestBody: "Connectez-vous pour activer la synchronisation cloud.", errorBody: "Synchronisation temporairement indisponible. Votre copie locale reste accessible.", add: "Ajouter une tâche", addBody: "Créez uniquement le travail que vous souhaitez réellement suivre.", taskTitle: "Titre de la tâche", low: "Priorité faible", medium: "Priorité moyenne", high: "Priorité élevée", yourTasks: "Vos tâches", open: "ouvertes", total: "au total", empty: "Aucune tâche enregistrée.", due: "Échéance", markOpen: "Marquer comme ouverte", markDone: "Marquer comme terminée", delete: "Supprimer la tâche" },
    reports: { title: "Rapports", subtitle: "Les résumés utilisent vos données cloud réelles, avec une copie locale de secours. Aucun revenu, client ou activité fictif.", customers: "Clients", customerNote: "Fiches clients enregistrées", documents: "Documents", documentNote: "Fiches documentaires enregistrées", expenses: "Dépenses", expenseEntries: "dépenses enregistrées", openTasks: "Tâches ouvertes", completedTasks: "tâches terminées", integrity: "Intégrité du rapport", integrityCloud: "Tous les chiffres ci-dessus proviennent des données de votre espace cloud HEGEVA authentifié.", integrityBrowser: "Tous les chiffres ci-dessus proviennent des données de votre espace HEGEVA dans ce navigateur.", integrityNote: "Revenus, bénéfices, conversion, économies et autres performances ne sont volontairement pas affichés, car HEGEVA ne dispose pas encore de données sources vérifiées." },
    messages: { title: "Studio de messages", subtitle: "Rédigez réponses clients, suivis, rappels et messages professionnels. Les brouillons connectés sont synchronisés mais jamais présentés comme envoyés.", saving: "Enregistrement dans le cloud…", synced: "Cloud synchronisé", checking: "Vérification du cloud…", browser: "Enregistré dans ce navigateur", cloudBody: "Les brouillons sont synchronisés avec votre espace HEGEVA authentifié.", guestBody: "Connectez-vous pour activer la synchronisation cloud.", errorBody: "Synchronisation temporairement indisponible. Votre copie locale reste accessible.", newDraft: "Nouveau brouillon", types: ["Réponse client", "Suivi", "Rappel de paiement", "Message commercial", "Réponse d’assistance", "E-mail professionnel"], tones: ["Professionnel", "Amical", "Court", "Formel"], recipient: "Destinataire (facultatif)", subject: "Objet (facultatif)", body: "Écrivez ou collez votre brouillon", save: "Enregistrer le brouillon", honesty: "Enregistrer un brouillon ne l’envoie pas. Cette version ne prétend pas disposer d’une intégration active d’e-mail ou de messagerie.", empty: "Aucun brouillon enregistré", emptyBody: "Créez un vrai brouillon quand vous en avez besoin. HEGEVA n’invente ni messages envoyés ni activité client.", to: "À", copy: "Copier le brouillon", delete: "Supprimer le brouillon", saved: "Enregistré" },
  },
  es: {
    eyebrow: "Espacio de negocio",
    planner: { title: "Planificador / Ahorro de tiempo", subtitle: "Reúne prioridades, fechas límite y tareas rápidas. Las cuentas conectadas sincronizan estos datos reales con su espacio en la nube.", saving: "Guardando en la nube…", synced: "Nube sincronizada", checking: "Comprobando la nube…", browser: "Guardado en este navegador", cloudBody: "Las tareas se sincronizan con tu espacio HEGEVA autenticado.", guestBody: "Inicia sesión para activar la sincronización en la nube.", errorBody: "La sincronización no está disponible temporalmente. La copia del navegador permanece accesible.", add: "Añadir tarea", addBody: "Crea solo el trabajo que realmente quieras seguir.", taskTitle: "Título de la tarea", low: "Prioridad baja", medium: "Prioridad media", high: "Prioridad alta", yourTasks: "Tus tareas", open: "abiertas", total: "en total", empty: "Todavía no hay tareas guardadas.", due: "Fecha límite", markOpen: "Marcar como abierta", markDone: "Marcar como completada", delete: "Eliminar tarea" },
    reports: { title: "Informes", subtitle: "Los resúmenes se calculan con datos reales de tu espacio en la nube y una copia local de respaldo. No se inventan ingresos, clientes ni actividad.", customers: "Clientes", customerNote: "Registros de clientes guardados", documents: "Documentos", documentNote: "Registros de documentos guardados", expenses: "Gastos", expenseEntries: "gastos guardados", openTasks: "Tareas abiertas", completedTasks: "tareas completadas", integrity: "Integridad del informe", integrityCloud: "Todas las cifras anteriores proceden de registros almacenados en tu espacio HEGEVA autenticado en la nube.", integrityBrowser: "Todas las cifras anteriores proceden de registros almacenados en tu espacio HEGEVA del navegador.", integrityNote: "Ingresos, beneficios, conversión, ahorro y otros indicadores no se muestran porque HEGEVA todavía no dispone de datos de origen verificados." },
    messages: { title: "Estudio de mensajes", subtitle: "Redacta respuestas, seguimientos, recordatorios y mensajes de negocio. Los borradores conectados se sincronizan, pero nunca aparecen como enviados.", saving: "Guardando en la nube…", synced: "Nube sincronizada", checking: "Comprobando la nube…", browser: "Guardado en este navegador", cloudBody: "Los borradores se sincronizan con tu espacio HEGEVA autenticado.", guestBody: "Inicia sesión para activar la sincronización en la nube.", errorBody: "La sincronización no está disponible temporalmente. La copia del navegador permanece accesible.", newDraft: "Nuevo borrador", types: ["Respuesta al cliente", "Seguimiento", "Recordatorio de pago", "Mensaje de ventas", "Respuesta de soporte", "Correo de negocio"], tones: ["Profesional", "Amable", "Breve", "Formal"], recipient: "Destinatario (opcional)", subject: "Asunto (opcional)", body: "Escribe o pega tu borrador", save: "Guardar borrador", honesty: "Guardar un borrador no lo envía. Esta versión no afirma disponer de una integración activa de correo o mensajería.", empty: "Todavía no hay borradores guardados", emptyBody: "Crea un borrador real cuando lo necesites. HEGEVA no inventa mensajes enviados ni actividad de clientes.", to: "Para", copy: "Copiar borrador", delete: "Eliminar borrador", saved: "Guardado" },
  },
} satisfies Record<Locale, unknown>

export function getBusinessModulesCopy(locale: Locale) {
  return businessModulesCopy[locale]
}
