import type { Locale } from "./dictionaries"

export const COMMAND_OVERVIEW_COPY: Record<Locale, {
  overview:string; overviewDesc:string; customers:string; documents:string; expenses:string; openTasks:string; invoices:string; paid:string;
  attention:string; overdueInvoices:string; overdueTasks:string; noAttention:string; businessModules:string; aiModules:string;
  intelligenceEyebrow?:string; intelligenceDesc?:string; operationsEyebrow?:string; pricing?:string;
  assistantTitle:string; assistantDesc:string; promptTitle:string; promptDesc:string; buildTitle:string; buildDesc:string; fixTitle:string; fixDesc:string;
}> = {
  en:{overview:"Live workspace overview",overviewDesc:"A real-time summary calculated only from data saved in your HEGEVA workspace.",customers:"Customers",documents:"Documents",expenses:"Expenses",openTasks:"Open tasks",invoices:"Invoices & quotes",paid:"Paid invoices",attention:"Needs attention",overdueInvoices:"overdue invoices",overdueTasks:"overdue tasks",noAttention:"Nothing overdue right now.",businessModules:"Business workspace",aiModules:"AI & App Studio",intelligenceEyebrow:"Intelligence layer",intelligenceDesc:"Move from a question to a verified result with the right HEGEVA workspace.",operationsEyebrow:"Operations layer",pricing:"Pricing",assistantTitle:"HEGEVA Assistant",assistantDesc:"Practical multilingual business support connected to your live account.",promptTitle:"Prompt My App",promptDesc:"Turn an idea into a structured application specification.",buildTitle:"Build My App X10",buildDesc:"Plan and build an application through a guided workflow.",fixTitle:"Fix My App X10",fixDesc:"Review an existing application and create an improvement plan."},
  hu:{overview:"Élő munkaterület-áttekintés",overviewDesc:"Valós idejű összesítés, kizárólag a HEGEVA munkaterületedre mentett adatokból.",customers:"Ügyfelek",documents:"Dokumentumok",expenses:"Kiadások",openTasks:"Nyitott feladatok",invoices:"Számlák és ajánlatok",paid:"Fizetett számlák",attention:"Figyelmet igényel",overdueInvoices:"lejárt számla",overdueTasks:"lejárt feladat",noAttention:"Jelenleg nincs lejárt tétel.",businessModules:"Üzleti munkaterület",aiModules:"AI és App Stúdió",intelligenceEyebrow:"Intelligenciaréteg",intelligenceDesc:"A kérdéstől a hitelesített eredményig a megfelelő HEGEVA-munkaterülettel.",operationsEyebrow:"Működési réteg",pricing:"Csomagok",assistantTitle:"HEGEVA Asszisztens",assistantDesc:"Gyakorlati, többnyelvű üzleti segítség az élő fiókodhoz kapcsolva.",promptTitle:"Prompt My App",promptDesc:"Alakítsd az ötletedet strukturált alkalmazásspecifikációvá.",buildTitle:"Build My App X10",buildDesc:"Tervezz és építs alkalmazást vezetett munkafolyamatban.",fixTitle:"Fix My App X10",fixDesc:"Vizsgáld át meglévő alkalmazásodat, és készíts fejlesztési tervet."},
  de:{overview:"Live-Arbeitsbereichsübersicht",overviewDesc:"Eine Echtzeit-Zusammenfassung ausschließlich aus gespeicherten HEGEVA-Daten.",customers:"Kunden",documents:"Dokumente",expenses:"Ausgaben",openTasks:"Offene Aufgaben",invoices:"Rechnungen & Angebote",paid:"Bezahlte Rechnungen",attention:"Aufmerksamkeit nötig",overdueInvoices:"überfällige Rechnungen",overdueTasks:"überfällige Aufgaben",noAttention:"Derzeit ist nichts überfällig.",businessModules:"Business-Arbeitsbereich",aiModules:"KI & App Studio",assistantTitle:"HEGEVA Assistent",assistantDesc:"Praktische mehrsprachige Geschäftshilfe für Ihr Live-Konto.",promptTitle:"Prompt My App",promptDesc:"Verwandeln Sie eine Idee in eine strukturierte App-Spezifikation.",buildTitle:"Build My App X10",buildDesc:"Planen und erstellen Sie eine App in einem geführten Ablauf.",fixTitle:"Fix My App X10",fixDesc:"Prüfen Sie eine bestehende App und erstellen Sie einen Verbesserungsplan."},
  fr:{overview:"Vue en direct de l’espace",overviewDesc:"Un résumé en temps réel calculé uniquement avec les données enregistrées dans HEGEVA.",customers:"Clients",documents:"Documents",expenses:"Dépenses",openTasks:"Tâches ouvertes",invoices:"Factures et devis",paid:"Factures payées",attention:"À surveiller",overdueInvoices:"factures en retard",overdueTasks:"tâches en retard",noAttention:"Aucun élément en retard actuellement.",businessModules:"Espace professionnel",aiModules:"IA et App Studio",assistantTitle:"Assistant HEGEVA",assistantDesc:"Assistance professionnelle multilingue connectée à votre compte actif.",promptTitle:"Prompt My App",promptDesc:"Transformez une idée en spécification d’application structurée.",buildTitle:"Build My App X10",buildDesc:"Planifiez et créez une application avec un parcours guidé.",fixTitle:"Fix My App X10",fixDesc:"Analysez une application existante et préparez un plan d’amélioration."},
  es:{overview:"Resumen del espacio en vivo",overviewDesc:"Un resumen en tiempo real calculado solo con los datos guardados en HEGEVA.",customers:"Clientes",documents:"Documentos",expenses:"Gastos",openTasks:"Tareas abiertas",invoices:"Facturas y presupuestos",paid:"Facturas pagadas",attention:"Requiere atención",overdueInvoices:"facturas vencidas",overdueTasks:"tareas vencidas",noAttention:"No hay elementos vencidos ahora.",businessModules:"Espacio de negocio",aiModules:"IA y App Studio",assistantTitle:"Asistente HEGEVA",assistantDesc:"Ayuda empresarial multilingüe conectada a tu cuenta activa.",promptTitle:"Prompt My App",promptDesc:"Convierte una idea en una especificación de aplicación estructurada.",buildTitle:"Build My App X10",buildDesc:"Planifica y crea una aplicación mediante un flujo guiado.",fixTitle:"Fix My App X10",fixDesc:"Revisa una aplicación existente y crea un plan de mejora."}
}
