import type { Locale } from './dictionaries'

const en = { title:'Contact HEGEVA', subtitle:'Tell us what you need from HEGEVA AI. Your message is saved securely for genuine follow-up; submitting this form does not promise an immediate reply.', name:'Name', email:'Email', company:'Company (optional)', message:'How can HEGEVA help?', placeholder:'Describe your business, what you want to improve, and the result you are looking for.', send:'Send message', sending:'Saving securely…', success:'Thank you. Your message has been securely received.', error:'Your message could not be saved. Check the fields and try again.', privacy:'Only provide information needed for your enquiry. Do not include passwords, API keys, payment details or other secrets.' }
type ContactCopy = typeof en
export const CONTACT_COPY: Record<Locale, ContactCopy> = {
 en,
 hu:{title:'Kapcsolat a HEGEVA-val',subtitle:'Írd meg, mire van szükséged a HEGEVA AI-tól. Az üzenetet biztonságosan mentjük valódi utánkövetéshez; az űrlap elküldése nem ígér azonnali választ.',name:'Név',email:'E-mail',company:'Vállalkozás (nem kötelező)',message:'Miben segíthet a HEGEVA?',placeholder:'Írd le a vállalkozásodat, mit szeretnél fejleszteni, és milyen eredményt vársz.',send:'Üzenet küldése',sending:'Biztonságos mentés…',success:'Köszönjük. Az üzeneted biztonságosan megérkezett.',error:'Az üzenetet nem sikerült elmenteni. Ellenőrizd a mezőket, majd próbáld újra.',privacy:'Csak az érdeklődéshez szükséges adatokat add meg. Ne írj be jelszót, API-kulcsot, fizetési adatot vagy más titkot.'},
 de:{title:'HEGEVA kontaktieren',subtitle:'Teilen Sie uns mit, was Sie von HEGEVA AI benötigen. Ihre Nachricht wird sicher für eine echte Nachverfolgung gespeichert; das Formular verspricht keine sofortige Antwort.',name:'Name',email:'E-Mail',company:'Unternehmen (optional)',message:'Wie kann HEGEVA helfen?',placeholder:'Beschreiben Sie Ihr Unternehmen, was Sie verbessern möchten und welches Ergebnis Sie suchen.',send:'Nachricht senden',sending:'Wird sicher gespeichert…',success:'Vielen Dank. Ihre Nachricht ist sicher eingegangen.',error:'Die Nachricht konnte nicht gespeichert werden. Prüfen Sie die Felder und versuchen Sie es erneut.',privacy:'Geben Sie nur notwendige Informationen an. Keine Passwörter, API-Schlüssel, Zahlungsdaten oder andere Geheimnisse.'},
 fr:{title:'Contacter HEGEVA',subtitle:'Expliquez ce dont vous avez besoin. Votre message est enregistré en toute sécurité pour un suivi réel; ce formulaire ne promet pas une réponse immédiate.',name:'Nom',email:'E-mail',company:'Entreprise (facultatif)',message:'Comment HEGEVA peut-il vous aider ?',placeholder:'Décrivez votre entreprise, ce que vous souhaitez améliorer et le résultat recherché.',send:'Envoyer le message',sending:'Enregistrement sécurisé…',success:'Merci. Votre message a été reçu en toute sécurité.',error:'Le message n’a pas pu être enregistré. Vérifiez les champs et réessayez.',privacy:'Fournissez uniquement les informations nécessaires. N’ajoutez aucun mot de passe, clé API, donnée de paiement ou autre secret.'},
 es:{title:'Contactar con HEGEVA',subtitle:'Cuéntanos qué necesitas de HEGEVA AI. Tu mensaje se guarda de forma segura para un seguimiento real; enviar el formulario no promete una respuesta inmediata.',name:'Nombre',email:'Correo',company:'Empresa (opcional)',message:'¿Cómo puede ayudarte HEGEVA?',placeholder:'Describe tu negocio, qué quieres mejorar y qué resultado buscas.',send:'Enviar mensaje',sending:'Guardando de forma segura…',success:'Gracias. Tu mensaje se ha recibido de forma segura.',error:'No se pudo guardar el mensaje. Comprueba los campos e inténtalo de nuevo.',privacy:'Incluye solo la información necesaria. No añadas contraseñas, claves API, datos de pago ni otros secretos.'}
}
