import type { Locale } from "./dictionaries"

export const LEADS_COPY: Record<Locale, {
  eyebrow:string; title:string; subtitle:string; checking:string; deniedTitle:string; deniedBody:string;
  empty:string; refresh:string; name:string; company:string; received:string; new:string; read:string; closed:string;
  markRead:string; close:string; reopen:string; error:string; inbox:string;
}> = {
  en:{eyebrow:"HEGEVA OWNER",title:"Contact enquiries",subtitle:"Real messages submitted through the HEGEVA contact form.",checking:"Checking owner access…",deniedTitle:"Owner access required",deniedBody:"This private page is available only to the configured HEGEVA owner account.",empty:"No contact enquiries yet.",refresh:"Refresh",name:"Name",company:"Company",received:"Received",new:"New",read:"Read",closed:"Closed",markRead:"Mark as read",close:"Close",reopen:"Reopen",error:"The lead inbox is temporarily unavailable.",inbox:"Lead inbox"},
  hu:{eyebrow:"HEGEVA TULAJDONOS",title:"Kapcsolati érdeklődők",subtitle:"A HEGEVA kapcsolatfelvételi űrlapján beküldött valódi üzenetek.",checking:"Tulajdonosi hozzáférés ellenőrzése…",deniedTitle:"Tulajdonosi hozzáférés szükséges",deniedBody:"Ez a privát oldal csak a beállított HEGEVA-tulajdonosi fiókkal érhető el.",empty:"Még nincs kapcsolati érdeklődő.",refresh:"Frissítés",name:"Név",company:"Vállalkozás",received:"Érkezett",new:"Új",read:"Olvasott",closed:"Lezárt",markRead:"Megjelölés olvasottként",close:"Lezárás",reopen:"Újranyitás",error:"Az érdeklődő-postafiók átmenetileg nem érhető el.",inbox:"Érdeklődők"},
  de:{eyebrow:"HEGEVA INHABER",title:"Kontaktanfragen",subtitle:"Echte Nachrichten aus dem HEGEVA-Kontaktformular.",checking:"Inhaberzugriff wird geprüft…",deniedTitle:"Inhaberzugriff erforderlich",deniedBody:"Diese private Seite ist nur für das konfigurierte HEGEVA-Inhaberkonto verfügbar.",empty:"Noch keine Kontaktanfragen.",refresh:"Aktualisieren",name:"Name",company:"Unternehmen",received:"Eingegangen",new:"Neu",read:"Gelesen",closed:"Geschlossen",markRead:"Als gelesen markieren",close:"Schließen",reopen:"Wieder öffnen",error:"Der Anfrageeingang ist vorübergehend nicht verfügbar.",inbox:"Anfrageeingang"},
  fr:{eyebrow:"PROPRIÉTAIRE HEGEVA",title:"Demandes de contact",subtitle:"Messages réels envoyés via le formulaire de contact HEGEVA.",checking:"Vérification de l’accès propriétaire…",deniedTitle:"Accès propriétaire requis",deniedBody:"Cette page privée est réservée au compte propriétaire HEGEVA configuré.",empty:"Aucune demande de contact.",refresh:"Actualiser",name:"Nom",company:"Entreprise",received:"Reçu",new:"Nouveau",read:"Lu",closed:"Fermé",markRead:"Marquer comme lu",close:"Fermer",reopen:"Rouvrir",error:"La boîte des demandes est temporairement indisponible.",inbox:"Demandes"},
  es:{eyebrow:"PROPIETARIO HEGEVA",title:"Consultas de contacto",subtitle:"Mensajes reales enviados mediante el formulario de contacto de HEGEVA.",checking:"Comprobando acceso del propietario…",deniedTitle:"Se requiere acceso de propietario",deniedBody:"Esta página privada solo está disponible para la cuenta propietaria de HEGEVA configurada.",empty:"Todavía no hay consultas.",refresh:"Actualizar",name:"Nombre",company:"Empresa",received:"Recibido",new:"Nuevo",read:"Leído",closed:"Cerrado",markRead:"Marcar como leído",close:"Cerrar",reopen:"Reabrir",error:"La bandeja de consultas no está disponible temporalmente.",inbox:"Consultas"}
}
