import type { Locale } from "./dictionaries"

type Copy = { eyebrow:string; title:string; subtitle:string; sandbox:string; month:string; current:string; free:string; basic:string; premium:string; pro:string; choose:string; starting:string; signIn:string; opening:string; unavailable:string; secure:string; basicFeatures:string[]; premiumFeatures:string[]; proFeatures:string[] }

export const PRICING_COPY: Record<Locale, Copy> = {
  en:{eyebrow:"HEGEVA PLANS",title:"Choose the right workspace",subtitle:"Start free, then upgrade when you need more monthly AI capacity.",sandbox:"Sandbox testing is active. No real charge will be made.",month:"month",current:"Current plan",free:"Free",basic:"Basic",premium:"Premium",pro:"Pro",choose:"Choose plan",starting:"Opening secure Stripe Checkout…",signIn:"Sign in to continue",opening:"Opening…",unavailable:"Secure checkout is temporarily unavailable.",secure:"Payments are handled securely by Stripe. HEGEVA never stores card details.",basicFeatures:["50 AI messages each month","Prompt My App","Build My App X10 and Fix My App X10 guided beta previews","Business workspace and cloud sync"],premiumFeatures:["300 AI messages each month","Prompt My App","Build My App X10 and Fix My App X10 guided beta access","All working business modules"],proFeatures:["1,000 AI messages each month","Prompt My App","Build My App X10 and Fix My App X10 guided beta access","All working HEGEVA modules"]},
  hu:{eyebrow:"HEGEVA CSOMAGOK",title:"Válaszd ki a megfelelő munkaterületet",subtitle:"Kezdj ingyen, majd válts magasabb csomagra, amikor több havi AI-kapacitásra van szükséged.",sandbox:"A Sandbox tesztelés aktív. Valódi terhelés nem történik.",month:"hó",current:"Jelenlegi csomag",free:"Ingyenes",basic:"Basic",premium:"Premium",pro:"Pro",choose:"Csomag kiválasztása",starting:"Biztonságos Stripe Checkout megnyitása…",signIn:"Jelentkezz be a folytatáshoz",opening:"Megnyitás…",unavailable:"A biztonságos fizetési oldal átmenetileg nem érhető el.",secure:"A fizetést biztonságosan a Stripe kezeli. A HEGEVA nem tárol bankkártyaadatokat.",basicFeatures:["50 AI-üzenet havonta","Prompt My App","Build My App X10 és Fix My App X10 irányított béta előnézet","Üzleti munkaterület és felhőszinkron"],premiumFeatures:["300 AI-üzenet havonta","Prompt My App","Build My App X10 és Fix My App X10 irányított béta hozzáférés","Minden működő üzleti modul"],proFeatures:["1000 AI-üzenet havonta","Prompt My App","Build My App X10 és Fix My App X10 irányított béta hozzáférés","Minden működő HEGEVA modul"]},
  de:{eyebrow:"HEGEVA TARIFE",title:"Wählen Sie den passenden Arbeitsbereich",subtitle:"Starten Sie kostenlos und wechseln Sie bei höherem KI-Bedarf den Tarif.",sandbox:"Der Sandbox-Test ist aktiv. Es erfolgt keine echte Belastung.",month:"Monat",current:"Aktueller Tarif",free:"Kostenlos",basic:"Basic",premium:"Premium",pro:"Pro",choose:"Tarif wählen",starting:"Sicherer Stripe Checkout wird geöffnet…",signIn:"Zum Fortfahren anmelden",opening:"Wird geöffnet…",unavailable:"Der sichere Checkout ist vorübergehend nicht verfügbar.",secure:"Zahlungen werden sicher von Stripe verarbeitet. HEGEVA speichert keine Kartendaten.",basicFeatures:["50 KI-Nachrichten pro Monat","Prompt My App","Geführte Beta-Vorschau von Build My App X10 und Fix My App X10","Business-Arbeitsbereich und Cloud-Synchronisierung"],premiumFeatures:["300 KI-Nachrichten pro Monat","Prompt My App","Geführter Beta-Zugang zu Build My App X10 und Fix My App X10","Alle aktiven Business-Module"],proFeatures:["1.000 KI-Nachrichten pro Monat","Prompt My App","Geführter Beta-Zugang zu Build My App X10 und Fix My App X10","Alle aktiven HEGEVA-Module"]},
  fr:{eyebrow:"OFFRES HEGEVA",title:"Choisissez l’espace adapté",subtitle:"Commencez gratuitement, puis augmentez votre capacité IA selon vos besoins.",sandbox:"Le test Sandbox est actif. Aucun débit réel ne sera effectué.",month:"mois",current:"Offre actuelle",free:"Gratuit",basic:"Basic",premium:"Premium",pro:"Pro",choose:"Choisir l’offre",starting:"Ouverture du paiement sécurisé Stripe…",signIn:"Connectez-vous pour continuer",opening:"Ouverture…",unavailable:"Le paiement sécurisé est temporairement indisponible.",secure:"Les paiements sont traités en toute sécurité par Stripe. HEGEVA ne stocke aucune donnée de carte.",basicFeatures:["50 messages IA par mois","Prompt My App","Aperçu bêta guidé de Build My App X10 et Fix My App X10","Espace professionnel et synchronisation cloud"],premiumFeatures:["300 messages IA par mois","Prompt My App","Accès bêta guidé à Build My App X10 et Fix My App X10","Tous les modules professionnels actifs"],proFeatures:["1 000 messages IA par mois","Prompt My App","Accès bêta guidé à Build My App X10 et Fix My App X10","Tous les modules HEGEVA actifs"]},
  es:{eyebrow:"PLANES HEGEVA",title:"Elige el espacio adecuado",subtitle:"Empieza gratis y amplía tu capacidad mensual de IA cuando lo necesites.",sandbox:"La prueba Sandbox está activa. No se realizará ningún cargo real.",month:"mes",current:"Plan actual",free:"Gratis",basic:"Basic",premium:"Premium",pro:"Pro",choose:"Elegir plan",starting:"Abriendo Stripe Checkout seguro…",signIn:"Inicia sesión para continuar",opening:"Abriendo…",unavailable:"El pago seguro no está disponible temporalmente.",secure:"Stripe procesa los pagos de forma segura. HEGEVA no almacena datos de tarjetas.",basicFeatures:["50 mensajes de IA al mes","Prompt My App","Vista previa beta guiada de Build My App X10 y Fix My App X10","Espacio de negocio y sincronización"],premiumFeatures:["300 mensajes de IA al mes","Prompt My App","Acceso beta guiado a Build My App X10 y Fix My App X10","Todos los módulos activos"],proFeatures:["1.000 mensajes de IA al mes","Prompt My App","Acceso beta guiado a Build My App X10 y Fix My App X10","Todos los módulos HEGEVA activos"]},
}
