import type { Locale } from "./dictionaries"

type Copy = { eyebrow:string; title:string; subtitle:string; sandbox:string; month:string; current:string; free:string; basic:string; premium:string; pro:string; choose:string; starting:string; signIn:string; opening:string; unavailable:string; secure:string; basicFeatures:string[]; premiumFeatures:string[]; proFeatures:string[] }

export const PRICING_COPY: Record<Locale, Copy> = {
  en:{eyebrow:"HEGEVA PLANS",title:"Choose the right workspace",subtitle:"Start free, then upgrade when you need more monthly AI capacity.",sandbox:"Sandbox testing is active. No real charge will be made.",month:"month",current:"Current plan",free:"Free",basic:"Basic",premium:"Premium",pro:"Pro",choose:"Choose plan",starting:"Opening secure Stripe Checkout…",signIn:"Sign in to continue",opening:"Opening…",unavailable:"Secure checkout is temporarily unavailable.",secure:"Payments are handled securely by Stripe. HEGEVA never stores card details.",basicFeatures:["50 AI messages each month","Business workspace and tools","Cloud-synced account data"],premiumFeatures:["300 AI messages each month","All working business modules","Priority product updates"],proFeatures:["1,000 AI messages each month","Highest monthly AI capacity","All working HEGEVA modules"]},
  hu:{eyebrow:"HEGEVA CSOMAGOK",title:"Válaszd ki a megfelelő munkaterületet",subtitle:"Kezdj ingyen, majd válts magasabb csomagra, amikor több havi AI-kapacitásra van szükséged.",sandbox:"A Sandbox tesztelés aktív. Valódi terhelés nem történik.",month:"hó",current:"Jelenlegi csomag",free:"Ingyenes",basic:"Basic",premium:"Premium",pro:"Pro",choose:"Csomag kiválasztása",starting:"Biztonságos Stripe Checkout megnyitása…",signIn:"Jelentkezz be a folytatáshoz",opening:"Megnyitás…",unavailable:"A biztonságos fizetési oldal átmenetileg nem érhető el.",secure:"A fizetést biztonságosan a Stripe kezeli. A HEGEVA nem tárol bankkártyaadatokat.",basicFeatures:["50 AI-üzenet havonta","Üzleti munkaterület és eszközök","Felhőbe szinkronizált fiókadatok"],premiumFeatures:["300 AI-üzenet havonta","Minden működő üzleti modul","Elsőbbségi termékfrissítések"],proFeatures:["1000 AI-üzenet havonta","Legmagasabb havi AI-kapacitás","Minden működő HEGEVA modul"]},
  de:{eyebrow:"HEGEVA TARIFE",title:"Wählen Sie den passenden Arbeitsbereich",subtitle:"Starten Sie kostenlos und wechseln Sie bei höherem KI-Bedarf den Tarif.",sandbox:"Der Sandbox-Test ist aktiv. Es erfolgt keine echte Belastung.",month:"Monat",current:"Aktueller Tarif",free:"Kostenlos",basic:"Basic",premium:"Premium",pro:"Pro",choose:"Tarif wählen",starting:"Sicherer Stripe Checkout wird geöffnet…",signIn:"Zum Fortfahren anmelden",opening:"Wird geöffnet…",unavailable:"Der sichere Checkout ist vorübergehend nicht verfügbar.",secure:"Zahlungen werden sicher von Stripe verarbeitet. HEGEVA speichert keine Kartendaten.",basicFeatures:["50 KI-Nachrichten pro Monat","Business-Arbeitsbereich und Tools","Cloud-synchronisierte Kontodaten"],premiumFeatures:["300 KI-Nachrichten pro Monat","Alle aktiven Business-Module","Bevorzugte Produktupdates"],proFeatures:["1.000 KI-Nachrichten pro Monat","Höchste monatliche KI-Kapazität","Alle aktiven HEGEVA-Module"]},
  fr:{eyebrow:"OFFRES HEGEVA",title:"Choisissez l’espace adapté",subtitle:"Commencez gratuitement, puis augmentez votre capacité IA selon vos besoins.",sandbox:"Le test Sandbox est actif. Aucun débit réel ne sera effectué.",month:"mois",current:"Offre actuelle",free:"Gratuit",basic:"Basic",premium:"Premium",pro:"Pro",choose:"Choisir l’offre",starting:"Ouverture du paiement sécurisé Stripe…",signIn:"Connectez-vous pour continuer",opening:"Ouverture…",unavailable:"Le paiement sécurisé est temporairement indisponible.",secure:"Les paiements sont traités en toute sécurité par Stripe. HEGEVA ne stocke aucune donnée de carte.",basicFeatures:["50 messages IA par mois","Espace professionnel et outils","Données de compte synchronisées"],premiumFeatures:["300 messages IA par mois","Tous les modules professionnels actifs","Mises à jour prioritaires"],proFeatures:["1 000 messages IA par mois","Capacité IA mensuelle maximale","Tous les modules HEGEVA actifs"]},
  es:{eyebrow:"PLANES HEGEVA",title:"Elige el espacio adecuado",subtitle:"Empieza gratis y amplía tu capacidad mensual de IA cuando lo necesites.",sandbox:"La prueba Sandbox está activa. No se realizará ningún cargo real.",month:"mes",current:"Plan actual",free:"Gratis",basic:"Basic",premium:"Premium",pro:"Pro",choose:"Elegir plan",starting:"Abriendo Stripe Checkout seguro…",signIn:"Inicia sesión para continuar",opening:"Abriendo…",unavailable:"El pago seguro no está disponible temporalmente.",secure:"Stripe procesa los pagos de forma segura. HEGEVA no almacena datos de tarjetas.",basicFeatures:["50 mensajes de IA al mes","Espacio de negocio y herramientas","Datos de cuenta sincronizados"],premiumFeatures:["300 mensajes de IA al mes","Todos los módulos activos","Actualizaciones prioritarias"],proFeatures:["1.000 mensajes de IA al mes","Máxima capacidad mensual de IA","Todos los módulos HEGEVA activos"]},
}
