import type { Locale } from "./dictionaries"

export const TOOLS_COPY: Record<Locale, {
  eyebrow:string; title:string; subtitle:string; currency:string; revenue:string; costs:string; profit:string; margin:string;
  profitTitle:string; profitDesc:string; pricingTitle:string; pricingDesc:string; unitCost:string; targetMargin:string; sellingPrice:string; unitProfit:string;
  vatTitle:string; vatDesc:string; net:string; vatRate:string; vat:string; gross:string;
  breakEvenTitle:string; breakEvenDesc:string; fixedCosts:string; variableCost:string; price:string; units:string;
  invalid:string; note:string; moduleTitle:string; moduleDesc:string;
}> = {
 en:{eyebrow:"HEGEVA BUSINESS TOOLS",title:"Business calculators",subtitle:"Fast calculations based only on the numbers you enter.",currency:"Currency",revenue:"Revenue",costs:"Total costs",profit:"Profit",margin:"Profit margin",profitTitle:"Profit & margin",profitDesc:"See the difference between revenue and real costs.",pricingTitle:"Target-margin pricing",pricingDesc:"Calculate the selling price needed for your target margin.",unitCost:"Cost per unit",targetMargin:"Target margin",sellingPrice:"Suggested selling price",unitProfit:"Profit per unit",vatTitle:"VAT calculator",vatDesc:"Calculate net, VAT and gross values using your selected rate.",net:"Net amount",vatRate:"VAT rate",vat:"VAT amount",gross:"Gross amount",breakEvenTitle:"Break-even point",breakEvenDesc:"Estimate how many units cover your fixed costs.",fixedCosts:"Fixed costs",variableCost:"Variable cost per unit",price:"Selling price per unit",units:"Units to break even",invalid:"Enter valid numbers to calculate.",note:"Calculations are estimates, not accounting, tax or financial advice. Check important figures with a qualified professional.",moduleTitle:"Business Tools",moduleDesc:"Profit, margin, VAT, pricing and break-even calculators."},
 hu:{eyebrow:"HEGEVA ÜZLETI ESZKÖZÖK",title:"Üzleti kalkulátorok",subtitle:"Gyors számítások kizárólag az általad megadott számok alapján.",currency:"Pénznem",revenue:"Bevétel",costs:"Összes költség",profit:"Nyereség",margin:"Nyereséghányad",profitTitle:"Nyereség és árrés",profitDesc:"Lásd a bevétel és a valódi költségek különbségét.",pricingTitle:"Célárréses árazás",pricingDesc:"Számítsd ki a kívánt árréshez szükséges eladási árat.",unitCost:"Egységköltség",targetMargin:"Célárrés",sellingPrice:"Javasolt eladási ár",unitProfit:"Egységenkénti nyereség",vatTitle:"ÁFA-kalkulátor",vatDesc:"Nettó, ÁFA és bruttó érték számítása a választott kulccsal.",net:"Nettó összeg",vatRate:"ÁFA-kulcs",vat:"ÁFA összege",gross:"Bruttó összeg",breakEvenTitle:"Fedezeti pont",breakEvenDesc:"Becsüld meg, hány egység fedezi a fix költségeket.",fixedCosts:"Fix költségek",variableCost:"Változó költség egységenként",price:"Eladási ár egységenként",units:"Fedezethez szükséges egységek",invalid:"Adj meg érvényes számokat a számításhoz.",note:"A számítások becslések, nem minősülnek könyvelési, adózási vagy pénzügyi tanácsnak. A fontos adatokat ellenőriztesd képzett szakemberrel.",moduleTitle:"Üzleti eszközök",moduleDesc:"Nyereség-, árrés-, ÁFA-, árazási és fedezetipont-kalkulátorok."},
 de:{eyebrow:"HEGEVA BUSINESS-TOOLS",title:"Unternehmensrechner",subtitle:"Schnelle Berechnungen ausschließlich mit den von Ihnen eingegebenen Zahlen.",currency:"Währung",revenue:"Umsatz",costs:"Gesamtkosten",profit:"Gewinn",margin:"Gewinnmarge",profitTitle:"Gewinn & Marge",profitDesc:"Zeigt die Differenz zwischen Umsatz und tatsächlichen Kosten.",pricingTitle:"Zielmargen-Preis",pricingDesc:"Berechnet den nötigen Verkaufspreis für Ihre Zielmarge.",unitCost:"Stückkosten",targetMargin:"Zielmarge",sellingPrice:"Empfohlener Verkaufspreis",unitProfit:"Gewinn pro Einheit",vatTitle:"MwSt.-Rechner",vatDesc:"Netto-, Steuer- und Bruttowerte mit dem gewählten Satz berechnen.",net:"Nettobetrag",vatRate:"MwSt.-Satz",vat:"MwSt.-Betrag",gross:"Bruttobetrag",breakEvenTitle:"Gewinnschwelle",breakEvenDesc:"Schätzt, wie viele Einheiten die Fixkosten decken.",fixedCosts:"Fixkosten",variableCost:"Variable Kosten pro Einheit",price:"Verkaufspreis pro Einheit",units:"Einheiten bis zur Gewinnschwelle",invalid:"Geben Sie gültige Zahlen ein.",note:"Berechnungen sind Schätzungen und keine Buchhaltungs-, Steuer- oder Finanzberatung. Lassen Sie wichtige Zahlen fachlich prüfen.",moduleTitle:"Business-Tools",moduleDesc:"Rechner für Gewinn, Marge, MwSt., Preise und Gewinnschwelle."},
 fr:{eyebrow:"OUTILS PROFESSIONNELS HEGEVA",title:"Calculateurs d’entreprise",subtitle:"Calculs rapides basés uniquement sur les chiffres que vous saisissez.",currency:"Devise",revenue:"Chiffre d’affaires",costs:"Coûts totaux",profit:"Bénéfice",margin:"Marge bénéficiaire",profitTitle:"Bénéfice et marge",profitDesc:"Affiche la différence entre revenus et coûts réels.",pricingTitle:"Prix avec marge cible",pricingDesc:"Calcule le prix de vente nécessaire pour votre marge cible.",unitCost:"Coût unitaire",targetMargin:"Marge cible",sellingPrice:"Prix de vente suggéré",unitProfit:"Bénéfice unitaire",vatTitle:"Calculateur de TVA",vatDesc:"Calcule les montants net, TVA et brut au taux choisi.",net:"Montant net",vatRate:"Taux de TVA",vat:"Montant de TVA",gross:"Montant brut",breakEvenTitle:"Seuil de rentabilité",breakEvenDesc:"Estime le nombre d’unités couvrant les coûts fixes.",fixedCosts:"Coûts fixes",variableCost:"Coût variable unitaire",price:"Prix de vente unitaire",units:"Unités pour atteindre le seuil",invalid:"Saisissez des nombres valides.",note:"Ces calculs sont des estimations, pas des conseils comptables, fiscaux ou financiers. Faites vérifier les chiffres importants par un professionnel qualifié.",moduleTitle:"Outils professionnels",moduleDesc:"Calculateurs de bénéfice, marge, TVA, prix et seuil de rentabilité."},
 es:{eyebrow:"HERRAMIENTAS HEGEVA",title:"Calculadoras empresariales",subtitle:"Cálculos rápidos basados únicamente en los números que introduces.",currency:"Moneda",revenue:"Ingresos",costs:"Costes totales",profit:"Beneficio",margin:"Margen de beneficio",profitTitle:"Beneficio y margen",profitDesc:"Muestra la diferencia entre ingresos y costes reales.",pricingTitle:"Precio con margen objetivo",pricingDesc:"Calcula el precio de venta necesario para tu margen objetivo.",unitCost:"Coste por unidad",targetMargin:"Margen objetivo",sellingPrice:"Precio de venta sugerido",unitProfit:"Beneficio por unidad",vatTitle:"Calculadora de IVA",vatDesc:"Calcula importes netos, IVA y brutos con la tasa elegida.",net:"Importe neto",vatRate:"Tasa de IVA",vat:"Importe de IVA",gross:"Importe bruto",breakEvenTitle:"Punto de equilibrio",breakEvenDesc:"Estima cuántas unidades cubren los costes fijos.",fixedCosts:"Costes fijos",variableCost:"Coste variable por unidad",price:"Precio de venta por unidad",units:"Unidades para alcanzar el equilibrio",invalid:"Introduce números válidos.",note:"Los cálculos son estimaciones, no asesoramiento contable, fiscal ni financiero. Verifica las cifras importantes con un profesional cualificado.",moduleTitle:"Herramientas empresariales",moduleDesc:"Calculadoras de beneficio, margen, IVA, precios y punto de equilibrio."}
}
