import type { Locale } from "./dictionaries"
export const VAULT_COPY: Record<Locale, {
 eyebrow:string;title:string;subtitle:string;cloud:string;local:string;saving:string;syncError:string;
 add:string;templateTitle:string;category:string;content:string;save:string;search:string;empty:string;copy:string;copied:string;remove:string;
 moduleTitle:string;moduleDesc:string;note:string;
}> = {
 en:{eyebrow:"HEGEVA VAULT",title:"Vault & templates",subtitle:"Create, search and reuse your own business text templates.",cloud:"Cloud synced to your authenticated workspace.",local:"Stored only in this browser until you sign in.",saving:"Saving templates…",syncError:"Cloud sync is temporarily unavailable; a browser copy remains.",add:"Create template",templateTitle:"Template title",category:"Category",content:"Template content",save:"Save template",search:"Search templates",empty:"No templates saved yet. HEGEVA does not insert fake business documents.",copy:"Copy",copied:"Copied",remove:"Delete",moduleTitle:"Vault & Templates",moduleDesc:"Create and cloud-sync reusable business text templates.",note:"Templates are your working drafts. Review legal, tax or contractual text with a qualified professional before use."},
 hu:{eyebrow:"HEGEVA SZÉF",title:"Széf és sablonok",subtitle:"Saját üzleti szövegsablonok létrehozása, keresése és újrafelhasználása.",cloud:"Hitelesített munkaterületeddel felhőbe szinkronizálva.",local:"Bejelentkezésig csak ebben a böngészőben tárolva.",saving:"Sablonok mentése…",syncError:"A felhőszinkron átmenetileg nem érhető el; a böngészőmásolat megmarad.",add:"Sablon létrehozása",templateTitle:"Sablon címe",category:"Kategória",content:"Sablon tartalma",save:"Sablon mentése",search:"Keresés a sablonok között",empty:"Még nincs mentett sablon. A HEGEVA nem illeszt be kitalált üzleti dokumentumokat.",copy:"Másolás",copied:"Másolva",remove:"Törlés",moduleTitle:"Széf és sablonok",moduleDesc:"Újrafelhasználható üzleti szövegsablonok létrehozása és felhőszinkronja.",note:"A sablonok munkavázlatok. A jogi, adózási vagy szerződéses szöveget használat előtt ellenőriztesd képzett szakemberrel."},
 de:{eyebrow:"HEGEVA TRESOR",title:"Tresor & Vorlagen",subtitle:"Eigene Geschäftstextvorlagen erstellen, durchsuchen und wiederverwenden.",cloud:"Mit Ihrem authentifizierten Cloud-Arbeitsbereich synchronisiert.",local:"Bis zur Anmeldung nur in diesem Browser gespeichert.",saving:"Vorlagen werden gespeichert…",syncError:"Cloud-Synchronisierung vorübergehend nicht verfügbar; eine Browserkopie bleibt erhalten.",add:"Vorlage erstellen",templateTitle:"Vorlagentitel",category:"Kategorie",content:"Vorlageninhalt",save:"Vorlage speichern",search:"Vorlagen durchsuchen",empty:"Noch keine Vorlagen gespeichert. HEGEVA fügt keine erfundenen Geschäftsdokumente ein.",copy:"Kopieren",copied:"Kopiert",remove:"Löschen",moduleTitle:"Tresor & Vorlagen",moduleDesc:"Wiederverwendbare Geschäftstextvorlagen erstellen und synchronisieren.",note:"Vorlagen sind Arbeitsentwürfe. Lassen Sie rechtliche, steuerliche oder vertragliche Texte vor der Verwendung fachlich prüfen."},
 fr:{eyebrow:"COFFRE HEGEVA",title:"Coffre et modèles",subtitle:"Créez, recherchez et réutilisez vos propres modèles de textes professionnels.",cloud:"Synchronisé avec votre espace de travail cloud authentifié.",local:"Stocké uniquement dans ce navigateur jusqu’à votre connexion.",saving:"Enregistrement des modèles…",syncError:"Synchronisation cloud temporairement indisponible ; une copie navigateur reste disponible.",add:"Créer un modèle",templateTitle:"Titre du modèle",category:"Catégorie",content:"Contenu du modèle",save:"Enregistrer le modèle",search:"Rechercher des modèles",empty:"Aucun modèle enregistré. HEGEVA n’insère pas de faux documents professionnels.",copy:"Copier",copied:"Copié",remove:"Supprimer",moduleTitle:"Coffre et modèles",moduleDesc:"Créez et synchronisez des modèles de textes professionnels réutilisables.",note:"Les modèles sont des brouillons. Faites vérifier les textes juridiques, fiscaux ou contractuels par un professionnel qualifié."},
 es:{eyebrow:"BÓVEDA HEGEVA",title:"Bóveda y plantillas",subtitle:"Crea, busca y reutiliza tus propias plantillas de texto empresarial.",cloud:"Sincronizado con tu espacio de trabajo autenticado.",local:"Guardado solo en este navegador hasta que inicies sesión.",saving:"Guardando plantillas…",syncError:"La sincronización en la nube no está disponible temporalmente; se conserva una copia local.",add:"Crear plantilla",templateTitle:"Título de la plantilla",category:"Categoría",content:"Contenido de la plantilla",save:"Guardar plantilla",search:"Buscar plantillas",empty:"Todavía no hay plantillas guardadas. HEGEVA no inserta documentos empresariales falsos.",copy:"Copiar",copied:"Copiado",remove:"Eliminar",moduleTitle:"Bóveda y plantillas",moduleDesc:"Crea y sincroniza plantillas de texto empresarial reutilizables.",note:"Las plantillas son borradores de trabajo. Revisa textos legales, fiscales o contractuales con un profesional cualificado."}
}
