const idPattern=/^[A-Za-z0-9_-]{1,100}$/;
const tokenPattern=/^[A-Za-z0-9_-]{40,60}$/;
const json=row=>{try{const value=JSON.parse(row?.data||"[]");return Array.isArray(value)?value:[]}catch{return[]}};
const text=(value,max=200)=>typeof value==="string"?value.trim().slice(0,max):"";
const amount=value=>{const number=Number(value);return Number.isFinite(number)&&number>=0?Math.min(number,1000000000000):0};
async function hash(value){const data=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(data)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function token(){const bytes=crypto.getRandomValues(new Uint8Array(32));return btoa(String.fromCharCode(...bytes)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
function publicDocument(document){const documentType=document?.type==="invoice"||document?.type==="quote"?document.type:null,reference=text(document?.number,50);if(!documentType||!reference)return null;const items=Array.isArray(document.items)?document.items.map(item=>{const quantity=amount(item?.quantity),unitPrice=amount(item?.unitPrice);return{description:text(item?.description,500),quantity,unitPrice,lineTotal:quantity*unitPrice}}):[],subtotal=items.reduce((sum,item)=>sum+item.lineTotal,0),vatRate=Math.min(amount(document.vatRate),100),vatAmount=subtotal*vatRate/100;return{documentType,reference,issueDate:text(document.issueDate,20),dueDate:text(document.dueDate,20),currency:text(document.currency,8)||"GBP",business:{name:text(document.businessName,200)},customer:{name:text(document.clientName,200)},items,subtotal,vatRate,vatAmount,total:subtotal+vatAmount}}
function publicSnapshot(customer,documents){return{schemaVersion:2,customer:{name:text(customer?.title,200)},documents}}
async function selectedSnapshot(db,userId,body){const customerId=String(body?.customerId||""),invoiceIds=Array.isArray(body?.invoiceIds)?body.invoiceIds.map(String).slice(0,20):[];if(!idPattern.test(customerId)||invoiceIds.some(id=>!idPattern.test(id)))return{error:"Invalid portal selection.",status:400};const rows=await db.prepare("SELECT dataType,data FROM workspace_data WHERE userId=?1 AND dataType IN ('customers','invoice_documents')").bind(userId).all(),customerRow=rows.results?.find(row=>row.dataType==="customers"),invoiceRow=rows.results?.find(row=>row.dataType==="invoice_documents"),customer=json(customerRow).find(item=>item?.id===customerId);if(!customer)return{error:"Customer not found.",status:404};const documents=json(invoiceRow).filter(item=>invoiceIds.includes(String(item?.id))&&text(item?.clientName)===text(customer.title)).map(publicDocument).filter(Boolean);return{snapshot:publicSnapshot(customer,documents)}}
function v2Snapshot(snapshot){if(!snapshot||typeof snapshot!=="object"||!Array.isArray(snapshot.documents))return null;const documents=snapshot.documents.map(item=>publicDocument({type:item?.documentType,number:item?.reference,issueDate:item?.issueDate,dueDate:item?.dueDate,currency:item?.currency,businessName:item?.business?.name,clientName:item?.customer?.name,vatRate:item?.vatRate,items:item?.items})).filter(Boolean);return publicSnapshot({title:snapshot.customer?.name},documents)}
function legacySnapshot(snapshot){const customer=snapshot&&typeof snapshot==="object"?snapshot.customer:null,invoices=Array.isArray(snapshot?.invoices)?snapshot.invoices:[];return{schemaVersion:1,customer:{name:text(customer?.title,200)},documents:invoices.map(item=>({documentType:item?.type==="quote"?"quote":"invoice",reference:text(item?.number,50),issueDate:text(item?.issueDate,20),dueDate:text(item?.dueDate,20)}))}}
export async function createPortalShare(db,userId,body){const selection=await selectedSnapshot(db,userId,body);if(selection.error)return selection;const days=Math.min(30,Math.max(1,Number(body?.expiresInDays)||7)),raw=token(),now=new Date(),expires=new Date(now.getTime()+days*86400000),id=crypto.randomUUID();await db.prepare("INSERT INTO client_portal_shares(id,userId,tokenHash,snapshot,expiresAt,createdAt) VALUES(?1,?2,?3,?4,?5,?6)").bind(id,userId,await hash(raw),JSON.stringify(selection.snapshot),expires.toISOString(),now.toISOString()).run();return{status:201,data:{token:raw,expiresAt:expires.toISOString(),invoiceCount:selection.snapshot.documents.length}}}
export async function previewPortalShare(db,userId,body){const selection=await selectedSnapshot(db,userId,body);return selection.error?selection:{status:200,data:selection.snapshot}}
export async function readPortalShare(db,raw){if(!tokenPattern.test(raw))return{status:404,error:"Portal not found."};const row=await db.prepare("SELECT snapshot,expiresAt,revokedAt FROM client_portal_shares WHERE tokenHash=?1 LIMIT 1").bind(await hash(raw)).first();if(!row||row.revokedAt||row.expiresAt<=new Date().toISOString())return{status:404,error:"Portal not found."};try{const snapshot=JSON.parse(row.snapshot),data=snapshot?.schemaVersion===2?v2Snapshot(snapshot):legacySnapshot(snapshot);return data?{status:200,data}:{status:404,error:"Portal not found."}}catch{return{status:404,error:"Portal not found."}}}
export async function revokePortalShare(db,userId,id){if(!idPattern.test(id))return{status:400,error:"Invalid share."};const result=await db.prepare("UPDATE client_portal_shares SET revokedAt=?1 WHERE id=?2 AND userId=?3 AND revokedAt IS NULL").bind(new Date().toISOString(),id,userId).run();return result.meta?.changes?{status:200,data:{revoked:true}}:{status:404,error:"Share not found."}}
