"use client"
import { useEffect, useMemo, useState } from "react"
import { AppShell } from "@/components/app-shell"
import { PageHeader } from "@/components/page-header"
import { useI18n } from "@/lib/i18n/provider"
import { useWorkspaceData } from "@/lib/use-workspace-data"
import { INVOICE_COPY } from "@/lib/i18n/invoice-copy"
type Item={id:string;description:string;quantity:number;unitPrice:number}
type Customer={id:string;title:string;meta?:string;notes?:string;createdAt:string}
type BusinessProfile={id:string;name:string;details:string;updatedAt:string}
type DocStatus="draft"|"sent"|"paid"
type Doc={id:string;type:"invoice"|"quote";status?:DocStatus;number:string;issueDate:string;dueDate:string;currency:string;vatRate:number;businessName:string;businessDetails:string;clientName:string;clientDetails:string;items:Item[];notes:string;createdAt:string;updatedAt:string}
const today=()=>new Date().toISOString().slice(0,10)
const plusDays=(days:number)=>{const date=new Date();date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
const nextNumber=(type:Doc["type"],docs:Doc[])=>{const year=new Date().getUTCFullYear();const prefix=type==="invoice"?"INV":"QUO";const used=docs.filter((item)=>item.type===type&&item.number.startsWith(`${prefix}-${year}-`)).length+1;return `${prefix}-${year}-${String(used).padStart(3,"0")}`}
const blank=(type:Doc["type"]="invoice",docs:Doc[]=[]):Doc=>({id:"draft",type,status:"draft",number:nextNumber(type,docs),issueDate:today(),dueDate:plusDays(14),currency:"GBP",vatRate:20,businessName:"",businessDetails:"",clientName:"",clientDetails:"",items:[{id:"item-1",description:"",quantity:1,unitPrice:0}],notes:"",createdAt:"",updatedAt:""})
const esc=(v:string)=>v.replace(/[&<>"']/g,(ch)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]||ch))
export default function InvoicePage(){
 const {locale}=useI18n();const c=INVOICE_COPY[locale];const {items:docs,setItems:setDocs,syncState}=useWorkspaceData<Doc>("invoice_documents");const {items:customers}=useWorkspaceData<Customer>("customers");const {items:profiles,setItems:setProfiles}=useWorkspaceData<BusinessProfile>("business_profile");const [doc,setDoc]=useState<Doc>(()=>blank());const [filter,setFilter]=useState<"all"|DocStatus|"overdue">("all")
 useEffect(()=>{const profile=profiles[0];if(profile&&doc.id==="draft"&&!doc.businessName){setDoc((current)=>({...current,businessName:profile.name,businessDetails:profile.details}))}},[profiles,doc.id,doc.businessName])
 useEffect(()=>{if(doc.id==="draft"&&docs.some((item)=>item.number===doc.number)){setDoc((current)=>({...current,number:nextNumber(current.type,docs)}))}},[docs,doc.id,doc.number])
 const symbol=({GBP:"£",EUR:"€",USD:"$",HUF:"Ft"} as Record<string,string>)[doc.currency]||doc.currency
 const totals=useMemo(()=>{const subtotal=doc.items.reduce((sum,item)=>sum+(Number(item.quantity)||0)*(Number(item.unitPrice)||0),0);const vat=subtotal*(Number(doc.vatRate)||0)/100;return{subtotal,vat,total:subtotal+vat}},[doc.items,doc.vatRate])
 const statusOf=(item:Doc):DocStatus|"overdue"=>item.status!=="paid"&&item.type==="invoice"&&Boolean(item.dueDate)&&item.dueDate<today()?"overdue":item.status||"draft"
 const visibleDocs=useMemo(()=>filter==="all"?docs:docs.filter((item)=>statusOf(item)===filter),[docs,filter])
 const counts=useMemo(()=>({all:docs.length,draft:docs.filter((item)=>statusOf(item)==="draft").length,sent:docs.filter((item)=>statusOf(item)==="sent").length,paid:docs.filter((item)=>statusOf(item)==="paid").length,overdue:docs.filter((item)=>statusOf(item)==="overdue").length}),[docs])
 const statusLabel=(status:DocStatus|"overdue")=>({draft:c.statusDraft,sent:c.statusSent,paid:c.statusPaid,overdue:c.statusOverdue})[status]
 const money=(n:number)=>`${symbol}${n.toLocaleString(locale,{minimumFractionDigits:2,maximumFractionDigits:2})}`
 const set=(patch:Partial<Doc>)=>setDoc((current)=>({...current,...patch,updatedAt:new Date().toISOString()}))
 const updateItem=(id:string,patch:Partial<Item>)=>set({items:doc.items.map((item)=>item.id===id?{...item,...patch}:item)})
 function save(){if(!doc.businessName.trim()||!doc.clientName.trim()||!doc.number.trim())return;const now=new Date().toISOString();const stored={...doc,id:doc.id==="draft"?crypto.randomUUID():doc.id,createdAt:doc.createdAt||now,updatedAt:now};setDoc(stored);setDocs((current)=>[stored,...current.filter((item)=>item.id!==stored.id)].slice(0,200));setProfiles([{id:profiles[0]?.id||crypto.randomUUID(),name:doc.businessName.trim(),details:doc.businessDetails.trim(),updatedAt:now}])}
 function chooseCustomer(id:string){const customer=customers.find((item)=>item.id===id);if(customer)set({clientName:customer.title,clientDetails:[customer.meta,customer.notes].filter(Boolean).join("\n")})}
 function newDocument(){const fresh=blank(doc.type,docs);const profile=profiles[0];setDoc(profile?{...fresh,businessName:profile.name,businessDetails:profile.details}:fresh)}
 function print(){const rows=doc.items.map((item)=>`<tr><td>${esc(item.description)}</td><td>${item.quantity}</td><td>${money(item.unitPrice)}</td><td>${money(item.quantity*item.unitPrice)}</td></tr>`).join("");const w=window.open("","_blank");if(!w)return;w.opener=null;w.document.write(`<!doctype html><html><head><title>${esc(doc.number)}</title><style>body{font-family:Arial,sans-serif;color:#17201c;padding:36px;max-width:900px;margin:auto}h1{font-size:30px}header,.meta{display:flex;justify-content:space-between;gap:30px}.box{white-space:pre-wrap;line-height:1.55}table{width:100%;border-collapse:collapse;margin-top:30px}th,td{padding:12px;border-bottom:1px solid #ccd5cf;text-align:left}th{background:#eff5f1}.totals{margin:25px 0 0 auto;width:300px}.totals p{display:flex;justify-content:space-between}.grand{font-size:20px;font-weight:bold;border-top:2px solid #17201c;padding-top:12px}.notes{margin-top:35px;white-space:pre-wrap}@media print{body{padding:0}}</style></head><body><header><div><h1>${esc(doc.type==="invoice"?c.invoice:c.quote)}</h1><strong>${esc(doc.number)}</strong></div><div class="box"><strong>${esc(doc.businessName)}</strong><br>${esc(doc.businessDetails)}</div></header><div class="meta"><p>${c.issueDate}: ${esc(doc.issueDate)}<br>${c.dueDate}: ${esc(doc.dueDate)}</p><div class="box"><strong>${c.client}</strong><br>${esc(doc.clientName)}<br>${esc(doc.clientDetails)}</div></div><table><thead><tr><th>${c.description}</th><th>${c.quantity}</th><th>${c.unitPrice}</th><th>${c.total}</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><p><span>${c.subtotal}</span><strong>${money(totals.subtotal)}</strong></p><p><span>${c.vat} (${doc.vatRate}%)</span><strong>${money(totals.vat)}</strong></p><p class="grand"><span>${c.total}</span><strong>${money(totals.total)}</strong></p></div><div class="notes">${esc(doc.notes)}</div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
 const input="mt-2 w-full rounded-xl border border-input bg-input/30 px-3.5 py-3 outline-none focus:border-primary/50"
 const syncText=syncState==="cloud"?c.syncCloud:syncState==="saving"?c.syncSaving:syncState==="error"?c.syncError:c.syncLocal
 return <AppShell><main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><PageHeader eyebrow={c.eyebrow} title={c.title} subtitle={c.subtitle}/><p className="mt-6 rounded-xl border border-border bg-card/60 p-3 text-xs text-muted-foreground">{syncText}</p>
 <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_20rem]"><section className="glass-panel rounded-3xl p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
 <label className="text-sm font-medium">{c.documentType}<select value={doc.type} onChange={(e)=>{const type=e.target.value as Doc["type"];set({type,number:nextNumber(type,docs)})}} className={input}><option value="invoice">{c.invoice}</option><option value="quote">{c.quote}</option></select></label>
 <label className="text-sm font-medium">{c.number}<input value={doc.number} onChange={(e)=>set({number:e.target.value})} maxLength={50} className={input}/></label>
 <label className="text-sm font-medium">{c.currency}<select value={doc.currency} onChange={(e)=>set({currency:e.target.value})} className={input}>{["GBP","EUR","USD","HUF"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="text-sm font-medium">{c.issueDate}<input type="date" value={doc.issueDate} onChange={(e)=>set({issueDate:e.target.value})} className={input}/></label>
 <label className="text-sm font-medium">{c.dueDate}<input type="date" value={doc.dueDate} onChange={(e)=>set({dueDate:e.target.value})} className={input}/></label>
 <label className="text-sm font-medium">{c.vatRate}<input type="number" min="0" step="0.01" value={doc.vatRate} onChange={(e)=>set({vatRate:Number(e.target.value)})} className={input}/></label>
 <label className="text-sm font-medium">{c.status}<select value={doc.status||"draft"} onChange={(e)=>set({status:e.target.value as DocStatus})} className={input}><option value="draft">{c.statusDraft}</option><option value="sent">{c.statusSent}</option><option value="paid">{c.statusPaid}</option></select></label></div>
 <div className="mt-6 grid gap-5 md:grid-cols-2"><div><h2 className="font-semibold">{c.business}</h2><p className="mt-1 text-xs text-muted-foreground">{c.rememberBusiness}</p><input value={doc.businessName} onChange={(e)=>set({businessName:e.target.value})} placeholder={c.businessName} className={input}/><textarea value={doc.businessDetails} onChange={(e)=>set({businessDetails:e.target.value})} placeholder={c.businessDetails} rows={4} className={input}/></div><div><h2 className="font-semibold">{c.client}</h2>{customers.length>0&&<select defaultValue="" onChange={(e)=>chooseCustomer(e.target.value)} className={input}><option value="" disabled>{c.selectCustomer}</option>{customers.map((customer)=><option key={customer.id} value={customer.id}>{customer.title}</option>)}</select>}<input value={doc.clientName} onChange={(e)=>set({clientName:e.target.value})} placeholder={c.clientName} className={input}/><textarea value={doc.clientDetails} onChange={(e)=>set({clientDetails:e.target.value})} placeholder={c.clientDetails} rows={4} className={input}/></div></div>
 <h2 className="mt-7 font-semibold">{c.items}</h2><div className="mt-3 space-y-3">{doc.items.map((item)=><div key={item.id} className="grid gap-3 rounded-xl border border-border p-3 sm:grid-cols-[1fr_7rem_9rem_auto]"><input value={item.description} onChange={(e)=>updateItem(item.id,{description:e.target.value})} placeholder={c.description} className="rounded-lg border border-input bg-input/30 px-3 py-2"/><input type="number" min="0" step="0.01" value={item.quantity} onChange={(e)=>updateItem(item.id,{quantity:Number(e.target.value)})} aria-label={c.quantity} className="rounded-lg border border-input bg-input/30 px-3 py-2"/><input type="number" min="0" step="0.01" value={item.unitPrice} onChange={(e)=>updateItem(item.id,{unitPrice:Number(e.target.value)})} aria-label={c.unitPrice} className="rounded-lg border border-input bg-input/30 px-3 py-2"/><button type="button" title={c.remove} onClick={()=>set({items:doc.items.filter(x=>x.id!==item.id)})} className="rounded-lg border border-border px-3 py-2 text-sm">×</button></div>)}</div>
 <button type="button" onClick={()=>set({items:[...doc.items,{id:crypto.randomUUID(),description:"",quantity:1,unitPrice:0}]})} className="mt-3 rounded-lg border border-border px-4 py-2 text-sm font-semibold hover:bg-secondary">+ {c.addItem}</button>
 <div className="mt-7 grid gap-5 md:grid-cols-[1fr_18rem]"><textarea value={doc.notes} onChange={(e)=>set({notes:e.target.value})} placeholder={c.notes} rows={5} className="rounded-xl border border-input bg-input/30 p-3.5"/><div className="rounded-2xl bg-background/50 p-5 text-sm"><p className="flex justify-between"><span>{c.subtotal}</span><strong>{money(totals.subtotal)}</strong></p><p className="mt-3 flex justify-between"><span>{c.vat}</span><strong>{money(totals.vat)}</strong></p><p className="mt-4 flex justify-between border-t border-border pt-4 text-lg"><span>{c.total}</span><strong className="text-primary">{money(totals.total)}</strong></p></div></div>
 <div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={save} className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">{c.save}</button><button type="button" onClick={print} className="rounded-xl border border-border px-5 py-3 text-sm font-semibold hover:bg-secondary">{c.print}</button><button type="button" onClick={newDocument} className="rounded-xl border border-border px-5 py-3 text-sm font-semibold hover:bg-secondary">{c.newDoc}</button></div><p className="mt-5 text-xs leading-6 text-muted-foreground">{c.disclaimer}</p></section>
 <aside className="glass-panel h-fit rounded-3xl p-5"><h2 className="font-semibold">{c.saved}</h2><div className="mt-4 grid grid-cols-2 gap-2">{(["all","draft","sent","paid","overdue"] as const).map((value)=><button key={value} type="button" onClick={()=>setFilter(value)} className={`rounded-lg border px-2 py-2 text-xs ${filter===value?"border-primary bg-primary/10 text-primary":"border-border text-muted-foreground"}`}>{value==="all"?c.filterAll:statusLabel(value)} · {counts[value]}</button>)}</div><div className="mt-4 space-y-3">{docs.length===0&&<p className="text-sm text-muted-foreground">{c.empty}</p>}{docs.length>0&&visibleDocs.length===0&&<p className="text-sm text-muted-foreground">{c.noMatch}</p>}{visibleDocs.map((saved)=>{const state=statusOf(saved);return <div key={saved.id} className="rounded-xl border border-border p-3"><div className="flex items-start justify-between gap-2"><p className="font-semibold">{saved.number}</p><span className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold ${state==="paid"?"border-primary/40 bg-primary/10 text-primary":state==="overdue"?"border-destructive/40 bg-destructive/10 text-destructive":"border-border text-muted-foreground"}`}>{statusLabel(state)}</span></div><p className="mt-1 truncate text-xs text-muted-foreground">{saved.clientName}</p><div className="mt-3 flex gap-2"><button onClick={()=>setDoc({...saved,status:saved.status||"draft"})} className="rounded-lg border border-border px-3 py-1.5 text-xs">{c.load}</button><button onClick={()=>setDocs((current)=>current.filter(x=>x.id!==saved.id))} className="rounded-lg border border-border px-3 py-1.5 text-xs text-destructive">{c.delete}</button></div></div>})}</div></aside></div></main></AppShell>
}
