"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { ArrowUpRight, CalendarDays, CheckCircle2, Mail, ShieldCheck } from "lucide-react"
import { useI18n } from "@/lib/i18n/provider"
import { useWorkspaceData } from "@/lib/use-workspace-data"

type Kind="customer-email-attention"|"overdue-customer-contact"|"meeting-quote-followup"|"opportunity-conversation"
type Finding={id:string;kind:Kind;provider:"google"|"microsoft";count:number;confidence:"high";customerIds:string[];customerNames:string[];workspaceEvidenceIds?:string[];externalEvidenceIds:string[];nextAt?:string|null;href:string}
type Payload={findings:Finding[];providers:{provider:string;available:boolean}[];access:"read-only";contentStored:false;externalActions:false;checkedAt:string}
type Task={id:string;title:string;due:string;priority:"high"|"medium";done:boolean;sourceId:string}

const COPY={
 en:{eye:"GOOGLE / MICROSOFT INTELLIGENCE",title:"External signals, understood in business context.",sub:"HEGEVA matches read-only email and calendar metadata to real customers, quotes and invoices. It does not read message bodies, store external content or perform external actions.",loading:"Analysing connected read-only signals…",empty:"No evidence-backed customer relationship was found in the current bounded window.",unavailable:"A connected provider could not be read right now.",evidence:"Evidence",impact:"Why this matters",recommend:"Recommended action",prepare:"Prepare in Planner",prepared:"Added to Planner",open:"Open linked workspace",boundary:"READ → UNDERSTAND → MATCH → PRIORITISE → RECOMMEND · Owner approval remains required",provider:{google:"Google Workspace",microsoft:"Microsoft 365"},kind:{"customer-email-attention":"Customer emails may need attention","overdue-customer-contact":"A customer with an overdue invoice contacted you","meeting-quote-followup":"Upcoming customer meeting links to an open quote","opportunity-conversation":"Conversations appear related to active opportunities"},impactText:{"customer-email-attention":"A real customer message may be waiting while work is in progress.","overdue-customer-contact":"The contact provides a timely opening to resolve evidenced overdue revenue.","meeting-quote-followup":"Preparing before the meeting can reduce quote leakage.","opportunity-conversation":"The conversations connect directly to an existing lead or open quote."}},
 hu:{eye:"GOOGLE / MICROSOFT INTELLIGENCE",title:"Külső jelzések, üzleti összefüggésben értelmezve.",sub:"A HEGEVA csak olvasható e-mail- és naptár-metaadatokat kapcsol valódi ügyfelekhez, ajánlatokhoz és számlákhoz. Nem olvas levéltörzset, nem tárol külső tartalmat és nem végez külső műveletet.",loading:"A kapcsolt, csak olvasható jelzések elemzése…",empty:"A korlátozott időablakban nincs bizonyítékkal alátámasztott ügyfélkapcsolat.",unavailable:"Egy kapcsolt szolgáltató most nem olvasható.",evidence:"Bizonyíték",impact:"Miért fontos",recommend:"Javasolt lépés",prepare:"Előkészítés a Tervezőben",prepared:"A Tervezőhöz adva",open:"Kapcsolt munkaterület megnyitása",boundary:"OLVASÁS → ÉRTELMEZÉS → PÁROSÍTÁS → PRIORITÁS → JAVASLAT · A tulajdonosi jóváhagyás kötelező",provider:{google:"Google Workspace",microsoft:"Microsoft 365"},kind:{"customer-email-attention":"Ügyfél-e-mailek várhatnak figyelemre","overdue-customer-contact":"Lejárt számlával rendelkező ügyfél jelentkezett","meeting-quote-followup":"Közelgő ügyféltalálkozó nyitott ajánlathoz kapcsolódik","opportunity-conversation":"Beszélgetések aktív lehetőséghez kapcsolódnak"},impactText:{"customer-email-attention":"Valódi ügyfélüzenet várhat válaszra folyamatban lévő munka mellett.","overdue-customer-contact":"A megkeresés időszerű lehetőség az igazolt lejárt bevétel rendezésére.","meeting-quote-followup":"A találkozó előtti felkészülés csökkentheti az ajánlati veszteséget.","opportunity-conversation":"A beszélgetések meglévő leadhez vagy nyitott ajánlathoz kapcsolódnak."}},
 de:{eye:"GOOGLE / MICROSOFT INTELLIGENCE",title:"Externe Signale im Geschäftskontext verstanden.",sub:"HEGEVA verknüpft nur lesbare E-Mail- und Kalendermetadaten mit echten Kunden, Angeboten und Rechnungen. Keine Nachrichtentexte, keine externe Speicherung, keine externe Aktion.",loading:"Nur-Lese-Signale werden analysiert…",empty:"Im begrenzten Zeitraum wurde kein belegter Kundenbezug gefunden.",unavailable:"Ein verbundener Anbieter ist derzeit nicht lesbar.",evidence:"Nachweis",impact:"Warum wichtig",recommend:"Empfohlene Aktion",prepare:"Im Planer vorbereiten",prepared:"Zum Planer hinzugefügt",open:"Verknüpften Workspace öffnen",boundary:"LESEN → VERSTEHEN → ZUORDNEN → PRIORISIEREN → EMPFEHLEN · Eigentümerfreigabe bleibt erforderlich",provider:{google:"Google Workspace",microsoft:"Microsoft 365"},kind:{"customer-email-attention":"Kunden-E-Mails benötigen möglicherweise Aufmerksamkeit","overdue-customer-contact":"Ein Kunde mit überfälliger Rechnung hat Kontakt aufgenommen","meeting-quote-followup":"Kundentermin ist mit offenem Angebot verknüpft","opportunity-conversation":"Konversationen gehören zu aktiven Chancen"},impactText:{"customer-email-attention":"Eine echte Kundennachricht wartet möglicherweise auf Bearbeitung.","overdue-customer-contact":"Der Kontakt schafft eine aktuelle Gelegenheit, belegte Außenstände zu klären.","meeting-quote-followup":"Vorbereitung vor dem Termin kann Angebotsverluste senken.","opportunity-conversation":"Die Konversationen sind mit einem Lead oder offenen Angebot verbunden."}},
 fr:{eye:"GOOGLE / MICROSOFT INTELLIGENCE",title:"Des signaux externes compris dans leur contexte métier.",sub:"HEGEVA associe uniquement les métadonnées e-mail et calendrier en lecture seule aux vrais clients, devis et factures. Aucun corps de message stocké, aucune action externe.",loading:"Analyse des signaux en lecture seule…",empty:"Aucune relation client étayée dans la fenêtre limitée.",unavailable:"Un fournisseur connecté est momentanément indisponible.",evidence:"Preuve",impact:"Pourquoi c’est important",recommend:"Action recommandée",prepare:"Préparer dans le planning",prepared:"Ajouté au planning",open:"Ouvrir l’espace lié",boundary:"LIRE → COMPRENDRE → ASSOCIER → PRIORISER → RECOMMANDER · Approbation du propriétaire requise",provider:{google:"Google Workspace",microsoft:"Microsoft 365"},kind:{"customer-email-attention":"Des e-mails clients peuvent nécessiter votre attention","overdue-customer-contact":"Un client avec facture en retard vous a contacté","meeting-quote-followup":"Une réunion client est liée à un devis ouvert","opportunity-conversation":"Des conversations concernent des opportunités actives"},impactText:{"customer-email-attention":"Un vrai message client peut attendre une réponse.","overdue-customer-contact":"Le contact permet de traiter rapidement un revenu en retard confirmé.","meeting-quote-followup":"Se préparer avant la réunion peut réduire la perte de devis.","opportunity-conversation":"Les conversations sont liées à un prospect ou devis existant."}},
 es:{eye:"GOOGLE / MICROSOFT INTELLIGENCE",title:"Señales externas entendidas en contexto empresarial.",sub:"HEGEVA vincula metadatos de correo y calendario de solo lectura con clientes, presupuestos y facturas reales. No lee cuerpos, no almacena contenido externo ni ejecuta acciones externas.",loading:"Analizando señales conectadas de solo lectura…",empty:"No se encontró una relación respaldada en la ventana limitada.",unavailable:"Un proveedor conectado no está disponible ahora.",evidence:"Evidencia",impact:"Por qué importa",recommend:"Acción recomendada",prepare:"Preparar en Planificador",prepared:"Añadido al Planificador",open:"Abrir espacio vinculado",boundary:"LEER → ENTENDER → VINCULAR → PRIORIZAR → RECOMENDAR · Se requiere aprobación del propietario",provider:{google:"Google Workspace",microsoft:"Microsoft 365"},kind:{"customer-email-attention":"Algunos correos de clientes pueden requerir atención","overdue-customer-contact":"Un cliente con factura vencida se ha puesto en contacto","meeting-quote-followup":"Una reunión está vinculada a un presupuesto abierto","opportunity-conversation":"Hay conversaciones relacionadas con oportunidades activas"},impactText:{"customer-email-attention":"Un mensaje real de cliente puede estar esperando respuesta.","overdue-customer-contact":"El contacto permite abordar ingresos vencidos demostrados.","meeting-quote-followup":"Prepararse antes de la reunión puede reducir la pérdida de presupuestos.","opportunity-conversation":"Las conversaciones están vinculadas a un lead o presupuesto existente."}},
} as const

export function ExternalIntelligenceLayer(){
 const{locale}=useI18n(),c=COPY[locale],{items:tasks,setItems:setTasks}=useWorkspaceData<Task>("planner"),[payload,setPayload]=useState<Payload|null>(null),[failed,setFailed]=useState(false)
 useEffect(()=>{const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),12000);fetch("/api/integrations/intelligence",{credentials:"include",cache:"no-store",signal:controller.signal}).then(async response=>{if(response.status===401){setPayload({findings:[],providers:[],access:"read-only",contentStored:false,externalActions:false,checkedAt:new Date().toISOString()});return}if(!response.ok)throw new Error("integration-intelligence-unavailable");setPayload(await response.json())}).catch(()=>setFailed(true)).finally(()=>window.clearTimeout(timer));return()=>{window.clearTimeout(timer);controller.abort()}},[])
 const source=(finding:Finding)=>`integration-intelligence:${finding.id}:${new Date().toISOString().slice(0,10)}`,has=(finding:Finding)=>tasks.some(task=>task.sourceId===source(finding)),prepare=(finding:Finding)=>{if(has(finding))return;setTasks(all=>[{id:crypto.randomUUID(),title:c.kind[finding.kind],due:new Date().toISOString().slice(0,10),priority:finding.kind==="overdue-customer-contact"?"high":"medium",done:false,sourceId:source(finding)},...all])}
 return <section className="mt-10 space-y-4"><header className="rounded-3xl border border-cyan-300/25 bg-gradient-to-br from-cyan-300/[.08] via-background to-primary/[.04] p-6"><p className="ve-eyebrow">{c.eye}</p><h2 className="mt-2 font-display text-3xl font-semibold">{c.title}</h2><p className="mt-3 max-w-4xl text-sm leading-6 text-muted-foreground">{c.sub}</p></header>{!payload&&!failed?<p className="text-sm text-muted-foreground">{c.loading}</p>:failed?<p className="text-sm text-amber-300">{c.unavailable}</p>:payload!.findings.length?<div className="grid gap-4 xl:grid-cols-2">{payload!.findings.map(finding=><article key={finding.id} className="rounded-3xl border border-border bg-background/45 p-5"><div className="flex items-start gap-3">{finding.kind==="meeting-quote-followup"?<CalendarDays className="mt-1 size-5 text-cyan-300"/>:<Mail className="mt-1 size-5 text-cyan-300"/>}<div><small className="text-cyan-300">{c.provider[finding.provider]} · {finding.confidence.toUpperCase()}</small><h3 className="mt-1 font-semibold">{c.kind[finding.kind]}</h3></div></div><div className="mt-4 grid gap-3 text-xs sm:grid-cols-2"><p><b>{c.evidence}:</b> {finding.count} · {finding.customerNames.slice(0,3).join(", ")}</p><p><b>{c.impact}:</b> {c.impactText[finding.kind]}</p></div><div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" disabled={has(finding)} onClick={()=>prepare(finding)} className="min-h-11 rounded-xl border border-cyan-300/35 px-4 text-xs font-semibold text-cyan-200 disabled:text-emerald-300">{has(finding)?<span className="inline-flex items-center gap-2"><CheckCircle2 className="size-4"/>{c.prepared}</span>:c.prepare}</button><Link href={finding.href} className="inline-flex min-h-11 items-center gap-2 text-xs font-semibold text-primary">{c.open}<ArrowUpRight className="size-4"/></Link></div></article>)}</div>:<p className="rounded-2xl border border-border p-4 text-sm text-muted-foreground">{c.empty}</p>}<p className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 text-primary"/>{c.boundary}</p></section>
}
