"use client"

import { useState } from "react"
import { Check, ListChecks, ShieldCheck, Sparkles, Target } from "lucide-react"
import { useI18n } from "@/lib/i18n/provider"
import { useWorkspaceData } from "@/lib/use-workspace-data"

type Goal={id:string;goal:string;steps:string[];state:"awaiting-approval"|"approved"|"added-to-planner";createdAt:string}
type Task={id:string;title:string;priority:"low"|"medium"|"high";done:boolean;goalId?:string}
const copy={
 en:{eyebrow:"V4 · Goal Mode",title:"Tell HEGEVA the outcome, not the task.",sub:"HEGEVA prepares a bounded plan first. You approve it before anything is added to your workspace.",placeholder:"Example: Help me win five new customers this month",prepare:"Prepare plan",approval:"Awaiting your approval",approve:"Approve plan",add:"Add approved steps to Planner",added:"Added to Planner",current:"Current goal",empty:"No active goal yet.",steps:["Review the current workspace evidence","Define a measurable result and deadline","Prepare the first customer-facing action","Review results and choose the next verified step"]},
 hu:{eyebrow:"V4 · Goal Mode",title:"Az eredményt mondd meg a HEGEVA-nak, ne a feladatot.",sub:"A HEGEVA először korlátozott tervet készít. Csak a jóváhagyásod után kerül bármi a munkaterületre.",placeholder:"Példa: Segíts öt új ügyfelet szereznem ebben a hónapban",prepare:"Terv készítése",approval:"Jóváhagyásodra vár",approve:"Terv jóváhagyása",add:"Jóváhagyott lépések a Tervezőbe",added:"Hozzáadva a Tervezőhöz",current:"Aktív cél",empty:"Még nincs aktív cél.",steps:["A jelenlegi munkaterületi adatok áttekintése","Mérhető eredmény és határidő meghatározása","Az első ügyféloldali lépés előkészítése","Az eredmények ellenőrzése és a következő igazolt lépés kiválasztása"]},
 de:{eyebrow:"V4 · Goal Mode",title:"Nennen Sie HEGEVA das Ergebnis, nicht die Aufgabe.",sub:"HEGEVA erstellt zuerst einen begrenzten Plan. Erst nach Ihrer Freigabe wird etwas hinzugefügt.",placeholder:"Beispiel: Diesen Monat fünf neue Kunden gewinnen",prepare:"Plan vorbereiten",approval:"Wartet auf Freigabe",approve:"Plan freigeben",add:"Freigegebene Schritte zum Planer",added:"Zum Planer hinzugefügt",current:"Aktuelles Ziel",empty:"Noch kein aktives Ziel.",steps:["Aktuelle Workspace-Daten prüfen","Messbares Ergebnis und Frist definieren","Erste kundenbezogene Aktion vorbereiten","Ergebnisse prüfen und nächsten verifizierten Schritt wählen"]},
 fr:{eyebrow:"V4 · Goal Mode",title:"Donnez le résultat à HEGEVA, pas la tâche.",sub:"HEGEVA prépare d’abord un plan limité. Rien n’est ajouté sans votre approbation.",placeholder:"Exemple : gagner cinq nouveaux clients ce mois-ci",prepare:"Préparer le plan",approval:"En attente d’approbation",approve:"Approuver le plan",add:"Ajouter les étapes au planning",added:"Ajouté au planning",current:"Objectif actuel",empty:"Aucun objectif actif.",steps:["Examiner les données actuelles","Définir un résultat mesurable et une échéance","Préparer la première action client","Vérifier les résultats et choisir l’étape suivante"]},
 es:{eyebrow:"V4 · Goal Mode",title:"Dile a HEGEVA el resultado, no la tarea.",sub:"HEGEVA prepara primero un plan limitado. Nada se añade sin tu aprobación.",placeholder:"Ejemplo: conseguir cinco clientes nuevos este mes",prepare:"Preparar plan",approval:"Pendiente de aprobación",approve:"Aprobar plan",add:"Añadir pasos al planificador",added:"Añadido al planificador",current:"Objetivo actual",empty:"Aún no hay un objetivo activo.",steps:["Revisar los datos actuales","Definir un resultado medible y una fecha","Preparar la primera acción para clientes","Revisar resultados y elegir el siguiente paso verificado"]},
} as const

export function GoalMode(){
 const{locale}=useI18n();const c=copy[locale]
 const{items:goals,setItems:setGoals,syncState}=useWorkspaceData<Goal>("goal_mode")
 const{setItems:setTasks}=useWorkspaceData<Task>("planner")
 const[input,setInput]=useState("")
 const current=goals[0]
 const prepare=()=>{const goal=input.trim().slice(0,240);if(!goal)return;setGoals(items=>[{id:crypto.randomUUID(),goal,steps:[...c.steps],state:"awaiting-approval",createdAt:new Date().toISOString()},...items.slice(0,9)]);setInput("")}
 const approve=()=>current&&setGoals(items=>items.map(goal=>goal.id===current.id?{...goal,state:"approved"}:goal))
 const addToPlanner=()=>{if(!current||current.state!=="approved")return;setTasks(tasks=>{if(tasks.some(task=>task.goalId===current.id))return tasks;return [...current.steps.map((title,index)=>({id:crypto.randomUUID(),title,priority:(index===0?"high":"medium") as Task["priority"],done:false,goalId:current.id})),...tasks]});setGoals(items=>items.map(goal=>goal.id===current.id?{...goal,state:"added-to-planner"}:goal))}
 return <section className="border-t border-border bg-background/45 px-4 py-7 sm:px-6"><div className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><div><p className="ve-eyebrow">{c.eyebrow}</p><h2 className="mt-2 max-w-2xl font-display text-3xl font-semibold">{c.title}</h2><p className="mt-3 max-w-xl text-sm leading-7 text-muted-foreground">{c.sub}</p><div className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={input} onChange={event=>setInput(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")prepare()}} maxLength={240} placeholder={c.placeholder} className="min-h-12 flex-1 rounded-xl border border-border bg-input/30 px-4 text-sm outline-none focus:border-primary/50"/><button type="button" disabled={!input.trim()} onClick={prepare} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground disabled:opacity-50"><Sparkles className="size-4" aria-hidden/>{c.prepare}</button></div><p className="mt-2 text-xs capitalize text-muted-foreground">{syncState}</p></div><div className="rounded-3xl border border-primary/20 bg-primary/[0.035] p-5">{current?<><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Target className="size-5" aria-hidden/></span><div><p className="text-xs uppercase tracking-[.14em] text-muted-foreground">{c.current}</p><h3 className="mt-1 font-semibold">{current.goal}</h3></div></div><ol className="mt-5 space-y-2">{current.steps.map((step,index)=><li key={step} className="flex gap-3 rounded-xl border border-border bg-background/45 p-3 text-sm"><span className="font-mono text-primary">{String(index+1).padStart(2,"0")}</span><span>{step}</span></li>)}</ol><div className="mt-5 flex flex-wrap items-center gap-3">{current.state==="awaiting-approval"?<><span className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ShieldCheck className="size-4"/>{c.approval}</span><button type="button" onClick={approve} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">{c.approve}</button></>:current.state==="approved"?<button type="button" onClick={addToPlanner} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><ListChecks className="size-4"/>{c.add}</button>:<span className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><Check className="size-4"/>{c.added}</span>}</div></>:<p className="text-sm text-muted-foreground">{c.empty}</p>}</div></div></section>
}
