"use client"

import { RefreshCcw, ShieldCheck } from "lucide-react"
import { useI18n } from "@/lib/i18n/provider"
import { useWorkspaceData } from "@/lib/use-workspace-data"
import { adaptGoalPlan, expectedGoalProgress, goalProgress, measureGoalOutcome, type GoalEvidence, type GoalPlan } from "@/lib/goal-mode-v4"
import type { AutopilotCustomer, AutopilotInvoice, AutopilotTask } from "@/lib/autopilot-v1"

type Goal={id:string;goal:string;steps:string[];state:"awaiting-approval"|"approved"|"added-to-planner";createdAt:string;plan?:GoalPlan;revision?:number;previousGoalId?:string}
type Task=AutopilotTask&{goalId?:string}
const COPY={
 en:{title:"Measure & Adapt",activity:"Activity progress",outcome:"Business outcome progress",expected:"Expected by now",unavailable:"Not yet measurable from verified workspace data",ahead:"On or ahead of target",behind:"Behind target — HEGEVA recommends adapting the plan",adapt:"Prepare adapted plan",approval:"The revised plan requires owner approval again"},
 hu:{title:"Mérés és alkalmazkodás",activity:"Aktivitási előrehaladás",outcome:"Üzleti eredmény előrehaladása",expected:"Mostanra elvárt",unavailable:"Hitelesített munkaterületi adatból még nem mérhető",ahead:"Célon vagy a cél előtt",behind:"A cél mögött — a HEGEVA a terv módosítását javasolja",adapt:"Módosított terv előkészítése",approval:"A módosított tervhez ismét tulajdonosi jóváhagyás szükséges"},
 de:{title:"Messen & Anpassen",activity:"Aktivitätsfortschritt",outcome:"Geschäftsergebnis",expected:"Bis jetzt erwartet",unavailable:"Noch nicht aus verifizierten Workspace-Daten messbar",ahead:"Im oder vor dem Ziel",behind:"Hinter dem Ziel — HEGEVA empfiehlt eine Plananpassung",adapt:"Angepassten Plan vorbereiten",approval:"Der überarbeitete Plan erfordert erneut Ihre Freigabe"},
 fr:{title:"Mesurer et adapter",activity:"Progression des activités",outcome:"Progression du résultat métier",expected:"Attendu à ce jour",unavailable:"Pas encore mesurable à partir de données vérifiées",ahead:"Dans l’objectif ou en avance",behind:"En retard — HEGEVA recommande d’adapter le plan",adapt:"Préparer un plan adapté",approval:"Le plan révisé nécessite une nouvelle approbation"},
 es:{title:"Medir y adaptar",activity:"Progreso de actividad",outcome:"Progreso del resultado empresarial",expected:"Esperado a estas alturas",unavailable:"Aún no se puede medir con datos verificados",ahead:"En objetivo o por delante",behind:"Por detrás — HEGEVA recomienda adaptar el plan",adapt:"Preparar plan adaptado",approval:"El plan revisado requiere otra aprobación"},
} as const

export function GoalAdaptCycle(){
 const{locale}=useI18n(),c=COPY[locale]
 const{items:goals,setItems:setGoals}=useWorkspaceData<Goal>("goal_mode"),{items:tasks}=useWorkspaceData<Task>("planner"),{items:customers}=useWorkspaceData<AutopilotCustomer>("customers"),{items:invoices}=useWorkspaceData<AutopilotInvoice>("invoice_documents")
 const current=goals[0];if(!current?.plan)return null
 const today=new Date().toISOString().slice(0,10),total=(item:AutopilotInvoice)=>(item.items||[]).reduce((sum,line)=>sum+(Number(line.quantity)||0)*(Number(line.unitPrice)||0),0)*(1+(Number(item.vatRate)||0)/100),unpaid=invoices.filter(item=>item.type==="invoice"&&item.status!=="paid")
 const evidence:GoalEvidence={customers:customers.filter(item=>item.customerStatus!=="lead").length,leads:customers.filter(item=>item.customerStatus==="lead").length,unpaidInvoices:unpaid.length,unpaidValue:unpaid.reduce((sum,item)=>sum+total(item),0),overdueTasks:tasks.filter(item=>!item.done&&item.due&&item.due<today).length,currency:unpaid[0]?.currency||"GBP",paidRevenue:invoices.filter(item=>item.type==="invoice"&&item.status==="paid").reduce((sum,item)=>sum+total(item),0)}
 const goalTasks=tasks.filter(item=>item.goalId===current.id),completed=goalTasks.filter(item=>item.done).length,activity=goalProgress(current.plan,completed,current.steps.length),outcome=measureGoalOutcome(current.plan,evidence),expected=expectedGoalProgress(current.createdAt,current.plan.deadline),behind=Boolean(outcome.available&&outcome.progress!==null&&outcome.progress+5<expected)
 const adapt=()=>{if(current.state!=="added-to-planner")return;const plan=adaptGoalPlan(current.plan!,evidence);setGoals(items=>[{...current,id:crypto.randomUUID(),state:"awaiting-approval",createdAt:new Date().toISOString(),plan,revision:(current.revision||1)+1,previousGoalId:current.id},...items.slice(0,9)])}
 return <section className="border-t border-border bg-background/45 px-4 pb-7 sm:px-6"><div className="rounded-3xl border border-gold/25 bg-gold/[.035] p-5"><div className="flex items-center gap-2"><RefreshCcw className="size-5 text-gold"/><h3 className="font-display text-xl font-semibold">{c.title}</h3></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-border p-4"><p className="text-xs text-muted-foreground">{c.activity}</p><strong className="mt-1 block text-2xl text-primary">{activity}%</strong><small>{completed}/{current.steps.length}</small></div><div className="rounded-2xl border border-border p-4"><p className="text-xs text-muted-foreground">{c.outcome}</p><strong className="mt-1 block text-2xl text-gold">{outcome.available?`${outcome.progress}%`:"—"}</strong><small>{outcome.available?`${c.expected}: ${expected}%`:c.unavailable}</small></div></div><p className={`mt-4 text-sm font-semibold ${behind?"text-amber-300":"text-emerald-300"}`}>{behind?c.behind:c.ahead}</p>{current.state==="added-to-planner"&&<div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" onClick={adapt} className="min-h-11 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground">{c.adapt}</button><span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground"><ShieldCheck className="size-4"/>{c.approval}</span></div>}</div></section>
}
