"use client"

import Link from "next/link"
import { AlertTriangle, ArrowUpRight, Bot, Blocks, CalendarDays, Check, Circle, Cloud, FileText, ListChecks, MessageSquareText, PoundSterling, Receipt, UserPlus, Users } from "lucide-react"
import { useI18n } from "@/lib/i18n/provider"
import { useWorkspaceData } from "@/lib/use-workspace-data"
import { AICore } from "@/components/visual-engine"
import { cn } from "@/lib/utils"
import { createWorkspaceMissionProjection } from "@/lib/foundation/brain-runtime"
import { createWorkspacePulseProjection } from "@/lib/foundation/roadmap-foundations"
import { useCoreDecision, type CorePriority } from "@/lib/use-core-decision"
import { growthSignalCopy, overdueTaskCopy } from "@/lib/hegeva-core-copy"
import { CoreDecisionSurface, getCoreStatusSummary } from "@/components/command-center/core-decision-surface"
import { selectHegevaCorePriority } from "@/lib/hegeva-core"

type RecordItem={id:string;amount?:number;customerStatus?:"lead"|"active"|"paused";followUp?:string}
type Task={id:string;due?:string;done:boolean;title?:string}
type Invoice={id:string;type:"invoice"|"quote";status?:"draft"|"sent"|"paid";dueDate?:string;currency?:string;vatRate?:number;items?:{quantity?:number;unitPrice?:number}[]}
type Message={id:string;sourceId?:string;workflowStatus?:"draft"|"approved"|"completed"}

const copy={
 en:{eyebrow:"Operating picture",title:"Your work, in one line of sight",sub:"HEGEVA reads the real records in this workspace. Nothing below is simulated.",mission:"Workspace readiness mission",goal:"Turn scattered work into an operating workspace",understand:"Understand",plan:"Plan",work:"Execute",check:"Check",result:"Result",current:"Current work",empty:"No open tasks yet",openPlanner:"Open planner",inventory:"Workspace inventory",customers:"Customers",documents:"Documents",expenses:"Expenses",invoices:"Invoices",messages:"Messages",assistant:"Assistant",appStudio:"App Studio",available:"Available",attention:"Needs attention",clear:"No overdue tasks or invoices",sync:"Workspace data",cloud:"Authenticated cloud workspace",local:"Local workspace · not cloud-synced"},
 hu:{eyebrow:"Működési kép",title:"A munkád egyetlen áttekinthető térben",sub:"A HEGEVA a munkaterület valódi rekordjait olvassa. Az alábbi adatok nem szimuláltak.",mission:"Munkaterület-készenléti küldetés",goal:"A szétszórt munkából működő munkaterület",understand:"Megértés",plan:"Tervezés",work:"Végrehajtás",check:"Ellenőrzés",result:"Eredmény",current:"Aktuális munka",empty:"Még nincs nyitott feladat",openPlanner:"Tervező megnyitása",inventory:"Munkaterület-leltár",customers:"Ügyfelek",documents:"Dokumentumok",expenses:"Kiadások",invoices:"Számlák",messages:"Üzenetek",assistant:"Asszisztens",appStudio:"App Stúdió",available:"Elérhető",attention:"Figyelmet igényel",clear:"Nincs lejárt feladat vagy számla",sync:"Munkaterület-adatok",cloud:"Hitelesített felhő-munkaterület",local:"Helyi munkaterület · nincs felhőszinkron"},
 de:{eyebrow:"Betriebsbild",title:"Ihre Arbeit in einer klaren Sicht",sub:"HEGEVA liest echte Datensätze dieses Arbeitsbereichs. Nichts ist simuliert.",mission:"Workspace-Bereitschaftsmission",goal:"Verteilte Arbeit in einen operativen Workspace verwandeln",understand:"Verstehen",plan:"Planen",work:"Ausführen",check:"Prüfen",result:"Ergebnis",current:"Aktuelle Arbeit",empty:"Noch keine offenen Aufgaben",openPlanner:"Planer öffnen",inventory:"Workspace-Inventar",customers:"Kunden",documents:"Dokumente",expenses:"Ausgaben",invoices:"Rechnungen",messages:"Nachrichten",assistant:"Assistent",appStudio:"App Studio",available:"Verfügbar",attention:"Aufmerksamkeit nötig",clear:"Keine überfälligen Aufgaben oder Rechnungen",sync:"Workspace-Daten",cloud:"Authentifizierter Cloud-Workspace",local:"Lokaler Workspace · nicht cloud-synchronisiert"},
 fr:{eyebrow:"Vue opérationnelle",title:"Votre travail dans un seul champ de vision",sub:"HEGEVA lit les données réelles de cet espace. Rien n’est simulé.",mission:"Mission de préparation de l’espace",goal:"Transformer le travail dispersé en espace opérationnel",understand:"Comprendre",plan:"Planifier",work:"Exécuter",check:"Vérifier",result:"Résultat",current:"Travail actuel",empty:"Aucune tâche ouverte",openPlanner:"Ouvrir le planning",inventory:"Inventaire",customers:"Clients",documents:"Documents",expenses:"Dépenses",invoices:"Factures",messages:"Messages",assistant:"Assistant",appStudio:"App Studio",available:"Disponible",attention:"À surveiller",clear:"Aucune tâche ou facture en retard",sync:"Données de l’espace",cloud:"Espace cloud authentifié",local:"Espace local · non synchronisé dans le cloud"},
 es:{eyebrow:"Vista operativa",title:"Tu trabajo en un único campo de visión",sub:"HEGEVA lee los registros reales de este espacio. Nada está simulado.",mission:"Misión de preparación",goal:"Convertir trabajo disperso en un espacio operativo",understand:"Comprender",plan:"Planificar",work:"Ejecutar",check:"Verificar",result:"Resultado",current:"Trabajo actual",empty:"Aún no hay tareas abiertas",openPlanner:"Abrir planificador",inventory:"Inventario",customers:"Clientes",documents:"Documentos",expenses:"Gastos",invoices:"Facturas",messages:"Mensajes",assistant:"Asistente",appStudio:"App Studio",available:"Disponible",attention:"Requiere atención",clear:"Sin tareas ni facturas vencidas",sync:"Datos del espacio",cloud:"Espacio cloud autenticado",local:"Espacio local · no sincronizado en la nube"},
} as const
const missionUx={
 en:{prepared:"Planning context prepared",approval:"Awaiting owner approval",notStarted:"Execution not started"},
 hu:{prepared:"A tervezési kontextus elkészült",approval:"Tulajdonosi jóváhagyásra vár",notStarted:"A végrehajtás nem indult el"},
 de:{prepared:"Planungskontext vorbereitet",approval:"Warten auf Inhaberfreigabe",notStarted:"Ausführung nicht gestartet"},
 fr:{prepared:"Contexte de planification préparé",approval:"En attente de l’approbation du propriétaire",notStarted:"Exécution non démarrée"},
 es:{prepared:"Contexto de planificación preparado",approval:"Pendiente de aprobación del propietario",notStarted:"La ejecución no ha comenzado"},
} as const
const projectionCopy={
 en:{records:"Workspace records available",empty:"No workspace data available",continuity:"Workspace continuity is ready for review.",approval:"Awaiting owner approval",localApproval:"Local preview; approval required",next:"Review and approve the next mission step.",cloud:"Authenticated cloud workspace",local:"Local workspace · not cloud-synced"},
 hu:{records:"A munkaterület adatai elérhetők",empty:"Nincs elérhető munkaterületi adat",continuity:"A munkaterület folytonossága áttekintésre kész.",approval:"Tulajdonosi jóváhagyásra vár",localApproval:"Helyi előnézet; jóváhagyás szükséges",next:"Tekintsd át és hagyd jóvá a következő küldetéslépést.",cloud:"Hitelesített felhő-munkaterület",local:"Helyi munkaterület · nincs felhőszinkron"},
 de:{records:"Workspace-Daten verfügbar",empty:"Keine Workspace-Daten verfügbar",continuity:"Workspace-Kontinuität zur Prüfung bereit.",approval:"Warten auf Inhaberfreigabe",localApproval:"Lokale Vorschau; Freigabe erforderlich",next:"Nächsten Missionsschritt prüfen und freigeben.",cloud:"Authentifizierter Cloud-Workspace",local:"Lokaler Workspace · nicht cloud-synchronisiert"},
 fr:{records:"Données de l’espace disponibles",empty:"Aucune donnée d’espace disponible",continuity:"La continuité de l’espace est prête à être examinée.",approval:"En attente de l’approbation du propriétaire",localApproval:"Aperçu local ; approbation requise",next:"Examinez et approuvez la prochaine étape de la mission.",cloud:"Espace cloud authentifié",local:"Espace local · non synchronisé dans le cloud"},
 es:{records:"Datos del espacio disponibles",empty:"No hay datos del espacio disponibles",continuity:"La continuidad del espacio está lista para revisarse.",approval:"Pendiente de aprobación del propietario",localApproval:"Vista previa local; se requiere aprobación",next:"Revisa y aprueba el siguiente paso de la misión.",cloud:"Espacio cloud autenticado",local:"Espacio local · no sincronizado en la nube"},
} as const
const pulseCopy={
 en:{pulse:"HEGEVA Pulse",todaySummary:"Your business today",tasksToday:"Tasks due today",openInvoices:"Open invoices",expectedRevenue:"Expected GBP revenue",draftMessages:"Message drafts",quickActions:"Quick actions",newInvoice:"Create invoice",newMessage:"Write message",newTask:"Add task",newCustomer:"Add customer"},
 hu:{pulse:"HEGEVA Pulse",todaySummary:"A vállalkozásod ma",tasksToday:"Mai feladatok",openInvoices:"Nyitott számlák",expectedRevenue:"Várható GBP-bevétel",draftMessages:"Üzenetvázlatok",quickActions:"Gyors műveletek",newInvoice:"Számla készítése",newMessage:"Üzenet írása",newTask:"Feladat hozzáadása",newCustomer:"Ügyfél hozzáadása"},
 de:{pulse:"HEGEVA Pulse",todaySummary:"Ihr Unternehmen heute",tasksToday:"Heute fällige Aufgaben",openInvoices:"Offene Rechnungen",expectedRevenue:"Erwarteter GBP-Umsatz",draftMessages:"Nachrichtenentwürfe",quickActions:"Schnellaktionen",newInvoice:"Rechnung erstellen",newMessage:"Nachricht schreiben",newTask:"Aufgabe hinzufügen",newCustomer:"Kunden hinzufügen"},
 fr:{pulse:"HEGEVA Pulse",todaySummary:"Votre entreprise aujourd’hui",tasksToday:"Tâches dues aujourd’hui",openInvoices:"Factures ouvertes",expectedRevenue:"Revenu GBP attendu",draftMessages:"Brouillons de messages",quickActions:"Actions rapides",newInvoice:"Créer une facture",newMessage:"Écrire un message",newTask:"Ajouter une tâche",newCustomer:"Ajouter un client"},
 es:{pulse:"HEGEVA Pulse",todaySummary:"Tu negocio hoy",tasksToday:"Tareas para hoy",openInvoices:"Facturas abiertas",expectedRevenue:"Ingresos GBP previstos",draftMessages:"Borradores de mensajes",quickActions:"Acciones rápidas",newInvoice:"Crear factura",newMessage:"Escribir mensaje",newTask:"Añadir tarea",newCustomer:"Añadir cliente"},
} as const
const coreInsightCopy={
 en:{label:"HEGEVA Core priority",review:(count:number)=>`${count} customer follow-up${count===1?" is":"s are"} ready for your approval.`,finish:(count:number)=>`${count} approved follow-up${count===1?" is":"s are"} ready to complete.`,overdue:(count:number,value:string)=>`${count} overdue invoice${count===1?"":"s"} worth ${value} need your attention.`,tasks:(count:number)=>`${count} task${count===1?" is":"s are"} due today.`,clear:"No urgent payment or task risk detected in your current records.",start:"Add your first customer, task or invoice and HEGEVA will build your operating picture.",reviewAction:"Review drafts",finishAction:"Complete follow-ups",invoices:"Prepare follow-ups",planner:"Open today’s tasks",customers:"Add real business data"},
 hu:{label:"A HEGEVA Core prioritása",review:(count:number)=>`${count} ügyfél-utánkövetés vár jóváhagyásra.`,finish:(count:number)=>`${count} jóváhagyott utánkövetés lezárható.`,overdue:(count:number,value:string)=>`${count} lejárt, összesen ${value} értékű számla igényel figyelmet.`,tasks:(count:number)=>`${count} feladat esedékes ma.`,clear:"A jelenlegi adatokban nincs sürgős fizetési vagy feladatkockázat.",start:"Add hozzá az első ügyfelet, feladatot vagy számlát, és a HEGEVA felépíti a működési képet.",reviewAction:"Vázlatok áttekintése",finishAction:"Utánkövetések lezárása",invoices:"Utánkövetések előkészítése",planner:"Mai feladatok megnyitása",customers:"Valós üzleti adatok hozzáadása"},
 de:{label:"HEGEVA Core Priorität",review:(count:number)=>`${count} Kundennachfassung${count===1?" wartet":"en warten"} auf Freigabe.`,finish:(count:number)=>`${count} freigegebene Nachfassung${count===1?" kann":"en können"} abgeschlossen werden.`,overdue:(count:number,value:string)=>`${count} überfällige Rechnung${count===1?"":"en"} im Wert von ${value} erfordern Aufmerksamkeit.`,tasks:(count:number)=>`${count} Aufgabe${count===1?" ist":"n sind"} heute fällig.`,clear:"Keine dringenden Zahlungs- oder Aufgabenrisiken in den aktuellen Daten.",start:"Fügen Sie Kunden, Aufgaben oder Rechnungen hinzu, damit HEGEVA Ihr Betriebsbild erstellt.",reviewAction:"Entwürfe prüfen",finishAction:"Nachfassungen abschließen",invoices:"Nachfassaktionen vorbereiten",planner:"Heutige Aufgaben öffnen",customers:"Echte Geschäftsdaten hinzufügen"},
 fr:{label:"Priorité HEGEVA Core",review:(count:number)=>`${count} suivi${count===1?" client attend":"s clients attendent"} votre approbation.`,finish:(count:number)=>`${count} suivi${count===1?" approuvé est":"s approuvés sont"} prêt à terminer.`,overdue:(count:number,value:string)=>`${count} facture${count===1?"":"s"} en retard d’une valeur de ${value} nécessite${count===1?"":"nt"} votre attention.`,tasks:(count:number)=>`${count} tâche${count===1?" est":"s sont"} due aujourd’hui.`,clear:"Aucun risque urgent de paiement ou de tâche dans les données actuelles.",start:"Ajoutez un client, une tâche ou une facture pour créer votre vue opérationnelle.",reviewAction:"Examiner les brouillons",finishAction:"Terminer les suivis",invoices:"Préparer les relances",planner:"Ouvrir les tâches du jour",customers:"Ajouter des données réelles"},
 es:{label:"Prioridad de HEGEVA Core",review:(count:number)=>`${count} seguimiento${count===1?" está":"s están"} listo para tu aprobación.`,finish:(count:number)=>`${count} seguimiento${count===1?" aprobado está":"s aprobados están"} listo para completar.`,overdue:(count:number,value:string)=>`${count} factura${count===1?"":"s"} vencida${count===1?"":"s"} por ${value} requiere${count===1?"":"n"} atención.`,tasks:(count:number)=>`${count} tarea${count===1?" vence":"s vencen"} hoy.`,clear:"No se detectaron riesgos urgentes de pagos o tareas.",start:"Añade un cliente, una tarea o una factura para crear tu vista operativa.",reviewAction:"Revisar borradores",finishAction:"Completar seguimientos",invoices:"Preparar seguimientos",planner:"Abrir tareas de hoy",customers:"Añadir datos reales"},
} as const
const onboardingCopy={
 en:{title:"Launch your workspace",sub:"Complete these real first steps. Progress is calculated from saved workspace data.",progress:"complete",customer:"Add your first customer",task:"Plan your first task",invoice:"Create your first quote or invoice",assistant:"Ask HEGEVA your first question"},
 hu:{title:"Indítsd el a munkaterületed",sub:"Végezd el ezeket a valódi első lépéseket. A haladás a mentett munkaterületi adatokból számolódik.",progress:"kész",customer:"Add hozzá az első ügyfeledet",task:"Tervezd meg az első feladatodat",invoice:"Készítsd el az első ajánlatodat vagy számládat",assistant:"Tedd fel az első kérdésedet a HEGEVA-nak"},
 de:{title:"Workspace starten",sub:"Schließen Sie diese echten ersten Schritte ab. Der Fortschritt basiert auf gespeicherten Workspace-Daten.",progress:"erledigt",customer:"Ersten Kunden hinzufügen",task:"Erste Aufgabe planen",invoice:"Erstes Angebot oder erste Rechnung erstellen",assistant:"HEGEVA die erste Frage stellen"},
 fr:{title:"Lancez votre espace",sub:"Suivez ces premières étapes réelles. La progression repose sur les données enregistrées.",progress:"terminé",customer:"Ajouter votre premier client",task:"Planifier votre première tâche",invoice:"Créer votre premier devis ou facture",assistant:"Poser votre première question à HEGEVA"},
 es:{title:"Pon en marcha tu espacio",sub:"Completa estos primeros pasos reales. El progreso se calcula con los datos guardados.",progress:"completado",customer:"Añade tu primer cliente",task:"Planifica tu primera tarea",invoice:"Crea tu primer presupuesto o factura",assistant:"Haz tu primera pregunta a HEGEVA"},
} as const
export function OperatingCenter(){
  const {locale}=useI18n();const c=copy[locale]
  const pc=pulseCopy[locale]
  const ic=coreInsightCopy[locale]
  const gc=growthSignalCopy[locale]
  const oc=onboardingCopy[locale]
  const otc=overdueTaskCopy[locale]
  const ux=missionUx[locale]
  const projection=projectionCopy[locale]
  const {items:customers,syncState,cloudEnabled}=useWorkspaceData<RecordItem>("customers")
  const {data: coreResponse, status: coreStatus} = useCoreDecision()
  const {items:documents}=useWorkspaceData<RecordItem>("documents")
  const {items:expenses}=useWorkspaceData<RecordItem>("expenses")
  const {items:tasks}=useWorkspaceData<Task>("planner")
  const {items:invoices}=useWorkspaceData<Invoice>("invoice_documents")
  const {items:messages}=useWorkspaceData<Message>("messages")
  const {items:assistantHistory}=useWorkspaceData<RecordItem>("assistant_history")
  const today=new Date().toISOString().slice(0,10)
  const open=tasks.filter(item=>!item.done)
  const overdueTasks=open.filter(item=>item.due&&item.due<today).length
  const overdueInvoiceRecords=invoices.filter(item=>item.type==="invoice"&&item.status!=="paid"&&item.dueDate&&item.dueDate<today)
  const overdueInvoices=overdueInvoiceRecords.length
  const tasksToday=open.filter(item=>item.due===today).length
  const customerFollowUpsDue=customers.filter(item=>item.followUp&&item.followUp<=today&&item.customerStatus!=="paused").length
  const staleQuotes=invoices.filter(item=>item.type==="quote"&&item.status!=="paid"&&item.dueDate&&item.dueDate<today).length
  const draftInvoices=invoices.filter(item=>item.type==="invoice"&&item.status==="draft").length
  const openInvoices=invoices.filter(item=>item.type==="invoice"&&item.status!=="paid")
  const expectedRevenue=openInvoices.filter(item=>(item.currency||"GBP")==="GBP").reduce((sum,item)=>{const subtotal=(item.items||[]).reduce((value,line)=>value+(Number(line.quantity)||0)*(Number(line.unitPrice)||0),0);return sum+subtotal*(1+(Number(item.vatRate)||0)/100)},0)
  const overdueRevenue=overdueInvoiceRecords.filter(item=>(item.currency||"GBP")==="GBP").reduce((sum,item)=>{const subtotal=(item.items||[]).reduce((value,line)=>value+(Number(line.quantity)||0)*(Number(line.unitPrice)||0),0);return sum+subtotal*(1+(Number(item.vatRate)||0)/100)},0)
  const followUpsAwaitingApproval=messages.filter(item=>item.sourceId&&(!item.workflowStatus||item.workflowStatus==="draft")).length
  const approvedFollowUps=messages.filter(item=>item.sourceId&&item.workflowStatus==="approved").length
  const hasRecords=customers.length+documents.length+expenses.length+invoices.length>0
  const missionProjection=createWorkspaceMissionProjection({scope:cloudEnabled?"authenticated-cloud":"local-browser",hasRecords,openTasks:open.length,overdueItems:overdueTasks+overdueInvoices})
  const pulse=createWorkspacePulseProjection({scope:cloudEnabled?"authenticated-cloud":"local-browser",hasRecords,openTasks:open.length,missionState:"awaiting-approval"})
  const missionStage=missionProjection.stage
  const stageIndex={request:0,understand:1,spec:1,plan:2,permission:2,model:3,"tool-or-job":3,evaluate:4,result:5}[missionStage]
  const stages=[{label:c.understand,done:stageIndex>=1,active:stageIndex===0},{label:c.plan,done:stageIndex>=2,active:missionStage==="permission"||stageIndex===2},{label:c.work,done:stageIndex>=3,active:missionStage==="model"||stageIndex===3}, {label:c.check,done:stageIndex>=4,active:missionStage==="evaluate"},{label:c.result,done:stageIndex>=5,active:missionStage==="result"}]
  const completedStages=stages.filter(stage=>stage.done).length
  const currentStage=missionProjection.stage==="permission"?c.plan:stages.find(stage=>stage.active)?.label||stages.find(stage=>!stage.done)?.label||c.result
  const missionSummary=missionProjection.safeSummary.includes("No workspace")?projection.empty:missionProjection.safeSummary.includes("Workspace records")?projection.records:missionProjection.safeSummary.includes("Local preview")?projection.localApproval:missionProjection.safeSummary.includes("Awaiting")?projection.approval:missionProjection.safeSummary
  const continuitySummary=coreStatus === "ready" ? (coreResponse.pulse.understood || projection.empty) : getCoreStatusSummary(locale, coreStatus)
  const inventory=[[Users,c.customers,customers.length,"/business/customers"],[FileText,c.documents,documents.length,"/business/documents"],[Receipt,c.expenses,expenses.length,"/business/expenses"],[ListChecks,c.invoices,invoices.length,"/business/invoices"],[MessageSquareText,c.messages,messages.length,"/business/messages"]] as const
  const pulseMetrics:Array<[typeof CalendarDays,string,string|number]>=[[CalendarDays,pc.tasksToday,tasksToday],[ListChecks,pc.openInvoices,openInvoices.length],[PoundSterling,pc.expectedRevenue,expectedRevenue.toLocaleString(locale,{style:"currency",currency:"GBP"})],[MessageSquareText,pc.draftMessages,messages.length]]
  const onboardingSteps:Array<[typeof UserPlus,string,string,boolean]>=[[UserPlus,oc.customer,"/business/customers",customers.length>0],[CalendarDays,oc.task,"/business/planner",tasks.length>0],[Receipt,oc.invoice,"/business/invoices",invoices.length>0],[Bot,oc.assistant,"/assistant",assistantHistory.length>0]]
  const onboardingComplete=onboardingSteps.filter(([, , ,done])=>done).length

  // Use real Core V1 response
  const coreSignals = coreResponse.coreSignals
  const localCorePriority = selectHegevaCorePriority(coreSignals)
  const coreDecision = coreResponse.coreDecision || localCorePriority
  const secondaryCorePriorities = coreResponse.corePriorities || coreResponse.priorities

  const explainPriority=(decision:CorePriority)=>decision.kind==="complete-followups"?{text:ic.finish(decision.count),href:decision.href,action:ic.finishAction}:decision.kind==="review-followups"?{text:ic.review(decision.count),href:decision.href,action:ic.reviewAction}:decision.kind==="overdue-invoices"?{text:ic.overdue(decision.count,overdueRevenue.toLocaleString(locale,{style:"currency",currency:"GBP"})),href:decision.href,action:ic.invoices}:decision.kind==="customer-followups"?{text:gc.customer(decision.count),href:decision.href,action:gc.customerAction}:decision.kind==="stale-quotes"?{text:gc.quote(decision.count),href:decision.href,action:gc.quoteAction}:decision.kind==="overdue-tasks"?{text:otc.text(decision.count),href:decision.href,action:otc.action}:decision.kind==="today-tasks"?{text:ic.tasks(decision.count),href:decision.href,action:ic.planner}:decision.kind==="draft-invoices"?{text:gc.draft(decision.count),href:decision.href,action:gc.draftAction}:decision.kind==="clear"?{text:ic.clear,href:decision.href,action:c.inventory}:{text:ic.start,href:decision.href,action:ic.customers}
  const corePriority=explainPriority(coreDecision)

  // Determine if we have sufficient data for meaningful signals
  const hasEnoughData = coreSignals.hasRecords || secondaryCorePriorities.length > 0 || coreSignals.overdueInvoices > 0 || coreSignals.overdueTasks > 0 || coreSignals.tasksToday > 0 || coreSignals.draftInvoices > 0

  return <section className="mt-8 overflow-hidden border-y border-border bg-background/35">
  <div className="control-room-head"><div><p className="ve-eyebrow">{c.eyebrow}</p><h2>{c.title}</h2><p>{c.sub}</p></div><div className="flex items-center gap-3"><AICore state={syncState==="saving"?"working":syncState==="error"?"warning":"ready"}/><div><strong className="block text-sm">{c.sync}</strong><span className="text-xs capitalize text-muted-foreground">{syncState}</span></div></div></div>
  <div className="border-t border-border bg-primary/[0.035] px-4 py-6 sm:px-6">
   <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="ve-eyebrow">{pc.pulse}</p><h3 className="mt-1 font-display text-2xl font-semibold">{pc.todaySummary}</h3></div><p className="text-xs text-muted-foreground">{new Intl.DateTimeFormat(locale,{dateStyle:"full"}).format(new Date())}</p></div>
<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
     {pulseMetrics.map(([Icon,label,value])=><article key={label} className="rounded-2xl border border-border bg-background/55 p-4"><Icon aria-hidden className="size-4 text-primary"/><p className="mt-3 text-xs text-muted-foreground">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></article>)}
    </div>
  </div>

    <CoreDecisionSurface locale={locale} status={coreStatus} response={coreResponse} priority={corePriority} hasEnoughData={hasEnoughData} />
  <div className="border-t border-border px-4 py-6 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="ve-eyebrow">First steps</p><h3 className="mt-1 font-display text-2xl font-semibold">{oc.title}</h3><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{oc.sub}</p></div><strong className="rounded-full border border-primary/30 bg-primary/10 px-4 py-2 text-sm text-primary">{onboardingComplete}/{onboardingSteps.length} {oc.progress}</strong></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted" aria-label={`${onboardingComplete}/${onboardingSteps.length} ${oc.progress}`}><div className="h-full rounded-full bg-primary transition-all" style={{width:`${onboardingComplete/onboardingSteps.length*100}%`}}/></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{onboardingSteps.map(([Icon,label,href,done])=><Link key={label} href={href} className={cn("flex min-h-16 items-center gap-3 rounded-2xl border p-4 text-sm font-semibold transition-colors",done?"border-primary/25 bg-primary/5":"border-border bg-background/45 hover:border-primary/35")}><span className={cn("grid size-9 shrink-0 place-items-center rounded-full",done?"bg-primary text-primary-foreground":"bg-muted text-muted-foreground")}>{done?<Check className="size-4" aria-hidden/>:<Icon className="size-4" aria-hidden/>}</span><span>{label}</span>{!done&&<ArrowUpRight className="ml-auto size-4 text-primary" aria-hidden/>}</Link>)}</div></div>
  <div className="control-room-grid">
   <article className="mission-surface"><header><div><p>{c.mission}</p><h3>{c.goal}</h3><small className="mt-2 block text-xs text-muted-foreground">{missionSummary}</small><small className="block text-xs text-muted-foreground">{ux.prepared} · {ux.approval} · {ux.notStarted}{missionProjection.needsUser ? ` · ${projection.next}` : ""}</small></div><span>01</span></header><div className="mission-body"><div className="mission-core-visual" style={{background:`conic-gradient(var(--gold) ${completedStages*72}deg,oklch(.82 .13 85/.07) 0)`}}><div><AICore state={completedStages===stages.length?"completed":open.length?"working":"ready"}/><small>{currentStage}</small><strong>{completedStages}/{stages.length}</strong></div></div><ol>{stages.map((stage,index)=><li key={stage.label} className={cn(stage.done&&"is-done",stage.active&&"is-active")}><span>{stage.done?<Check aria-hidden/>:stage.active?<span className="mission-current"/>:<Circle aria-hidden/>}</span><div><b>{stage.label}</b><small>{index+1} / {stages.length}</small></div></li>)}</ol></div></article>
   <article className="current-work"><header><div><p>{c.current}</p><span className="text-xs text-muted-foreground">{continuitySummary}</span></div><Link href="/business/planner">{c.openPlanner}<ArrowUpRight aria-hidden/></Link></header>{open.length?<div>{open.slice(0,4).map((task,index)=><div key={task.id}><span>{String(index+1).padStart(2,"0")}</span><p>{task.title||`${c.current} ${index+1}`}</p><time>{task.due||"—"}</time></div>)}</div>:<div className="current-empty"><Check className="size-5 text-primary"/><p>{c.empty}</p></div>}
    <footer className={cn(overdueTasks+overdueInvoices&&"has-alert")}><AlertTriangle aria-hidden/><span>{overdueTasks+overdueInvoices?`${overdueTasks+overdueInvoices} · ${c.attention}`:c.clear}</span></footer></article>
  </div>
  <div className="inventory-strip"><p>{c.inventory}</p>{inventory.map(([Icon,label,value,href])=><Link key={label} href={href}><Icon aria-hidden/><span>{label}</span><strong>{value}</strong></Link>)}<span className="ml-auto hidden items-center gap-2 text-xs text-muted-foreground xl:flex"><Cloud className="size-3.5"/>{cloudEnabled ? projection.cloud : projection.local}</span></div>
  <div className="flex flex-wrap gap-2 border-t border-border px-4 py-3 sm:px-6"><Link href="/assistant" className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-semibold"><Bot aria-hidden className="size-3.5"/>{c.assistant}<span className="text-muted-foreground">· {c.available}</span></Link><Link href="/app-studio/build-my-app-x20" className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-semibold"><Blocks aria-hidden className="size-3.5"/>{c.appStudio}<span className="text-muted-foreground">· {c.available}</span></Link></div>
 </section>
}
