"use client"

import Link from "next/link"
import { useRouter } from "next/navigation"
import { useEffect, useState } from "react"
import { ArrowUpRight, ShieldCheck } from "lucide-react"
import type { Locale } from "@/lib/i18n/dictionaries"

type PreparedWorkRecord = { id: string; role: "Sales" | "Finance" | "Marketing" | "Support"; label: string; title: string; content: string; sourceIds: string[]; rationale: string; targetHref: string; status: "awaiting-review" | "approved" | "cancelled" | "completed-locally"; preparationStatus: "prepared"; deliveryStatus: "not-sent"; executionStatus: "not-executed"; createdAt: string; updatedAt: string }
const COPY: Record<Locale, { title: string; sub: string; review: string; cancel: string; complete: string; open: string; prepareQuote: string; empty: string; unavailable: string }> = {
  en: { title: "Prepared Work Review Board", sub: "Owner review only. Nothing is sent or executed automatically.", review: "Approve", cancel: "Cancel", complete: "Complete locally", open: "Open workspace", prepareQuote: "Open quote draft", empty: "No prepared work needs review.", unavailable: "Prepared work is temporarily unavailable. Reload and try again." },
  hu: { title: "Előkészített munka áttekintő tábla", sub: "Csak tulajdonosi áttekintés. Semmi nincs automatikusan elküldve vagy végrehajtva.", review: "Jóváhagyás", cancel: "Mégse", complete: "Helyi lezárás", open: "Munkaterület megnyitása", prepareQuote: "Ajánlatvázlat megnyitása", empty: "Nincs áttekintendő előkészített munka.", unavailable: "Az előkészített munka átmenetileg nem érhető el. Töltse újra, majd próbálja újra." },
  de: { title: "Prüftafel für vorbereitete Arbeit", sub: "Nur Eigentümerprüfung. Nichts wird automatisch gesendet oder ausgeführt.", review: "Freigeben", cancel: "Abbrechen", complete: "Lokal abschließen", open: "Workspace öffnen", prepareQuote: "Angebotsentwurf öffnen", empty: "Keine vorbereitete Arbeit benötigt eine Prüfung.", unavailable: "Vorbereitete Arbeit ist vorübergehend nicht verfügbar. Laden Sie neu und versuchen Sie es erneut." },
  fr: { title: "Tableau de revue du travail préparé", sub: "Revue du propriétaire uniquement. Rien n’est envoyé ou exécuté automatiquement.", review: "Approuver", cancel: "Annuler", complete: "Terminer localement", open: "Ouvrir l’espace", prepareQuote: "Ouvrir le brouillon de devis", empty: "Aucun travail préparé ne nécessite de revue.", unavailable: "Le travail préparé est temporairement indisponible. Actualisez puis réessayez." },
  es: { title: "Panel de revisión de trabajo preparado", sub: "Solo revisión del propietario. Nada se envía ni ejecuta automáticamente.", review: "Aprobar", cancel: "Cancelar", complete: "Completar localmente", open: "Abrir espacio", prepareQuote: "Abrir borrador de presupuesto", empty: "Ningún trabajo preparado necesita revisión.", unavailable: "El trabajo preparado no está disponible temporalmente. Recarga e inténtalo de nuevo." },
}
const STATUS = { "awaiting-review": "AWAITING REVIEW", approved: "APPROVED", cancelled: "CANCELLED", "completed-locally": "COMPLETED LOCALLY" } as const
export function PreparedWorkReviewBoard({ locale }: { locale: Locale }) {
  const router = useRouter(); const copy = COPY[locale]; const [records, setRecords] = useState<PreparedWorkRecord[]>([]); const [busy, setBusy] = useState<string | null>(null); const [unavailable, setUnavailable] = useState(false)
  useEffect(() => { void fetch("/api/prepared-work/sync", { method: "POST", credentials: "include" }).then((response) => response.ok ? response.json() : Promise.reject()).then((data) => { if (Array.isArray(data?.records)) setRecords(data.records); else setUnavailable(true) }).catch(() => setUnavailable(true)) }, [])
  async function review(record: PreparedWorkRecord, action: "approve" | "cancel" | "complete-locally") { setBusy(record.id); setUnavailable(false); try { const response = await fetch("/api/prepared-work/review", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ actionId: record.id, action }) }); const data = await response.json().catch(() => null); if (response.ok && data?.record) setRecords((items) => items.map((item) => item.id === record.id ? data.record : item)); else setUnavailable(true) } catch { setUnavailable(true) } finally { setBusy(null) } }
  function openApprovedQuoteDraft(record: PreparedWorkRecord) { if (record.status !== "approved" || record.rationale !== "quote-brief-owner-review-pending") return; const params = new URLSearchParams({ preparedWorkId: record.id, sourceIds: record.sourceIds.join(",") }); router.push(`/business/invoices?prepare=quote&${params.toString()}`) }
 return <section className="border-t border-border px-4 py-6 sm:px-6" aria-labelledby="prepared-work-review-board-title"><p className="ve-eyebrow">PREPARED WORK / OWNER REVIEW</p><h3 id="prepared-work-review-board-title" className="mt-1 font-display text-2xl font-semibold">{copy.title}</h3><p className="mt-2 text-sm text-muted-foreground">{copy.sub}</p>{unavailable && <p role="alert" className="mt-4 rounded-2xl border border-destructive/40 p-4 text-sm text-destructive">{copy.unavailable}</p>}{records.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{records.map((record) => <article key={record.id} className="v4-surface rounded-2xl border p-4"><p className="text-xs font-bold uppercase tracking-wide text-primary">{record.role} · {record.label}</p><strong className="mt-2 block text-sm">{record.title}</strong><p className="mt-2 line-clamp-3 text-xs text-muted-foreground">{record.content}</p><p className="mt-3 text-xs text-muted-foreground">Evidence: {record.sourceIds.length} · {record.rationale}</p><div className="mt-3 flex flex-wrap gap-1 text-[.6rem] font-bold tracking-wide"><span className="rounded-full border px-2 py-1">PREPARED</span><span className="v4-status-review rounded-full border border-gold/35 px-2 py-1">{STATUS[record.status]}</span><span className="rounded-full border px-2 py-1">NOT SENT</span><span className="rounded-full border px-2 py-1">NOT EXECUTED</span></div><div className="mt-4 flex flex-wrap gap-2">{record.status === "awaiting-review" && <button type="button" disabled={busy === record.id} onClick={() => review(record, "approve")} className="min-h-10 rounded-lg border border-primary/40 px-3 text-xs font-semibold text-primary">{copy.review}</button>}{["awaiting-review", "approved"].includes(record.status) && <button type="button" disabled={busy === record.id} onClick={() => review(record, "cancel")} className="min-h-10 rounded-lg border border-border px-3 text-xs">{copy.cancel}</button>}{record.status === "approved" && <button type="button" disabled={busy === record.id} onClick={() => review(record, "complete-locally")} className="min-h-10 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground">{copy.complete}</button>}{record.status === "approved" && record.rationale === "quote-brief-owner-review-pending" && <button type="button" onClick={() => openApprovedQuoteDraft(record)} className="min-h-10 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground">{copy.prepareQuote}</button>}<Link href={record.targetHref} className="inline-flex min-h-10 items-center gap-1 text-xs text-primary">{copy.open}<ArrowUpRight className="size-3" /></Link></div></article>)}</div> : !unavailable && <p className="v4-surface mt-4 rounded-2xl border p-5 text-sm text-muted-foreground"><ShieldCheck className="mr-2 inline size-4 text-primary" />{copy.empty}</p>}</section>
}
