"use client"
import {useMemo,useState} from "react"
import Link from "next/link"
import {AlertTriangle,ArrowRight,BarChart3,CheckCircle2,FileInput,Megaphone,MessageSquarePlus,Receipt,Save,ShieldCheck,Sparkles} from "lucide-react"
import {useI18n} from "@/lib/i18n/provider"
import {useWorkspaceData} from "@/lib/use-workspace-data"
import {createAdVariants,convertQuoteToInvoice,extractTaskCandidates,invoiceTotal,topActions,watchtowerSignals,type IntelligenceInvoice,type IntelligenceTask} from "@/lib/business-intelligence"

type Draft={id:string;type:string;tone:string;recipient?:string;subject?:string;body:string;createdAt:string}
const COPY={
 en:{title:"Business Intelligence",sub:"Seven practical assistants using your real workspace data. Nothing is sent without your action.",morning:"Morning briefing",ads:"One-click ad kit",follow:"Customer follow-up",weekly:"Weekly report",extract:"Tasks from documents",quote:"Quote to invoice",watch:"HEGEVA Watchtower",product:"Product or service",audience:"Audience",benefit:"Main benefit",generate:"Create variants",source:"Paste a contract, email or note",scan:"Find tasks",saveTasks:"Approve and add tasks",noFollow:"No overdue invoices or quotes need follow-up.",draft:"Create message draft",convert:"Create draft invoice",saved:"Saved",open:"Open full module",customers:"Customers",revenue:"Paid revenue",outstanding:"Outstanding",tasks:"Open tasks",newCustomers:"New customers (7 days)"},
 hu:{title:"Üzleti intelligencia",sub:"Hét gyakorlati segéd a valódi munkaterületi adataidból. Semmi nem kerül elküldésre a műveleted nélkül.",morning:"Reggeli összefoglaló",ads:"Egykattintásos reklámcsomag",follow:"Ügyfélkövetés",weekly:"Heti vezetői jelentés",extract:"Feladatok dokumentumokból",quote:"Ajánlatból számla",watch:"HEGEVA Watchtower",product:"Termék vagy szolgáltatás",audience:"Célközönség",benefit:"Legfontosabb előny",generate:"Változatok készítése",source:"Illessz be szerződést, e-mailt vagy jegyzetet",scan:"Feladatok keresése",saveTasks:"Jóváhagyás és feladatok hozzáadása",noFollow:"Nincs utánkövetést igénylő lejárt számla vagy ajánlat.",draft:"Üzenetvázlat készítése",convert:"Számlavázlat készítése",saved:"Mentve",open:"Teljes modul megnyitása",customers:"Ügyfelek",revenue:"Kifizetett bevétel",outstanding:"Kintlévőség",tasks:"Nyitott feladatok",newCustomers:"Új ügyfelek (7 nap)"},
 de:{title:"Business Intelligence",sub:"Sieben praktische Assistenten mit echten Workspace-Daten. Nichts wird ohne Ihre Aktion gesendet.",morning:"Morgenübersicht",ads:"Werbepaket mit einem Klick",follow:"Kundennachverfolgung",weekly:"Wochenbericht",extract:"Aufgaben aus Dokumenten",quote:"Angebot zu Rechnung",watch:"HEGEVA Watchtower",product:"Produkt oder Dienstleistung",audience:"Zielgruppe",benefit:"Hauptvorteil",generate:"Varianten erstellen",source:"Vertrag, E-Mail oder Notiz einfügen",scan:"Aufgaben finden",saveTasks:"Genehmigen und hinzufügen",noFollow:"Keine überfälligen Rechnungen oder Angebote.",draft:"Nachrichtenentwurf",convert:"Rechnungsentwurf erstellen",saved:"Gespeichert",open:"Vollständiges Modul öffnen",customers:"Kunden",revenue:"Bezahlter Umsatz",outstanding:"Offen",tasks:"Offene Aufgaben",newCustomers:"Neue Kunden (7 Tage)"},
 fr:{title:"Intelligence Business",sub:"Sept assistants pratiques basés sur vos vraies données. Rien n’est envoyé sans votre action.",morning:"Résumé du matin",ads:"Kit publicitaire en un clic",follow:"Suivi client",weekly:"Rapport hebdomadaire",extract:"Tâches depuis les documents",quote:"Devis en facture",watch:"HEGEVA Watchtower",product:"Produit ou service",audience:"Public",benefit:"Avantage principal",generate:"Créer les variantes",source:"Collez un contrat, e-mail ou note",scan:"Trouver les tâches",saveTasks:"Approuver et ajouter",noFollow:"Aucune facture ou devis en retard.",draft:"Créer un brouillon",convert:"Créer une facture brouillon",saved:"Enregistré",open:"Ouvrir le module complet",customers:"Clients",revenue:"Revenu payé",outstanding:"Impayé",tasks:"Tâches ouvertes",newCustomers:"Nouveaux clients (7 jours)"},
 es:{title:"Inteligencia empresarial",sub:"Siete asistentes prácticos con datos reales. Nada se envía sin tu acción.",morning:"Resumen matinal",ads:"Kit publicitario en un clic",follow:"Seguimiento de clientes",weekly:"Informe semanal",extract:"Tareas desde documentos",quote:"Presupuesto a factura",watch:"HEGEVA Watchtower",product:"Producto o servicio",audience:"Público",benefit:"Beneficio principal",generate:"Crear variantes",source:"Pega un contrato, email o nota",scan:"Buscar tareas",saveTasks:"Aprobar y añadir",noFollow:"No hay facturas o presupuestos vencidos.",draft:"Crear borrador",convert:"Crear factura borrador",saved:"Guardado",open:"Abrir módulo completo",customers:"Clientes",revenue:"Ingresos pagados",outstanding:"Pendiente",tasks:"Tareas abiertas",newCustomers:"Nuevos clientes (7 días)"},
} as const

export function BusinessIntelligenceCenter(){
 const{locale}=useI18n(),c=COPY[locale],today=new Date().toISOString().slice(0,10)
 const{items:tasks,setItems:setTasks}=useWorkspaceData<IntelligenceTask>("planner"),{items:invoices,setItems:setInvoices}=useWorkspaceData<IntelligenceInvoice>("invoice_documents"),{items:messages,setItems:setMessages}=useWorkspaceData<Draft>("messages"),{items:customers}=useWorkspaceData<{id:string;title?:string;createdAt?:string}>("customers")
 const[product,setProduct]=useState(""),[audience,setAudience]=useState(""),[benefit,setBenefit]=useState(""),[source,setSource]=useState(""),[notice,setNotice]=useState("")
 const ads=useMemo(()=>createAdVariants(product,audience,benefit),[product,audience,benefit]),candidates=useMemo(()=>extractTaskCandidates(source),[source]),signals=useMemo(()=>watchtowerSignals(tasks,invoices,today),[tasks,invoices,today])
 const followups=invoices.filter(x=>(x.type==="invoice"&&x.status!=="paid"||x.type==="quote")&&x.dueDate<today)
 const paid=invoices.filter(x=>x.type==="invoice"&&x.status==="paid").reduce((s,x)=>s+invoiceTotal(x),0),outstanding=invoices.filter(x=>x.type==="invoice"&&x.status!=="paid").reduce((s,x)=>s+invoiceTotal(x),0),weekAgo=Date.now()-7*86400000
 const metrics=[[c.customers,customers.length],[c.newCustomers,customers.filter(x=>x.createdAt&&new Date(x.createdAt).getTime()>=weekAgo).length],[c.revenue,`£${paid.toFixed(2)}`],[c.outstanding,`£${outstanding.toFixed(2)}`],[c.tasks,tasks.filter(x=>!x.done).length]]
 const addDraft=(doc:IntelligenceInvoice)=>{setMessages(xs=>[{id:crypto.randomUUID(),type:doc.type==="invoice"?"Payment reminder":"Follow-up",tone:"Professional",recipient:doc.clientName,subject:doc.type==="invoice"?`Payment reminder: ${doc.number}`:`Following up: ${doc.number}`,body:`Hello ${doc.clientName},\n\nI am following up regarding ${doc.number}. Please let me know if you need any further information.\n\nKind regards`,createdAt:new Date().toISOString()},...xs]);setNotice(c.saved)}
 const panel="glass-panel rounded-3xl p-5 sm:p-6",button="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-40",input="min-h-11 w-full rounded-xl border border-border bg-input/30 px-3 py-2.5 text-sm"
 return <div className="space-y-6">
  <section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold"><Sparkles className="size-5 text-primary"/>{c.morning}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{topActions(tasks,invoices,today).map(x=><div key={x} className="rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm font-medium">{x}</div>)}</div></section>
  <div className="grid gap-6 xl:grid-cols-2"><section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold"><Megaphone className="size-5 text-primary"/>{c.ads}</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><input className={input} value={product} onChange={e=>setProduct(e.target.value)} placeholder={c.product}/><input className={input} value={audience} onChange={e=>setAudience(e.target.value)} placeholder={c.audience}/><input className={input} value={benefit} onChange={e=>setBenefit(e.target.value)} placeholder={c.benefit}/></div><div className="mt-4 space-y-3">{ads.map(x=><article key={x.channel} className="rounded-2xl border border-border p-4"><strong>{x.channel} · {x.headline}</strong><p className="mt-2 text-sm text-muted-foreground">{x.body}</p><small className="mt-2 block text-primary">{x.cta}</small></article>)}</div><Link href="/app-studio/advertising" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-primary">{c.open}<ArrowRight className="size-4"/></Link></section>
  <section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold"><MessageSquarePlus className="size-5 text-primary"/>{c.follow}</h2><div className="mt-4 space-y-3">{followups.length?followups.slice(0,6).map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border p-4"><div><strong>{x.number}</strong><p className="text-sm text-muted-foreground">{x.clientName} · {x.dueDate}</p></div><button className={button} onClick={()=>addDraft(x)}>{c.draft}</button></div>):<p className="text-sm text-muted-foreground">{c.noFollow}</p>}</div><Link href="/business/messages" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-primary">{c.open}<ArrowRight className="size-4"/></Link></section></div>
  <section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold"><BarChart3 className="size-5 text-primary"/>{c.weekly}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{metrics.map(([label,value])=><div key={String(label)} className="rounded-2xl border border-border p-4"><p className="text-xs text-muted-foreground">{label}</p><strong className="mt-2 block text-2xl">{value}</strong></div>)}</div></section>
  <div className="grid gap-6 xl:grid-cols-2"><section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold"><FileInput className="size-5 text-primary"/>{c.extract}</h2><textarea className={`${input} mt-4 min-h-32`} value={source} onChange={e=>setSource(e.target.value)} placeholder={c.source}/><div className="mt-4 space-y-2">{candidates.map(x=><p key={x.id} className="rounded-xl border border-border p-3 text-sm">{x.title}{x.due&&<small className="ml-2 text-primary">{x.due}</small>}</p>)}</div><button disabled={!candidates.length} className={`${button} mt-4`} onClick={()=>{setTasks(xs=>[...candidates.map(x=>({id:crypto.randomUUID(),title:x.title,due:x.due,priority:"medium" as const,done:false})),...xs]);setNotice(c.saved)}}><Save className="size-4"/>{c.saveTasks}</button></section>
  <section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold"><Receipt className="size-5 text-primary"/>{c.quote}</h2><div className="mt-4 space-y-3">{invoices.filter(x=>x.type==="quote").slice(0,8).map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border p-4"><div><strong>{x.number}</strong><p className="text-sm text-muted-foreground">{x.clientName} · {x.currency} {invoiceTotal(x).toFixed(2)}</p></div><button className={button} onClick={()=>{setInvoices(xs=>[convertQuoteToInvoice(x,xs),...xs]);setNotice(c.saved)}}>{c.convert}</button></div>)}</div><Link href="/business/invoices" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-primary">{c.open}<ArrowRight className="size-4"/></Link></section></div>
  <section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold"><ShieldCheck className="size-5 text-primary"/>{c.watch}</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{signals.map(x=><article key={x.title} className={`rounded-2xl border p-4 ${x.severity==="critical"?"border-destructive/40 bg-destructive/5":x.severity==="warning"?"border-amber-400/30 bg-amber-400/5":"border-primary/25 bg-primary/5"}`}><div className="flex items-center gap-2"><AlertTriangle className="size-4"/><strong>{x.title}</strong></div><p className="mt-2 text-sm text-muted-foreground">{x.evidence}</p></article>)}</div>{notice&&<p role="status" className="mt-4 flex items-center gap-2 text-sm text-primary"><CheckCircle2 className="size-4"/>{notice}</p>}</section>
 </div>
}
