"use client"

import { CalendarDays, Mail, PlugZap, ShieldCheck } from "lucide-react"
import { useI18n } from "@/lib/i18n/provider"

const COPY = {
  en: { eye:"INTEGRATIONS V1 · SAFE FOUNDATION", title:"Bring your real business signals into one operating picture.", sub:"Email and calendar connections are prepared for secure OAuth setup. They remain unavailable until a workspace owner configures and explicitly authorises each provider.", required:"Setup required", connect:"Connection unavailable", mail:"Email", mailText:"Prepare customer follow-ups from authorised mailbox context. HEGEVA will not send a message without a separate owner approval.", calendar:"Calendar", calendarText:"Use authorised events to improve planning and daily priorities. HEGEVA will not create or change events without approval.", boundary:"No account is connected, no external data is read, and no action is performed in the current production configuration.", next:"Next activation step", nextText:"Add provider credentials, verified redirect URLs and consent-screen details, then complete a security review before enabling Connect." },
  hu: { eye:"INTEGRÁCIÓK V1 · BIZTONSÁGOS ALAP", title:"Hozd be a valódi üzleti jelzéseket egyetlen működési képbe.", sub:"Az e-mail- és naptárkapcsolatok biztonságos OAuth-beállításra vannak előkészítve. Addig nem érhetők el, amíg a munkaterület tulajdonosa nem konfigurálja és külön nem engedélyezi őket.", required:"Beállítás szükséges", connect:"A kapcsolódás még nem érhető el", mail:"E-mail", mailText:"Ügyfél-utánkövetések előkészítése az engedélyezett postafiók alapján. A HEGEVA külön tulajdonosi jóváhagyás nélkül nem küld üzenetet.", calendar:"Naptár", calendarText:"Az engedélyezett események használata a tervezés és napi prioritások javítására. A HEGEVA jóváhagyás nélkül nem hoz létre és nem módosít eseményt.", boundary:"A jelenlegi production konfigurációban nincs csatlakoztatott fiók, külső adatolvasás vagy végrehajtott művelet.", next:"Következő aktiválási lépés", nextText:"Szolgáltatói azonosítók, ellenőrzött visszahívási címek és hozzájárulási képernyő hozzáadása, majd biztonsági ellenőrzés a Kapcsolódás engedélyezése előtt." },
  de: { eye:"INTEGRATIONEN V1 · SICHERE BASIS", title:"Reale Geschäftssignale in einem Betriebsbild bündeln.", sub:"E-Mail- und Kalenderverbindungen sind für sicheres OAuth vorbereitet. Sie bleiben deaktiviert, bis ein Workspace-Eigentümer sie konfiguriert und ausdrücklich autorisiert.", required:"Einrichtung erforderlich", connect:"Verbindung nicht verfügbar", mail:"E-Mail", mailText:"Kunden-Follow-ups aus autorisiertem Postfachkontext vorbereiten. Keine Nachricht wird ohne separate Freigabe gesendet.", calendar:"Kalender", calendarText:"Autorisierte Termine für Planung und Prioritäten nutzen. Keine Termine werden ohne Freigabe geändert.", boundary:"Aktuell ist kein Konto verbunden; externe Daten werden weder gelesen noch Aktionen ausgeführt.", next:"Nächster Aktivierungsschritt", nextText:"Provider-Zugangsdaten, geprüfte Redirect-URLs und Consent-Details hinzufügen und vor Aktivierung sicherheitsprüfen." },
  fr: { eye:"INTÉGRATIONS V1 · BASE SÉCURISÉE", title:"Réunissez vos vrais signaux d’entreprise dans une vue opérationnelle.", sub:"Les connexions e-mail et calendrier sont préparées pour OAuth sécurisé. Elles restent désactivées sans configuration et autorisation explicite du propriétaire.", required:"Configuration requise", connect:"Connexion indisponible", mail:"E-mail", mailText:"Préparer les relances depuis une boîte autorisée. Aucun message n’est envoyé sans approbation distincte.", calendar:"Calendrier", calendarText:"Utiliser les événements autorisés pour améliorer les priorités. Aucun événement n’est modifié sans approbation.", boundary:"Aucun compte n’est connecté, aucune donnée externe n’est lue et aucune action n’est exécutée actuellement.", next:"Prochaine étape d’activation", nextText:"Ajouter les identifiants, URL de redirection vérifiées et détails de consentement, puis effectuer une revue de sécurité." },
  es: { eye:"INTEGRACIONES V1 · BASE SEGURA", title:"Reúne señales reales del negocio en una vista operativa.", sub:"Las conexiones de correo y calendario están preparadas para OAuth seguro. Permanecen desactivadas hasta que el propietario las configure y autorice expresamente.", required:"Configuración necesaria", connect:"Conexión no disponible", mail:"Correo", mailText:"Preparar seguimientos desde un buzón autorizado. No se envía ningún mensaje sin aprobación independiente.", calendar:"Calendario", calendarText:"Usar eventos autorizados para mejorar prioridades. Ningún evento se modifica sin aprobación.", boundary:"Actualmente no hay cuentas conectadas, lectura de datos externos ni acciones ejecutadas.", next:"Siguiente paso de activación", nextText:"Añadir credenciales, redirecciones verificadas y datos de consentimiento, y completar una revisión de seguridad." }
} as const

export function IntegrationCenter(){
  const { locale } = useI18n(); const c = COPY[locale]
  const providers = [{icon:Mail,title:c.mail,text:c.mailText,names:"Gmail · Microsoft Outlook"},{icon:CalendarDays,title:c.calendar,text:c.calendarText,names:"Google Calendar · Microsoft Calendar"}]
  return <main className="mx-auto max-w-6xl px-4 py-12 sm:px-6 lg:px-8">
    <p className="ve-eyebrow">{c.eye}</p><h1 className="mt-3 max-w-4xl font-display text-3xl font-semibold sm:text-5xl">{c.title}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">{c.sub}</p>
    <div className="mt-8 grid gap-5 md:grid-cols-2">{providers.map(({icon:Icon,title,text,names})=><section key={title} className="rounded-3xl border border-border bg-card/70 p-6"><div className="flex items-start justify-between gap-4"><span className="rounded-2xl border border-primary/25 bg-primary/10 p-3"><Icon className="size-6 text-primary"/></span><span className="rounded-full border border-amber-400/30 bg-amber-400/10 px-3 py-1 text-xs text-amber-200">{c.required}</span></div><h2 className="mt-5 text-xl font-semibold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{names}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p><button type="button" disabled className="mt-5 min-h-11 w-full cursor-not-allowed rounded-xl border border-border bg-muted/30 px-4 text-sm text-muted-foreground" aria-disabled="true">{c.connect}</button></section>)}</div>
    <section className="mt-6 rounded-3xl border border-emerald-400/25 bg-emerald-400/[.06] p-6"><p className="flex gap-2 text-sm"><ShieldCheck className="size-5 shrink-0 text-emerald-300"/>{c.boundary}</p></section>
    <section className="mt-5 rounded-3xl border border-border p-6"><h2 className="flex items-center gap-2 font-semibold"><PlugZap className="size-5 text-primary"/>{c.next}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{c.nextText}</p></section>
  </main>
}
