"use client"

import { ChangeEvent, useMemo, useState } from "react"
import { BellRing, Download, FileUp, TrendingDown, TrendingUp } from "lucide-react"
import { useI18n } from "@/lib/i18n/provider"
import { useWorkspaceData } from "@/lib/use-workspace-data"
import { extractTaskCandidates, invoiceTotal, type IntelligenceInvoice, type IntelligenceTask } from "@/lib/business-intelligence"

type Customer={id:string;createdAt?:string}
const COPY={
 en:{title:"Operations expansion",weekly:"Verified weekly comparison",current:"This week",previous:"Previous week",revenue:"Paid revenue",customers:"New customers",tasks:"Completed tasks",download:"Download management report",documents:"Document intake",upload:"Choose a text document",limit:"TXT and Markdown, maximum 256 KB. Nothing is uploaded to an external AI provider.",found:"task candidates found",add:"Approve and add tasks",alerts:"Action centre",overdue:"overdue tasks",unpaid:"overdue invoices",clear:"No urgent action detected"},
 hu:{title:"Működési bővítmény",weekly:"Ellenőrzött heti összehasonlítás",current:"Ez a hét",previous:"Előző hét",revenue:"Kifizetett bevétel",customers:"Új ügyfelek",tasks:"Lezárt feladatok",download:"Vezetői jelentés letöltése",documents:"Dokumentumbeolvasás",upload:"Szöveges dokumentum kiválasztása",limit:"TXT és Markdown, legfeljebb 256 KB. Semmi nem kerül külső AI-szolgáltatóhoz.",found:"feladatjelölt található",add:"Jóváhagyás és feladatok hozzáadása",alerts:"Teendőközpont",overdue:"lejárt feladat",unpaid:"lejárt számla",clear:"Nincs sürgős teendő"},
 de:{title:"Betriebserweiterung",weekly:"Geprüfter Wochenvergleich",current:"Diese Woche",previous:"Vorwoche",revenue:"Bezahlter Umsatz",customers:"Neue Kunden",tasks:"Erledigte Aufgaben",download:"Managementbericht herunterladen",documents:"Dokumentimport",upload:"Textdokument auswählen",limit:"TXT und Markdown, maximal 256 KB. Keine Übertragung an externe KI.",found:"Aufgabenkandidaten gefunden",add:"Genehmigen und hinzufügen",alerts:"Aktionszentrum",overdue:"überfällige Aufgaben",unpaid:"überfällige Rechnungen",clear:"Keine dringende Aktion"},
 fr:{title:"Extension opérationnelle",weekly:"Comparaison hebdomadaire vérifiée",current:"Cette semaine",previous:"Semaine précédente",revenue:"Revenu payé",customers:"Nouveaux clients",tasks:"Tâches terminées",download:"Télécharger le rapport",documents:"Import de document",upload:"Choisir un document texte",limit:"TXT et Markdown, 256 Ko maximum. Aucun envoi vers une IA externe.",found:"tâches candidates",add:"Approuver et ajouter",alerts:"Centre d’actions",overdue:"tâches en retard",unpaid:"factures en retard",clear:"Aucune action urgente"},
 es:{title:"Extensión operativa",weekly:"Comparación semanal verificada",current:"Esta semana",previous:"Semana anterior",revenue:"Ingresos pagados",customers:"Nuevos clientes",tasks:"Tareas completadas",download:"Descargar informe",documents:"Importar documento",upload:"Elegir documento de texto",limit:"TXT y Markdown, máximo 256 KB. Sin envío a IA externa.",found:"tareas candidatas",add:"Aprobar y añadir",alerts:"Centro de acciones",overdue:"tareas vencidas",unpaid:"facturas vencidas",clear:"No hay acciones urgentes"},
} as const

export function OperationsExpansion(){
 const{locale}=useI18n(),c=COPY[locale]
 const{items:tasks,setItems:setTasks}=useWorkspaceData<IntelligenceTask>("planner")
 const{items:invoices}=useWorkspaceData<IntelligenceInvoice>("invoice_documents")
 const{items:customers}=useWorkspaceData<Customer>("customers")
 const[source,setSource]=useState(""),[fileError,setFileError]=useState("")
 const now=Date.now(),week=7*86400000,start=now-week,prior=now-2*week
 const inRange=(value:string|undefined,a:number,b:number)=>Boolean(value&&Date.parse(value)>=a&&Date.parse(value)<b)
 const metrics=useMemo(()=>{const revenue=(a:number,b:number)=>invoices.filter(x=>x.type==="invoice"&&x.status==="paid"&&inRange(x.updatedAt,a,b)).reduce((s,x)=>s+invoiceTotal(x),0);return [{label:c.revenue,current:revenue(start,now),previous:revenue(prior,start),money:true},{label:c.customers,current:customers.filter(x=>inRange(x.createdAt,start,now)).length,previous:customers.filter(x=>inRange(x.createdAt,prior,start)).length},{label:c.tasks,current:tasks.filter(x=>x.done&&inRange((x as IntelligenceTask&{updatedAt?:string}).updatedAt,start,now)).length,previous:tasks.filter(x=>x.done&&inRange((x as IntelligenceTask&{updatedAt?:string}).updatedAt,prior,start)).length}]},[c,customers,invoices,now,prior,start,tasks])
 const candidates=useMemo(()=>extractTaskCandidates(source),[source]),today=new Date().toISOString().slice(0,10),overdue=tasks.filter(x=>!x.done&&x.due&&x.due<today).length,unpaid=invoices.filter(x=>x.type==="invoice"&&x.status!=="paid"&&x.dueDate<today).length
 const readFile=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];setFileError("");if(!file)return;if(file.size>262144||!(/\.(txt|md)$/i.test(file.name))){setFileError(c.limit);return}setSource(await file.text())}
 const addTasks=()=>setTasks(xs=>[...candidates.map(x=>({id:crypto.randomUUID(),title:x.title,due:x.due,priority:"medium" as const,done:false})),...xs])
 const download=()=>{const lines=[c.weekly,...metrics.map(x=>`${x.label}: ${x.current} (${c.previous}: ${x.previous})`),`${c.overdue}: ${overdue}`,`${c.unpaid}: ${unpaid}`];const url=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/plain;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`hegeva-weekly-${today}.txt`;a.click();URL.revokeObjectURL(url)}
 return <section className="mt-6 space-y-6"><h2 className="font-display text-2xl">{c.title}</h2><div className="grid gap-6 xl:grid-cols-2"><div className="glass-panel rounded-3xl p-5 sm:p-6"><h3 className="font-display text-xl">{c.weekly}</h3><div className="mt-4 grid gap-3 sm:grid-cols-3">{metrics.map(x=>{const up=x.current>=x.previous;return <div key={x.label} className="rounded-2xl border border-border p-4"><p className="text-xs text-muted-foreground">{x.label}</p><strong className="mt-2 block text-xl">{x.money?`£${x.current.toFixed(2)}`:x.current}</strong><span className={`mt-1 inline-flex items-center gap-1 text-xs ${up?"text-primary":"text-amber-500"}`}>{up?<TrendingUp className="size-3"/>:<TrendingDown className="size-3"/>}{c.previous}: {x.money?`£${x.previous.toFixed(2)}`:x.previous}</span></div>})}</div><button onClick={download} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground"><Download className="size-4"/>{c.download}</button></div><div className="glass-panel rounded-3xl p-5 sm:p-6"><h3 className="font-display text-xl">{c.documents}</h3><label className="mt-4 flex min-h-12 cursor-pointer items-center gap-2 rounded-xl border border-dashed border-primary/40 px-4 text-sm"><FileUp className="size-4"/>{c.upload}<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={readFile} className="sr-only"/></label><p className="mt-2 text-xs text-muted-foreground">{c.limit}</p>{fileError&&<p className="mt-2 text-sm text-destructive">{fileError}</p>}<p className="mt-4 text-sm">{candidates.length} {c.found}</p><button disabled={!candidates.length} onClick={addTasks} className="mt-3 min-h-11 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-40">{c.add}</button></div></div><div className="glass-panel rounded-3xl p-5 sm:p-6"><h3 className="flex items-center gap-2 font-display text-xl"><BellRing className="size-5 text-primary"/>{c.alerts}</h3><div className="mt-4 flex flex-wrap gap-3">{overdue||unpaid?<><span className="rounded-full border border-amber-400/40 px-3 py-2 text-sm">{overdue} {c.overdue}</span><span className="rounded-full border border-destructive/40 px-3 py-2 text-sm">{unpaid} {c.unpaid}</span></>:<span className="rounded-full border border-primary/30 px-3 py-2 text-sm text-primary">{c.clear}</span>}</div></div></section>
}
